### ISSUE TITLE
ItemFormat "%5.5i%|%5.5l%5.2>%|"

### ISSUE THREAD

**Issue by rasatpc** [fvwmorg/fvwm3#1008]
## Upfront Information

This is @Franky's complaint from the forum. This `ItemFormat "%5.5i%|%5.5l%5.2>%|"` worked in Fvwm2. In Fvwm3, the menu icon is flickering when highlighted. 
https://fvwmforums.org/t/strange-highlighting-of-icon-in-menu/4615

Is this a bug or an incorrect ItemFormat option?
I like this unusual option and plan to add it to myExt config collection.

**Comment by ThomasAdam** [comment]
Well, this a good job for git-bisect if ever there were one. 

@rasatpc -- are you able to reproduce this problem as well? I know you're filing this bug report on behalf of someone else, but you own this now. 

Any additional information you can provide would help. I can't reproduce this, FWIW.

**Comment by rasatpc** [comment]
First I didn't pay attention to this topic. When Ivar wrote that he tried and later got it to flicker with @Franky's config and icon. I tried the config and downloaded the icon. It is flickering.

@ThomasAdam , before trying the config, check if the ItemFormat code is correctly written.

```
ImagePath ${HOME}/.fvwm/images
Key Space   A   4   Popup Menu_Main

Colorset 0 fg white, bg black
Colorset 1 fg black, bg #FA0000

MenuStyle * Font "xft:Bitstream Vera Sans Mono:style=Roman:size=12"
MenuStyle * TrianglesSolid
MenuStyle * HilightBack
MenuStyle * MenuColorset 0
MenuStyle * ActiveColorset 1
MenuStyle * ItemFormat "%5.5i%|%5.5l%5.2>%|"

DestroyMenu Menu_Main
AddToMenu   Menu_Main
+ %music.note-24x24.png%"&This" Popup Menu_This
+ "T&hat" Popup Menu_That
+ "The &Other" Popup Menu_TheOther

```

**Comment by somiaj** [comment]
@rasatpc thanks for helping others try to get issues they have fixed, but first you need to first confirm that you can reproduce the bug (since we can work with you to ensure it is fixed).

In this case you should first confirm you experience the exact same issue reported, and second that this issue is not present in fvwm2. Then once you do that, being able to do a bit more like `git-bisect` could help us. I tried to reproduce this bug too, and I cannot reproduce it either.

**Comment by rasatpc** [comment]
> confirm that you can reproduce

1. Fresh Fvwm3 install
2. Slight modification on Franky's config, file: menu-icon.sys
```
## menu-icon.sys
ImagePath ${HOME}/.fvwm/images
Colorset 0 fg white, bg black
Colorset 1 fg black, bg #FA0000

MenuStyle * Font "xft:Bitstream Vera Sans Mono:style=Roman:size=12"
MenuStyle * TrianglesSolid
MenuStyle * HilightBack
MenuStyle * HilightTitleBack
MenuStyle * MenuColorset 0
MenuStyle * ActiveColorset 1
MenuStyle * ItemFormat "%5.5i%|%5.5l%5.2>%|"

DestroyMenu MenuFvwmRoot
AddToMenu   MenuFvwmRoot "TEST Menu" Title
+ %music.note-24x24.png%"&This" Popup Menu_This
+ "T&hat" Popup Menu_That
+ "The &Other" Popup Menu_TheOther
+ "Xterm%$[micon]/terminal.png%" Exec exec xterm
+ "Restart%$[micon]/refresh.png%" Restart
```
3. `Read menu-icon.sys`
https://rasatpc.net/screenshot/fvwm3/menu-icon-test.png

Menu on right-side, highlight "This" with icon. The icon is brighter than the left side.

>  issue is not present in fvwm2

Somewhere, Franky mentioned Fvwm2 and also mentioned continuing to use it instead of Fvwm3.
When I tested on 2.7.0, it showed the same bright icon. Could it be without brighness on 2.6.x??

**Comment by ThomasAdam** [comment]
If this is happening in fvwm2 as well, this tells me it's a regression I'm unlikely to fix any time soon.
