### ISSUE TITLE
FvwmPager grid disappears

### ISSUE THREAD

**Issue by rasatpc** [fvwmorg/fvwm3#1014]
* Fvwm3 version (run: `fvwm3 --version`)

1.1.1 update {17 April) and the latest, miniature view disappears after 2nd time the desk is changed..... Desk 0, Desk 1, Desk 0, Desk 1 (disappears).

10th April update works fine.

**Comment by somiaj** [comment]
The pager is undergoing a lot of work right now, so if I broke something I'd like to fix it. But your description doesn't help me. Do you have a video screen shots of what is happening when the '2nd time desk is changed', also can you share a copy of the configuration you are using for the pager?

**Comment by rasatpc** [comment]
Default config with RightPanel.  Click on FvwmPager's lable 0 and another desk number a few times.

No hurry, developments for 1.1.1 look great.

**Comment by somiaj** [comment]
Thanks for the description, I was able to reproduce this. FvwmPager is crashing, which was due to a minor typo in the code.

I have been working on other things, so fixed this on top of that. Give #1015 a test.

**Comment by rasatpc** [comment]
> Give #1015 a test.

Thanks, works fine.
