### ISSUE TITLE
fvwm 1.1.0 crash and logout when launch pycharm

### ISSUE THREAD

**Issue by mdimos** [fvwmorg/fvwm3#1021]
fvwm 1.1.0 crash and logout when launch pycharm

#system:
#Manjaro
#kernel:6.1.85.1

#pycharm-2023

**Comment by mdimos** [comment]
> fvwm 1.1.0 crash and logout when launch pycharm
> 
> #system: #Manjaro #kernel:6.1.85.1
> 
> #pycharm-2023

Wrong bug report, pycharm made gnome, KDE, plasma, fvwm crash, that is kernel issue or pycharm issue

**Comment by ThomasAdam** [comment]
Hi @mdimos,

Could you provide more information, please?

Does fvwm3 crash with a core file?

**Comment by mdimos** [comment]
> Hi @mdimos,
> 
> Could you provide more information, please?
> 
> Does fvwm3 crash with a core file?

sorry, wrong bug report, pycharm made gnome, KDE, plasma, fvwm crash, that is kernel issue or pycharm issue
