### ISSUE TITLE
SVG icons not work

### ISSUE THREAD

**Issue by yoursaf** [fvwmorg/fvwm3#1027]
When I upgrade to fvwm3,all SVG format icons can't display.
+   "%google-chrome.svg%&Chrome"		    Exec exec $[fvwm_browser]
or
+   "%utilities-terminal.svg:$[icon_size]%&Urxvt"  Exec exec urxvt
those 2 format code all not work.
![329914468-1af1b198-c12a-4f32-838d-cd3b513472bd](https://github.com/fvwmorg/fvwm3/assets/6297929/6e17fa1d-9f04-4714-bb7a-e807e6ee5e48)

Please help me fix this issue.
TYVM

**Comment by ThomasAdam** [comment]
Hi @yoursaf 

You'll need to supply a lot more information before we can help you with your problem.  In fact, the issue template which comes with new issues to be filled out already details the key information we typically need.

To start with, can you paste the output from running the following command:

```
fvwm3 --version
```

**Comment by yoursaf** [comment]
`fvwm3 --version`
`fvwm3 1.1.0 (released)
with support for:  ReadLine, PNG, Shape, XShm, SM, XRandR, XRender, XFT, NLS

fvwm3 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of fvwm under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.`

**Comment by ThomasAdam** [comment]
Hi @yoursaf 

Your version of fvwm doesn't have SVG compiled into it.

**Comment by yoursaf** [comment]
So, how can i get svg support vision ?
I'm in Archlinux,use yay to install fvwm3

**Comment by somiaj** [comment]
You will have to look at how the package is being built. If yay installs a prebuilt binary, you'll have to talk to the person who made the binary to include svg support, if it downloads source and builds it, you'll have to install the development headers for svg. Either way this isn't an fvwm3 issue, but an issue with whoever created the package you are installing.

**Comment by ThomasAdam** [comment]
Well. That's me. 🙂

But installing librsvg should be enough.

**Comment by yoursaf** [comment]
> Well. That's me. 🙂
> 
> But installing librsvg should be enough.

install libsvg not working.
i install fvwm3-git version,its fixed.
