### ISSUE TITLE
FvwmCommand doesn't find socket

### ISSUE THREAD

**Issue by akovalenko** [fvwmorg/fvwm3#1034]
After commit da4387bd84c6dcf7e4483d545c48610e5420992b, I started using FVWMMFL_SOCKET_PATH to put sockets into $XDG_RUNTIME_DIR/fvwm (which is the right place for multi-user system)

FvwmMFL (from the default config) creates a socket and provides FVWMMFL_SOCKET in the environment.

The problem is, FvwmCommand in da4387bd84c6dcf7e4483d545c48610e5420992b doesn't take FVWMMFL_SOCKET into account, resorting to guessing the socket path from FVWMMFL_SOCKET_PATH and DISPLAY. On my system it happens to guess *wrongly*: when the socket is created, it uses DISPLAY=:1 (as received from .Xsession), but under fvwm3, I have DISPLAY=:1.0 (with screen number). 

## Upfront Information

* Fvwm3 version (run: `fvwm3 --version`): fvwm3 1.1.1 (1.1.0-64-gf0366381)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS

* Linux distribution or BSD name/version: Ubuntu jammy

* Platform (run: `uname -sp`): Linux x86_64

## Expected Behaviour

Launched XTerm from FVWM, started FvwmCommand Module FvwmConsole, expected to see the console

## Actual Behaviour

```
Cannot find FvwmMFL socket /run/user/1000/fvwm/fvwm_mfl_:1.0.sock.
Please start FvwmMFL module from your fvwm configuration.
```

## Steps to Reproduce

How can the problem be reproduced?  
* Have screenless DISPLAY=:n in your fvwm3's starting environment
* Get DISPLAY=:n.0 in an XTerm launched by fvwm
* See how FvwmCommand fails to guess the socket path

**Comment by ThomasAdam** [comment]
Hi @akovalenko 

Thanks.  Can you please try `FvwmCommand` from the `ta/fvwmmfl-display-socket3` branch?

This should now be working correctly.

**Comment by akovalenko** [comment]
Hi @ThomasAdam, `FvwmCommand` from `ta/fvwmmfl-display-socket3` works for me.

**Comment by ThomasAdam** [comment]
Hey @akovalenko 

Awesome. Thanks for testing!
