### ISSUE TITLE
EdgeCommand stopped working in 1.0.9

### ISSUE THREAD

**Issue by lormaccone** [fvwmorg/fvwm3#1036]
After upgrading from 1.0.8 the EdgeCommand stopped working.

Relevant lines of the config file:

EdgeCommand Bottom Function Bottommenu
EdgeCommand Left Menu Utilities
EdgeCommand Top Function Topmenu

I installed (in the same system!) both 1.0.8 and 1.0.9, 1.1.0 and 1.1.1 
All the newer versions do not work (the menu doesn't appear when the mouse is on the edge of the screen), whereas in 1.0.8 the menu appears. Again, everything else (including the config file, installed libraries, etc.) is the same. Gentoo linux.

## Upfront Information

* Fvwm3 version (run: `fvwm3 --version`):

lor@Challenger ~ $ /usr/local/bin/fvwm3 --version
fvwm3 1.0.8 (released)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS

fvwm3 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of fvwm under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

lor@Challenger ~ $ /usr/bin/fvwm3 --version
fvwm3 1.0.9 (released)
with support for:  ReadLine, XPM, PNG, Shape, XShm, SM, XRandR, XRender, XCursor, XFT, NLS

fvwm3 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of fvwm under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

* Linux distribution or BSD name/version
Gentoo linux

* Platform (run: `uname -sp`)
Linux Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz

## Expected Behaviour

The menus should appear (and they appear in 1.0.8) when the mouse cursor is moved to the right top or bottom edges of the screen.

## Actual Behaviour

The menus do not appear in 1.0.9, 1.1.0, 1.1.1 but they do appear in 1.0.8.

## Steps to Reproduce

How can the problem be reproduced?  For this, the following is helpful:

* Reduce the problem to the smallest `fvwm` configuration example (where
  possible).  Start with a blank config file (`fvwm3 -f/dev/null`) and go from
  there.

The problem persists with the following minimal configuration file:

EdgeCommand Bottom Menu Utilities

AddToMenu Utilities "Lorenzo's Fvwm" Title
#+              "GNOME" Exec exec gnome-panel&
+              "Applications" Popup Applications

## Does Fvwm3 crash?

No

## Extra Information

No

**Comment by ThomasAdam** [comment]
Does:

```
EdgeThickness 2
```

Help?  If you set that before setting `EdgeCommand` in your config?

**Comment by lormaccone** [comment]
Wow, that was really quick! Thanks! Yes, that restored functionality both in 1.1.1 and in 1.0.9 

THANK YOU!
