### ISSUE TITLE
Right Panel button shows wrong desk after restart

### ISSUE THREAD

**Issue by rasatpc** [fvwmorg/fvwm3#1049]
* Fvwm3 version (run: `fvwm3 --version`)
fvwm3 1.1.1 (1.1.0-68-gd26bed64)

After restarting Fvwm, the Right Panel button shows the wrong desk. When on a desk other than 0, the pager miniature view is correct but the button desk 0 appears.
https://fvwmforums.org/t/rightpanel-buttons-display-incorrect-desk-after-fvwm-restart/4680/4

No fix or config seems to correct the button. The Right Panel gets stuck until updated.

**Comment by ThomasAdam** [comment]
Thanks. But I'm already dealing with this. 

Could you, in the future not file bugs on other's behalf? The issue in doing that is you're not the one with the problem, which means you're not going to necessarily be able to offer appropriate feedback. 

Thanks for trying to be helpful though.
