### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [fvwmorg/fvwm3#108]
[An extra null pointer check is not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [Circulate](https://github.com/fvwmorg/fvwm3/blob/4a639a8648f4f6a2a6273a827f2299c6cccaf30c/fvwm/conditional.c#L88 "Circulate function")
- [pop_menu_up](https://github.com/fvwmorg/fvwm3/blob/4a639a8648f4f6a2a6273a827f2299c6cccaf30c/fvwm/menus.c#L3212 "pop_menu_up function")

**Comment by ThomasAdam** [comment]
Hi @elfring,

Yes, you're right.  The only exception to this in `FVWM3`'s code base is when calling `XFree()` -- if you pass NULL in to that, X11 will more often than not segfault.  It *shouldn't* do, but it does.

Would you mind writing a cocci script to handle these checks so we can start applying it to the codebase?

Thanks!

**Comment by elfring** [comment]
I am curious then if another software developer (besides me) can get into the mood to apply a corresponding update suggestion which could be generated by [the software “Coccinelle”](http://coccinelle.lip6.fr/ "Source code transformation with Coccinelle") (also with the help of a variant from the following script).

```
@Remove_unnecessary_pointer_checks@
expression x;
@@
-if (\(x != 0 \| x != NULL\))
    free(x);
```

**Comment by ThomasAdam** [comment]
@elfring,

> I am curious then if another software developer (besides me) can get into the mood to apply a corresponding update suggestion which could be generated by [the software “Coccinelle”](http://coccinelle.lip6.fr/) (also with the help of a variant from the following script).

At present, the only person who could "get into the mood" is myself, as it's just me working on this project.  I'd be happy to take a look, but ideally I'd like to be on the reviewing-end of this, rather than the person doing the work.

That said, if I have to, then I will. :)

Kindly,
Thomas

**Comment by ThomasAdam** [comment]
This is odd.  I used the cocci file you supplied, and ran it over the entire code base.

```
spatch --sp-file contrib/coccinelle/remove_unnecessary_pointer_checks.cocci fvwm/*.c
```

Which doesn't modify any files under that directory.

What am I missing? Does the cocci file need updating?

**Comment by elfring** [comment]
>Does the cocci file need updating?

I constructed enhanced SmPL script variants (for example) a while ago.

**Comment by ThomasAdam** [comment]
> >Does the cocci file need updating?
> 
> 
> 
> I constructed enhanced SmPL script variants (for example) a while ago.

Did I miss that? Could you maybe let me know what changes I'd need to make to the .cocci file in that case?

**Comment by elfring** [comment]
:crystal_ball: This issue depends also on growing development interests.

How do you think about to extend your knowledge according to possible applications of the semantic patch language? :thinking:

Another script example:
```cocci
@Remove_unnecessary_pointer_checks1@
expression x;
@@
(
-if (\(x != 0 \| x != NULL\))
    free(x);
|
-if (\(x != 0 \| x != NULL\)) {
    free(x);
    x = \(0 \| NULL\);
-}
)

@Remove_unnecessary_pointer_checks2@
expression a, b;
@@
(
-if (\(a != 0 \| a != NULL\) && \(b != 0 \| b != NULL\))
+if (a)
    free(b);
|
-if (\(a != 0 \| a != NULL\) && \(b != 0 \| b != NULL\)) {
+if (a) {
    free(b);
    b = \(0 \| NULL\);
 }
|
-if (\(a != 0 \| a != NULL\) && \(b == 0 \| b == NULL\))
+if (!b)
    free(a);
|
-if (\(a != 0 \| a != NULL\) && \(b == 0 \| b == NULL\)) {
+if (!b) {
    free(a);
    a = \(0 \| NULL\);
 }
)
```

**Comment by ThomasAdam** [comment]
Hi @elfring 

Thank you.  I have no time (or desire) to learn anything more about SmPL than I already do.

These sorts of exercises are one-time only and a means to an end -- so when I do tend to need spatch, I know I've got people like yourself to lend a hand.

All I wanted out of this was an updated .cocci file, which you've provided, and I shall now commit.

Thanks.

**Comment by elfring** [comment]
:crystal_ball: I hope that further developers can benefit any more from improved data processing also with help of the semantic patch language.
