### ISSUE TITLE
FvwmRearrange Place windows wrong from git master but  release 1.1.0 is fine.

### ISSUE THREAD

**Issue by heelsleeh** [fvwmorg/fvwm3#1102]
Thanks for reporting your bug here!  The following template will help with
giving as much information as possible so that it's easier to diagnose and
fix.

## Upfront Information

Please provide the following information by running the command and providing
the output.

* Fvwm3 version (run: `fvwm3 --version`)
git master
* Linux distribution or BSD name/version
Rockylinux 9
* Platform (run: `uname -sp`)
Linux x86_64
## Expected Behaviour

What were you trying to do?  Please explain the problem.
When two windows are tiled, the two windows overlap and there is a blank area on the right side of the screen instead of filling the entire right space.The blank area on the right seems to be the same size as the space left by the iconbox on my left，see the pic below
![bug](https://github.com/user-attachments/assets/04c02539-59de-4d4a-97ff-c3d94f9fad04)

## Actual Behaviour

What should have happened, but didn't?

## Enabling logging

`fvwm3` has a means of logging what it's doing.  Enabling this when
reproducing the issue might help.  To do this, either change the means fvwm3
is started by adding `-v` as in:

```
fvwm3 -v
```

or, once `fvwm3` has loaded, send `SIGUSR2` as in:

```
pkill -USR2 fvwm3
```

The resulting logfile can be found in `$HOME/.fvwm/fvwm3-output.log`

## Steps to Reproduce
`FvwmRearrange -tile -animate -mn 2 -m -u -s -r -t 0 0 1800p 1080p`
How can the problem be reproduced?  For this, the following is helpful:

* Reduce the problem to the smallest `fvwm` configuration example (where
  possible).  Start with a blank config file (`fvwm3 -f/dev/null`) and go from
  there.

* Does the problem also happen with Fvwm2?

Include your configuration with this issue.

## Does Fvwm3 crash?

If fvwm3 crashes then check your system for a corefile.  This is platform
dependant, however, check if:

  - corefiles are enabled (`ulimit -c`)
  - A corefile might be in `$HOME` or `/tmp/`.
  - If you're using Linux (with `systemd`), check `coredumpctl list`.
    `coredumpctl` may need installing separately.

If you find a corefile, install `gdb` and run:

```
gdb /path/to/fvwm3 /path/to/corefile
```

If you're using `coredumpctl` then use:

```
coredumpctl debug
```

Then from within the `(gdb) ` prompt, issue:

```
bt full
```

... and include the output here.

## Extra Information

* Anything else we should know?

* Feel free to take a screen capture or video and upload to this issue if you
  feel it would help.

* Attach `$HOME/.fvwm/fvwm3-output.log` from the step above.

**Comment by somiaj** [comment]
Please check #1081, this is a known issue until that is merged.

**Comment by somiaj** [comment]
Note, The options for FvwmRearrange have been modified a bit, you will have to check the manual pages for the changes.

**Comment by heelsleeh** [comment]
> Note, The options for FvwmRearrange have been modified a bit, you will have to check the manual pages for the changes.

Thanks for your reply, looking forward to the update.

**Comment by somiaj** [comment]
Please give that PR a test, and let me know of any issues or thoughts you have with using it.
