### ISSUE TITLE
FvwmPager: WindowFore black seems to be broken

### ISSUE THREAD

**Issue by harridu** [fvwmorg/fvwm3#1105]
* Fvwm3 version (run: `fvwm3 --version`)
fvwm3 1.1.1 (released)
with support for:  ReadLine, XPM, PNG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS
commit f789db3004428868ebbc8db1e2b99effc95d85c2

* Linux distribution or BSD name/version
Debian Sid
Linux cecil.afaics.de 6.11.7-raw SMP PREEMPT_DYNAMIC Fri Nov  8 19:02:08 CET 2024 x86_64 GNU/Linux

## Actual Behaviour

Moving from version 1.1.0 to the top of the main branch (commit f789db3004428868ebbc8db1e2b99effc95d85c2) the WindowFore option for FvwmPager appears to be broken. 1.1.0:

![snapshot hfR7cm](https://github.com/user-attachments/assets/c5712db4-f7ec-4a43-8a16-83410b1fcdc5)

commit f789db3004428868ebbc8db1e2b99effc95d85c2:

![snapshot 9Sr3Qz](https://github.com/user-attachments/assets/a69b2165-7f7f-407f-a6ce-1c88039d51fa)

Please note the white frames, even though my FvwmPager config doesn't mention white at all:
```
Style   "FvwmPager"             NoTitle, BorderWidth 0, HandleWidth 0, WindowListSkip, Sticky, StaysOnBottom

*FvwmPager: Fore black
*FvwmPager: Back black
*FvwmPager: HiFore black
*FvwmPager: HiBack gray10
#*FvwmPagerWindowColors black #404040 black #c06000
*FvwmPager: WindowBack #404040
*FvwmPager: WindowFore #000000
*FvwmPager: FocusBack #c06000
*FvwmPager: FocusFore black
```
If I set WindowFore to #010101, then the new fvwm3 works as 1.1.0.

I understand that I should use colorsets. This is WIP. However, this should not affect WindowFore.

**Comment by somiaj** [comment]
I am unable to reproduce this using the config you provided, though I do notice an issue with `FocusFore`, which I think is related. I think the issue is I test if the fg pixel exists, otherwise fall back to the provided pixel of the window, and if the color is black, the pixel is actually `0`, failing the test. Give me a moment.

**Comment by harridu** [comment]
Yup, problem seems to be gone with commit e1f12ad.

Thank you very much
