### ISSUE TITLE
FvwmRearrange -tile -r -mn 3 -maximize 0 0

### ISSUE THREAD

**Issue by rasatpc** [fvwmorg/fvwm3#1107]
* Fvwm3 version (run: `fvwm3 --version`)
fvwm3 1.1.1 (1.1.0-120-g3e0d960d)

## Behaviour
Tile windows into columns and rows.
`FvwmRearrange -tile -r -mn 3 -maximize 0 0 86 82`

Does not work when numbers are added to maximize. Without numbers, it places all windows into columns without rows.
`FvwmRearrange -tile -r -mn 3 -maximize`

**Comment by somiaj** [comment]
`FvwmRearrnage -tile -reverse -max_n 3 -maximize 0 0 86 82` works just fine for me. Though you may want to check out the new features.

**Comment by somiaj** [comment]
The issue is `-mn` is no longer an option, so the number in `-mn 3` is read as part of the bounding box, so the bounding box is then used to be `3 0 0 86` which won't do anything. The bounding box logic has always been a bit fragile this way, this isn't new, what is new is the options have changed so the old options will cause odd issues.

**Comment by rasatpc** [comment]
>> FvwmRearrnage -tile -reverse -max_n 3 -maximize 0 0 86 82

Testing with default config, doesn't work. Manpage examples, only `FvwmRearrange -cascade 10 2 80 70` works. Additional options with `-tile` don't work.

**Comment by ThomasAdam** [comment]
@rasatpc 

Are you saying there's something in the default config which references `FvwmRearrange` which doesn't work (i.e, a configuration problem), or something else?

Again, you need to take into account the changes made to `FvwmRearrange` as breaking.

**Comment by rasatpc** [comment]
The default config is fine. I am testing the different FvwmRearrange examples in the manpage.

**Comment by ThomasAdam** [comment]
OK.  When you actually have something which might be an issue, let us know.  Until then, please try and not muddy the waters.

**Comment by rasatpc** [comment]
The issue is that option `-tile` does not work. Option `-cascade` is ok.

**Comment by ThomasAdam** [comment]
But it has always been that way, @rasatpc -- that's not anything new.  They're mutually-exclusive.

**Comment by rasatpc** [comment]
It worked fine until recent update. I have been using option `-tile` for a long time.

**Comment by somiaj** [comment]
The wiki has not been updated, use the man page. What do you mean the option '-tile' does not work, in my tests it does what it is designed to do.

**Comment by rasatpc** [comment]
> What do you mean the option '-tile' does not work

I tried many options mentioned in the FvwmRearrange manpage. Some work, others not. Here is the list:

```
FvwmRearrange -tile -swap 10 10 90 90 (ok)
----
FvwmRearrange -tile -swap 0 0 35 100
FvwmRearrange 35 0 100 10
(ok)
-----
FvwmRearrnage -tile -swap -max_n 3 0 0 86 82 (no)
FvwmRearrnage -tile -max_n 3 0 0 86 82 (no)
FvwmRearrnage -auto_tile (no)
FvwmRearrnage -tile -reverse -max_n 3 0 0 86 82 (no)
```
Option `-maximize` is not mentioned in the manpage. I did a test and got my code to work with minor edits. 
`FvwmRearrange -tile -reverse -max_n 3 -maximize 0 0 86 82` (ok)

**Comment by somiaj** [comment]
You have not clarified what doesn't work is doing. Also you should search the manual page better, `-maximize` is in the manual page.

Of course `FvwmRearrnage -tile -swap -max_n 3 0 0 86 82` doesn't work, but if you spell `FvwmRearrange` correctly it does work.

**Comment by rasatpc** [comment]
>> somiaj: `FvwmRearrnage -tile -reverse -max_n 3 -maximize 0 0 86 82` works just fine for me

I copied your spelling error. :) Everything works fine. Also, I found the option `-maximize`.

**Comment by somiaj** [comment]
Ahh sorry, silly me.
