### ISSUE TITLE
Add a dmenu/rofi keybinding for default config

### ISSUE THREAD

**Issue by lgsobalvarro** [fvwmorg/fvwm3#112]
In a similar way as standalonetray has being implemented into the default config file, it could be a nice touch if there was also a keybinding to call dmenu and/or rofi. Eg:

`Key Space A M Exec exec dmenu_run`

Or perhaps a menu option in a similar fashion as wmaker's "run command" window works. However I think this method could be considered a bit silly.

**Comment by ThomasAdam** [comment]
Hi @lgsobalvarro,

Thanks -- if you want to open a PR with a patch, that'd be good.

Kindly,
Thomas
