### ISSUE TITLE
fvwm3 and Galaxy Organizer

### ISSUE THREAD

**Issue by galaxysite** [fvwmorg/fvwm3#1130]
## Upfront Information

* Fvwm3 version (run: `fvwm3 --version`)

fvwm3 1.1.2 (1.1.1-2-gefef84cf)

* Linux distribution or BSD name/version

uname -a
Linux my 6.12.1 #2 SMP PREEMPT_RT Sat Nov 23 11:28:06 MSK 2024 x86_64 GNU/Linux

Debian Sid

* Platform (run: `uname -sp`)

Linux unknown

## Expected Behaviour

I make fvwm3 from git sources and run it.

1. My gorg64 https://github.com/galaxysite/gorg64 do not start automatically.
2. Stay-on-top property don't  work.
3. Frameless don't work. Border showed.

## Steps to Reproduce

![Снимок экрана в 2024-12-02 09-24-43](https://github.com/user-attachments/assets/77e9a1fb-f8d4-40e9-92f6-ddd4a6f8ce54)

**Comment by galaxysite** [comment]
Thanks for the answer!

What command should I add to my post-installation script so that gorg64 runs from fvwm? I'm afraid to mess it up - there's a lot described there.

About always on top. This is more of a bug, although it can probably be fixed by adding a special configuration.
But then how can I do this from the same script?

These aren't individual settings, but common settings for everyone.

**Comment by somiaj** [comment]
I think you are missing how fvwm works. It is up to fvwm users to configure things themselves. You could provide documentation for what they need to do, but the user will have to add that info into their own configuration file if they want it.

**Comment by galaxysite** [comment]
Could you then write not a script, but a compact instruction for the Galaxy Organizer and similar programs with a clock in the foreground, autostart and scheduler for your users? Perhaps from your own experience of launching it. This is a special type of program, and it may be difficult for users to take into account all the nuances of this. It is difficult to guess what settings to make in this case. The user, for example, can launch the installed program and see the clock. In a sense, this may please him, but he may not assume that for normal work he needs autostart (full-time runned automatical system), and the clock panel was supposed to be on top of all windows and always visible. I do not have such a lot of experience using fvwm to write such an instruction for it, but I can only warn users about the additional complexity in this wm.

But I understood the situation with these questions. Thanks anyway!

**Comment by somiaj** [comment]
I personally would not run a program that wants to override the window manager and decide if it should have decors and where it should be placed. That is the job of the window manager. There is a reason `gtk3-nocsd` exists, as some users don't want applications to make decisions that the window manager should be making. Users of fvwm often want to control things in their own way, and everything you are trying to do can be done via fvwm if the user wants to. Fvwm can make it so one window always stays on the top of others, decide where to place a window, and decide if or if not to include borders and/or title bars.

Yes, fvwm is complex and is not a window manager for everyone, it requires the user take time to learn how to write their own configuration, so warning them it is complex is just fine, it is. You can send users who need help configuring fvwm to the forums, https://fvwmforums.org/, and we can help them style the window so it has no decor or stays on top.

In my experience it is often the other way around, fvwm users are constantly trying to work around applications that want to override the window manager's decisions by removing their decor, try to stay on top, or control their position. So if you want to make your application work better for fvwm users, have a way to turn off all the overrides you are using, and let the window manager do its job and manage the window.

The biggest thing for fvwm is to have a well defined class/resource for the applications window that we can match against to be able to style it using the hundreds of fvwm available Styles.
