### ISSUE TITLE
Large Virtual Desktops Leak Windows

### ISSUE THREAD

**Issue by Zackrobat** [fvwmorg/fvwm3#1134]
I'm using the current Debian testing package version:
fvwm3 1.1.0

However, this issue has existed for at least 15 years in fvwm2. I upgraded to fvwm3 specifically to report this bug if I saw it here too, and I did.

uname -sp
Linux unknown

## Expected Behaviour

When using a DeskTopSize greater than 6x6 I expect each grid element to be available for my windowing applications. So when navigating to a grid element that has firefox, I would not expect to see a window that I opened in some other grid element. Each grid element of the desktop should be an isolated environment containing only the windows I've placed in that grid element.

To be clear: I'm trying to use the desktop normally. I use ctrl-alt-arrow keys to navigate to various viewports, where I have placed the windows I'm using in a given session. The windows are not sized larger than the viewport or placed to overlap viewports. Nothing fancy, nothing weird. Just an xterm in one viewport, google chrome in another viewport, etc

## Actual Behaviour

When I create an xterm or other window in the leftmost viewport, and then navigate rightward with ctrl-alt-right arrow, I will eventually see that same xterm (or other window) again. Not necessarily all the way to the right, but far to the right. In that rightward viewport the xterm will be offest, i.e. if I had it full-screen in the leftward viewport, it will now be shifted a bit to the right of the rightward viewport.

If I then, in the rightward viewport, create a new window, and then use ctrl-alt-left arrow to navigate back to the original viewport, I will also see the new window in that leftward viewport.

I.e. the two viewports show the same windows, although offset.

## Steps to Reproduce

Create a 20x20 Desktopsize.

Create a window in the upper left viewport.

Navigate to the right, viewport by viewport. Eventually you will see that same window offset.

* Does the problem also happen with Fvwm2?

Yes. I've seen this same bug without fail for 15 years or more.

## Does Fvwm3 crash?

No crash. Just the same windows appearing in multiple viewports.

## Extra Information

![2024-12-05_15-33](https://github.com/user-attachments/assets/8626d806-3601-46bd-b249-ed7e54f1e716)
![2024-12-05_15-34](https://github.com/user-attachments/assets/6a31b5af-7945-4213-a7f0-02b183ba2602)

**Comment by ThomasAdam** [comment]
Yes -- the virtual screen size is fixed with X11.  Virtual desks are making use of that overall size, so with a sufficiently large setup, this is bound to happen.
