### ISSUE TITLE
FvwmPager: The SolidSeparators option doesn't affect the first desk shown or multiple desks

### ISSUE THREAD

**Issue by vanillechose** [fvwmorg/fvwm3#1138]
## Upfront Information

* Fvwm3 version (run: `fvwm3 --version`):  `fvwm3 1.1.2 (1.1.1-3-g27fd3cae)` (latest commit of the main branch)

* Linux distribution or BSD name/version: Void Linux

* Platform (run: `uname -sp`): Linux unknown

## Expected Behaviour

The SolidSeparators configuration option of FvwmPager should work regardless of which desktop the pager is showing.

## Actual Behaviour

When SolidPager is set, the first desk displayed by FvwmPager (after start or a restart of fvwm) is drawn with dashed instead of solid lines. When switching between desks, all the other desks are drawn with solid separators.

## Enabling logging

The log file doesn't show anything related to the pager

## Steps to Reproduce

I noticed this bug after updating to 1.1.0, and I was able to reproduce it using the latest commit of the main branch with the following configuration file

```
DesktopSize 4x4

Mouse 4 R A GotoDesk +1 0 1
Mouse 5 R A GotoDesk +1 0 1

# show the pager on every desk
Style "Desk*" Sticky

DestroyModuleConfig FvwmPager
*FvwmPager: SolidSeparators

AddToFunc StartFunction
+ I Module FvwmPager *
```

## Extra Information

- I took a video of the bug in case my description wasn't clear enough https://github.com/user-attachments/assets/0ead5482-7a31-40a4-9b9c-380264351410

- The NoSeparators option still works properly.

**Comment by somiaj** [comment]
In my initial testing seems to be worse than that. If you are showing multiple desks at the same time, `SolidSeparators` has no effect.

**Comment by vanillechose** [comment]
> @vanillechose I believe #1139 should fix the issue (does in my testing). If you can let us know if it works for you, that would be great.

It works for me :) thank you very much.
