### ISSUE TITLE
Icons and its decorations (e.g. borders) sometimes disappear (e.g. on Fvwm Restart always) with new Xlib version

### ISSUE THREAD

**Issue by 111LUX** [fvwmorg/fvwm3#1143]
This is duplicate of https://github.com/fvwmorg/fvwm3/issues/818 as, for for some reason, bug was locked for further replies, while the issue is still persisting. **What is worse, siebenmann's patch https://github.com/fvwmorg/fvwm3/issues/818#issuecomment-1401144381 is no longer working with 1.1.1 version**, as _libs/FEvent.c_ code was changed. 

Maybe, as a workaround, someone may help to adopt siebenmann's patch to work with this new 1.1.1 version and post it here? As, unfortunately, I'm not familiar with that code on that level. Must have working icons, as my config [111LUX/FVWM](https://github.com/111LUX/FVWM) is not usable without it.

Why this is happening (almost 2 years by this moment)? Because it's hard to fix, or because such essential feature as icons is no longer considered as a "mainstream" for some reason, why? Because you don't use it? 

**Ways to reproduce:** install every not old distro, e.g. Debian stable, install FVWM (2 or 3 version), use icons with it and watch how icons of iconified apps disappear on Fvwm Restart and sometimes randomly.

![Dec-17-Tue-14:57:03](https://github.com/user-attachments/assets/63fc4a4c-358f-43c1-a6e2-0a5c70e9864a)

**Comment by ThomasAdam** [comment]
Thanks, but as you note, it's a duplicate.

**Comment by 111LUX** [comment]
> Thanks, but as you note, it's a duplicate.

Will this be fixed, or just "skipped"? Why no actions are made in this way, some difficulties with implementation? Or just no interest?

**Comment by 111LUX** [comment]
Hi, @siebenmann ! ;) Are you still using icons ?

**Comment by ThomasAdam** [comment]
> > Thanks, but as you note, it's a duplicate.
> 
> Will this be fixed, or just "skipped"? Why no actions are made in this way, some difficulties with implementation? Or just no interest?

Because...

1. I've yet to find an adequate solution to this.
2. I'm busy.
3. I prioritise other things.

I'll get round to it eventually.

**Comment by 111LUX** [comment]
Understood, thank you for your work 👍  Looking to the bright future 😊
