### ISSUE TITLE
FvwmPager sometimes doesn't correctly track window while dragging

### ISSUE THREAD

**Issue by ileGITimo** [fvwmorg/fvwm3#1149]
fvwm3 1.1.2 (80e6017)
Dual 1920x1080 screens, side by side, making up a 3840x1080 fvwm root.
Separate pagers on left and right monitors
DeskTopSize 12x1

While dragging left a window from the left screen, page N to page N-1, as soon as the left side of the window protrudes through the left edge of the screen, the icon on the pager jumps from page N to N+1, i.e. right, opposite direction/page, then, as soon as the mouse sprite moves through the left edge of the screen, the icon jumps from page N+1 to N-1,the correct destination page.

End window position in the pager is fine.

See attached video.

https://github.com/user-attachments/assets/c53d86f3-b7c6-4845-b750-f04930c8a6d0

**Comment by somiaj** [comment]
What DesktopConfiguration do you use? Is that a double monitor setup?

**Comment by ileGITimo** [comment]
Dual 1920x1080 screens, left and right, separate pagers on left and right monitors, per-monitor DesktopConfiguration

**Comment by somiaj** [comment]
This is just a side affect of how fvwm places windows relative to the location of the current monitor, the fact your pager is showing a single monitor and are located on different pages. I am aware of this and other issues that the pager won't be 100% accurate during interactive moves, and it requires the window to be placed for fvwm to update its relative location and the pager to show its real position.
