### ISSUE TITLE
multiple definition error when using gcc 10

### ISSUE THREAD

**Issue by lunarlabs** [fvwmorg/fvwm3#119]
I'm trying to make this file on an Arch Linux installation, and when I get to the make stage, I get the "ld: multiple definition" error that appears to be a new "feature" of GCC 10 as detailed here: https://gcc.gnu.org/gcc-10/porting_to.html

**Comment by ThomasAdam** [comment]
Hi @lunarlabs,

Thanks for the report.  Can you please paste the output from GCC, including the errors you're getting?

Thanks,
Thomas

**Comment by ThomasAdam** [comment]
OK.  GCC trying to be helpful and failing,

I'm not fixing this properly, but for now, I will disable `fcommon`.

Thanks for the report.
