### ISSUE TITLE
No .desktop file generated from make install

### ISSUE THREAD

**Issue by sweptr** [fvwmorg/fvwm3#12]
Did `./configure`  `make` `sudo make install`
logged out to lightdm. No new fvwm3 session.
`ls -la /usr/local/xessions` gives  no fvwm3.desktop. Copied and renamed fvwm2.desktop to fvwm3.desktop. Edited some of the contents in that file.
Did sudo killall Xorg to force reload of lightdm. Problem solved.

`uname -a
Linux macbookserver 5.0.0-38-generic #41-Ubuntu SMP Tue Dec 3 00:27:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

`lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco`

**Comment by ThomasAdam** [comment]
Thanks -- I looked in to this, and it seems Debian generate this file; presumably other OSes do as well.  It's currently not part of FVWM3 -- I'd happily accept a patch to add/install such a file, assuming it followed the Freedesktop guidelines.
