### ISSUE TITLE
FvwmScript: incorrect painting of dipsticks at low values

### ISSUE THREAD

**Issue by afhp-2020** [fvwmorg/fvwm3#125]
A quite minor one :)

With the test case enclosed, basic dipsticks with a value range of 0-100 and some way to change their value,
* from 6-100 everything displays correctly
* with value 5, the dipstick is not filled with the foreground color (but some relief is shown in the dipsticks at the right length)
* values 2-4, the horizontal dipstick is filled at 100%
* values 0-1 display correctly

[diptest.script.txt](https://github.com/fvwmorg/fvwm3/files/4735071/diptest.script.txt)

**Comment by ThomasAdam** [comment]
Hi @afhp-2020,

I'm not prioritising this until after 1.0 -- but all I can say is that this will also be happening on `fvwm2` and hence isn't a regression.

This is more for my benefit than anything else.

**Comment by afhp-2020** [comment]
No problem and no rush. It's not breaking anything :)
