### ISSUE TITLE
Logs of starting - closing fvwm3 with DesktopConfiguration set

### ISSUE THREAD

**Issue by MasterP-theGu** [fvwmorg/fvwm3#14]
[fvwm3_default-config_per-monitor.log](https://github.com/fvwmorg/fvwm3/files/4050897/fvwm3_default-config_per-monitor.log)
[fvwm3_default-config_unchanged.log](https://github.com/fvwmorg/fvwm3/files/4050898/fvwm3_default-config_unchanged.log)

In both cases, fvwm3 starts nicely and I haven't run into problems yet. But the RightPanel does not start. During startup, I can see in the top left corner components popping up (Pager, stalonetray, etc?), but there is no Panel at all, and after popping up, they are gone. No trace.

**Comment by ThomasAdam** [comment]
Which part isn't loading?  For me, the right panel loads...

![show](https://user-images.githubusercontent.com/101281/72223262-bd784900-3564-11ea-9e44-07f17608fac3.png)

**Comment by ThomasAdam** [comment]
Thanks.  This looks to be a problem in `libs/FScreen.c:FScreenParseGeometry()` -- I'll investigate and will let you know when I've got a patch.

**Comment by ThomasAdam** [comment]
This seems fixed; and FvwmButtons positioning is being tracked via #28 -- so I'm closing this.
