### ISSUE TITLE
FvwmPager sometimes ignores styles

### ISSUE THREAD

**Issue by lgsobalvarro** [fvwmorg/fvwm3#142]
Using the default config I have notice sometimes FVWM3 ignores styles for Pager.

![Screenshot_20200626_102948](https://user-images.githubusercontent.com/1160397/85876026-b94e8980-b79a-11ea-8401-9b980fe1e98c.png)
I did change my wallpaper from Florar to Space. After log out and then login, the Pager ignored all styles as can be seen in the screenshot. A restart fixed this issue but it reset the background back to floral.

If you set again the wallpaper to Space and restart, the Pager styles will be ignored again. This makes me think it could somehow related to .BGdefault or the Function SetBG

**Comment by ThomasAdam** [comment]
@lgsobalvarro -- when did you first notice this happening?  Does the same thing happen on FVWM2?

**Comment by lgsobalvarro** [comment]
I notice this yesterday. And no, it doesn't seem to happen on FVWM2. I haven't being able to reproduce this with restart as I can on FVWM3

**Comment by ThomasAdam** [comment]
Hi @lgsobalvarro,

I'm guessing this is still a problem?  Would you be able to give some details about how I might be able to reproduce it?  I tried in your original message, but for me `FvwmPager` always receives its styles.

**Comment by lgsobalvarro** [comment]
I was unable to reproduce this on 1.0.1.

Closing this issue then.
