### ISSUE TITLE
Properties of windows are lost after a restart

### ISSUE THREAD

**Issue by okraits** [fvwmorg/fvwm3#143]
When the Restart command is executed, properties of windows are lost after the restart:

* the maximized state is lost
* windows are moved to a previous position
* it even occured that windows are iconified after the restart

Running fvwm3 8ba1ac7009f45d16a08ec1eedb9cdd61615fb789.

**Comment by ThomasAdam** [comment]
Hi @okraits,

Is this issue happening regardless of the number of monitors you're using?  That is to say, does it happen with just one monitor, or more than one?

Thanks,
Thomas

**Comment by okraits** [comment]
Hi Thomas,

it happens on my laptop with one display as well as on my desktop with two displays.

Oliver

**Comment by okraits** [comment]
@ThomasAdam I still have an issue of this kind with current master branch.

I just restarted fvwm3 a couple of times and did some tests. It seems to boil down to one thing:

After a restart of fvwm3 (through the menu entry), some windows change their state from being not maximized to being horizontally maximized. This happens to all windows which have been maximized (both horizontally and vertically or only vertically) at least once before.

**Comment by ThomasAdam** [comment]
Hi @okraits,

Thanks for the information.  I can't reproduce this, and the information I asked for doesn't show a problem either.  That's not to say that this issue doesn't exist -- I can believe that it does -- I suspect it's a race-condition somewhere which isn't detailed in the state file you're providing.

Are you still seeing exactly the same problem?  Does it happen every time you restart or only sometimes?

**Comment by codedmart** [comment]
```
# This file is generated by fvwm. It stores global and window states.
# Normally, you must never delete this file, it will be auto-deleted.

[FVWM_VERSION] 1.0.1
[CLIENT] 1600001
  [RES_NAME] RightPanel
  [RES_CLASS] FvwmButtons
  [WM_NAME] RightPanel
  [GEOMETRY] 0 0 3840 36 0 0 0 0 0 0 0 0 1 0 0
  [MONITOR] 85
  [DESK] 0
  [LAYER] 6 6
  [PLACED_BY_BUTTON] 0
  [EWMH_DESKTOP] 0
  [FLAGS] 0b 00 00 00 00 00 00 00 00 40 5b 02 00 10 0a 01 01 00 00 00 01 00 00 00 00 00 00 00 c4 01 80 19 02 00 00 00 08 00 04 10 01 30 48 00 aa aa 0a 00
[CLIENT] a00002
  [RES_NAME] Alacritty
  [RES_CLASS] Alacritty
  [WM_NAME] codedmart@genhome:~
  [GEOMETRY] 613 309 2580 1553 0 327 3 1695 -3 0 0 0 1 438 0
  [MONITOR] 85
  [DESK] 0
  [LAYER] 4 4
  [PLACED_BY_BUTTON] 1
  [EWMH_DESKTOP] 0
  [FLAGS] 00 00 00 00 00 00 00 00 00 40 4b 02 00 10 0a 01 01 00 00 00 01 00 00 00 00 00 00 00 df 01 80 01 02 00 00 00 08 14 04 98 05 50 08 15 ca aa 0a 00
[GLOBAL]
  [MONITOR] 85
      [DESKTOP] 0
      [VIEWPORT] 0 0 69120 0
      [SCROLL] 0 0 450 0 0
  [MONITOR] 86
      [DESKTOP] 0
      [VIEWPORT] 0 0 69120 0
      [SCROLL] 0 0 450 0 0
  [MISC] 250 1 0
  [STYLE] 0 0
  [INFOSTORE]
    [KEY] runcmd
    [VALUE] rofi -show run
    [KEY] terminal
    [VALUE] xterm
```

**Comment by ThomasAdam** [comment]
This is even more apparent if you modify your fvwm config file, change `EwmhBaseStruts` and then restart.  Existing windows are then placed in very strange locations indeed!

**Comment by codedmart** [comment]
[fs-restart-fvwm2.txt](https://github.com/fvwmorg/fvwm3/files/5681146/fs-restart-fvwm2.txt)
[fs-restart-fvwm3.txt](https://github.com/fvwmorg/fvwm3/files/5681147/fs-restart-fvwm3.txt)
