### ISSUE TITLE
EdgeScroll not working properly when values change via FvwmConsole

### ISSUE THREAD

**Issue by lgsobalvarro** [fvwmorg/fvwm3#144]
When `DesktopConfiguration` is set to `global`, `EdgeScroll 0 0` and you change it on the fly via FvwmConsole to  `EdgeScroll 100 100` Scrolling to the right does not work. It does scroll fine up=>down, down=>up and right=>left, but left=>right is broken. However if I set `EdgeScroll 100 100` as default in my cfg and restart it does work fine.

If `EdgeScroll 100 100`  is the default and you switch with FvwmConsole to `EdgeScroll 0 0` and then back to `EdgeScroll 100 100` it works fine. 

This has been tested with the default cfg and with my custom with the same result.

**Comment by ThomasAdam** [comment]
Yes, this is the same as #82 -- it's already broken.

Thanks for the extra information though.
