### ISSUE TITLE
Feature Request: Enable using the 'c' unit with the "MinWindowSize" and "MaxWindowSize" styles

### ISSUE THREAD

**Issue by SolubleShoe** [fvwmorg/fvwm3#145]
Currently fvwm can resize windows using units defined by the client application. But for some reason those units can't be used when defining a minimum or maximum window size.

Quote from the man page:
>Resize [[frame] [directiondir] [warptoborderautomatic] [fixeddirection] [w]width[p|c|wa|da] [w]height[p|c]]
> Allows for resizing a window. If called from somewhere in a window or its border, then that window is resized. If called from the root window then the user is allowed to select the target window.
> 
> The operation can be aborted with Escape or by pressing any mouse button (except button 1 which confirms it). 
>
> If the optional arguments width and height are provided, then the window is resized so that its dimensions are width by height. The units of width and height are percent-of-screen, unless a letter 'p' is appended to one or both coordinates, in which case the location is specified in pixels. **With a 'c' suffix the unit defined by the client application (hence the c) is used.** With the suffix 'wa' the value is a percentage of the width or height size of the EWMH working area, and with the suffix 'da' it is a percentage of the width or height of the EWMH dynamic working area. So you can say
>`Resize 80c 24c` 
> to make a terminal window just big enough for 80x24 characters. 

What I would like is to be able to say:
`Style "termite" MinWindowSize 80c 24c`
But that is not currently supported, you can only use percentage of screen size or pixels. If i could use the 'c' suffix it would be really sweet, especially when _some_ shells freak out and flood the terminal with warning messages about "unreasonable" terminal sizes

**Comment by somiaj** [comment]
@SolubleShoe I have worked on a patch that adds this feature. Check out the js/gh-145 branch if you want to test it out.
