### ISSUE TITLE
FScreenGetScrRect function

### ISSUE THREAD

**Issue by klebertarcisio** [fvwmorg/fvwm3#163]
Hi everyone,

I would like to understand a little more about the FScreenGetScrRect function:

https://github.com/fvwmorg/fvwm3/blob/48dd50909b97170d517aa02c735cc86881564cb6/libs/FScreen.c#L636-L656

This function may not change the values of **x, y, w** and **h**. That way, I always have to pass **x, y, w** and **h** initialized, right? If I don't pass these initialized values, I can't guarantee that the function initialized them unless I check the function's return, but that return is **hardly used** in the code.

See this example:

https://github.com/fvwmorg/fvwm3/blob/48dd50909b97170d517aa02c735cc86881564cb6/fvwm/icons.c#L2041-L2058

**Is there any possibility that global_icon_box_ptr-> IconBox [0] will receive an uninitialized value?**

**Comment by ThomasAdam** [comment]
Hi @klebertarcisio,

Yes, there's a small risk, but that's not the point here, because:

* Most compilers will set the value to 0 if undeclared in this case;
* The context for these callers is such that it's very unlikely we're going to fail finding a screen to set the values in the first place.

**Comment by danespen** [comment]
Thomas Adam <notifications@github.com> writes:

> Hi @klebertarcisio,
>
> Yes, there's a small risk, but that's not the point here, because:

You're the expert, but as I remember, the built in default iconbox that covers the root
can't be removed.  Not sure what you are doing with multiple monitors
that can be turned on and off, but the basic idea of the iconboxes was
to have a grid to fall back to.

-- 
Dan Espen

**Comment by ThomasAdam** [comment]
Hi @danespen,

Yes -- that's still the case here; per screen iconboxes can be definedm and come and go depending on whether the monitor is attached or not.  The `PRIMARY` monitor is now always set regardless.

**Comment by klebertarcisio** [comment]
To contribute to this discussion, I will post a few more places that the **FScreenGetScrRect** function is used in a similar way.

**FScreen.c**
https://github.com/fvwmorg/fvwm3/blob/48dd50909b97170d517aa02c735cc86881564cb6/libs/FScreen.c#L661-L684

**FvwmIdent.c**
https://github.com/fvwmorg/fvwm3/blob/48dd50909b97170d517aa02c735cc86881564cb6/modules/FvwmIdent/FvwmIdent.c#L787-L813
