### ISSUE TITLE
fvwm-menu-desktop only produces half the xdg-menu

### ISSUE THREAD

**Issue by MasterP-theGu** [fvwmorg/fvwm3#177]
From roughly the penultimate (?) update of master branch on, my XDG-menu is broken. The script only produces up to Graphics, and from Internet onwards, the items remain empty. Here's the end of the output, beginning with the final working entry "Grafik":

```
DestroyMenu "Grafik"
AddToMenu "Grafik" "Grafik" Title
+ "E-book viewer%/home/peter/.fvwm/icons/24x24-calibre-viewer.png%" Exec exec ebook-viewer --detach 
+ "Flameshot%/home/peter/.fvwm/icons/24x24-flameshot.png%" Exec exec flameshot
+ "GNU Image Manipulation Program%/usr/share/icons/hicolor/24x24/apps/gimp.png%" Exec exec gimp-2.10 
+ "LRF viewer%/home/peter/.fvwm/icons/24x24-calibre-viewer.png%" Exec exec lrfviewer 
+ "LibreOffice Draw%/usr/share/icons/hicolor/24x24/apps/libreoffice-draw.png%" Exec exec libreoffice --draw 
%s icon or default icon not found!
+ "XDvi" Exec exec xdvi 
Traceback (most recent call last):
  File "/usr/local/bin/fvwm-menu-desktop", line 877, in <module>
    main()
  File "/usr/local/bin/fvwm-menu-desktop", line 461, in main
    parsemenus(menulist, desktop, desktop_entries)
  File "/usr/local/bin/fvwm-menu-desktop", line 717, in parsemenus
    parsemenu(xdg.Menu.parse(menulist[0]), top, '', desktop_entries)
  File "/usr/local/bin/fvwm-menu-desktop", line 822, in parsemenu
    parsemenu(entry, '', '', desktop_entries)
  File "/usr/local/bin/fvwm-menu-desktop", line 801, in parsemenu
    printmenu(desktop.getName(), desktop.getIcon(), "Exec exec " + execProgram)
  File "/usr/local/bin/fvwm-menu-desktop", line 706, in printmenu
    iconfile = geticonfile(icon) or getdefaulticonfile(command) or icon
  File "/usr/local/bin/fvwm-menu-desktop", line 693, in geticonfile
    if st.check_size():
  File "/usr/local/bin/fvwm-menu-desktop", line 129, in check_size
    return self._do_check()
  File "/usr/local/bin/fvwm-menu-desktop", line 160, in _do_check
    with PIL.Image.open(self.filename) as f:
  File "/usr/lib/python3.8/site-packages/PIL/Image.py", line 2920, in open
    im = _open_core(fp, filename, prefix)
  File "/usr/lib/python3.8/site-packages/PIL/Image.py", line 2902, in _open_core
    im = factory(fp, filename)
  File "/usr/lib/python3.8/site-packages/PIL/ImageFile.py", line 117, in __init__
    self._open()
  File "/usr/lib/python3.8/site-packages/PIL/XpmImagePlugin.py", line 60, in _open
    raise ValueError("cannot read this XPM file")
ValueError: cannot read this XPM file
```

**Comment by ThomasAdam** [comment]
@mikeandmore -- can you take a look at this?  Presumably related to the work you've recently done?

**Comment by mikeandmore** [comment]
Sure.

It looks like PIL doens't support this particular xpm. Can you upload this xpm to github so that I can take a look?

I think I should catch the exception when this happens too...

**Comment by MasterP-theGu** [comment]
Thanks!
I could upload it if there was one. I guess it's xdvi that's causing the trouble as the libreoffice draw icon works fine.

My xdvi is part of texlive-bin, and these are the files that come with it:
```
texlive-bin /usr/bin/xdvi
texlive-bin /usr/bin/xdvi-xaw
texlive-bin /usr/bin/xdvipdfmx
texlive-bin /usr/share/applications/xdvi.desktop
texlive-bin /usr/share/man/man1/xdvi.1.gz
texlive-bin /usr/share/man/man1/xdvipdfmx.1.gz
```
xdvi.desktop looks like this:

```
[Desktop Entry]
Name=XDvi
GenericName=DVI Viewer
Exec=xdvi %f
Type=Application
Terminal=false
Categories=Graphics;Viewer;
Keywords=documents;
```

In my lunchbreak, I'll try to manipulate the .desktop file so that it includes an Icon and let you know if that works (but that wouldn't solve the original trouble, would it?). :D

**Comment by mikeandmore** [comment]
Do you happen to have a `XDvi.xpm` under `/usr/share/icons` or any of its sub-directories? 

I'm sure I can make this error disappear, but I just think it's better to display the icon if we can find one...

**Comment by MasterP-theGu** [comment]
Initially, no, the texlive-bin package that's installed doesn't provide an icon at all.
Apart from that, I haven't got any xpm icons in the path you're referring to, they're png, svg.
However, I `convert`ed xreader.png into xdvi.xpm to at least have an xdvi.xpm at hand.
Without modifying xdvi.desktop, nothing changes, so I'm not going to re-post the same error-output, hope that's ok.
Modyfying xdvi.desktop to include Icon=xdvi.xpm doesn't change anything, either.
To be on the safe side and to make sure my homemade xpm is alright, I attach it here (github doesn't allow uploading xpms, hence the gz)
[xdvi.xpm.gz](https://github.com/fvwmorg/fvwm3/files/5017109/xdvi.xpm.gz)

**Comment by mikeandmore** [comment]
I created #178, but it just ignores the broken file.

I suspect XDvi is actually fine, it's another xpm that's corrupted. This PR will at least print out which file is broken. Then we can see what does it take to display that xpm file.

**Comment by MasterP-theGu** [comment]
Hi, I am most awfully sorry, but nothing I can see has changed. The same error appears in the same place. :(

If it helps: I've now also tried to remove "xpm" from the fvwm-menu-desktop scriptfile, but to no avail.
Similarly, removing my old ~/fvwm/icons doesn't do the trick, either. I am still stuck somewhere between libreoffice Draw and Xdvi.

**Comment by mikeandmore** [comment]
Does the following patch work?

```
From 7fdc505884f59b6f53a59d497f604ecd83959432 Mon Sep 17 00:00:00 2001
From: Mike Qin <mikeandmore@gmail.com>
Date: Wed, 5 Aug 2020 17:29:54 -0400
Subject: [PATCH] catch when _do_check() fails

---
 bin/fvwm-menu-desktop.in | 8 ++++++--
 1 file changed, 6 insertions(+), 2 deletions(-)

diff --git a/bin/fvwm-menu-desktop.in b/bin/fvwm-menu-desktop.in
index e6763553..94afe442 100644
--- a/bin/fvwm-menu-desktop.in
+++ b/bin/fvwm-menu-desktop.in
@@ -125,8 +125,12 @@ class BaseIconScaleTool(object):
     def check_size(self):
         if self.filename.endswith('.svg'):
             return False
-        
-        return self._do_check()
+        try:
+            return self._do_check()
+        except:
+            # Always try to convert if check_size() fails.
+            # Worst case convert() would fail and ignore the icon.
+            return False
 
     def convert(self, theme_changed):
         # FVWM knows how to render SVGs
-- 
2.24.1

```

**Comment by mikeandmore** [comment]
@MasterP-theGu ping?

**Comment by MasterP-theGu** [comment]
@mikeandmore pong.
Sorry, I was very busy and more or less offline for a while, but things should become calmer now in my neck of the woods, so...
As soon as I'm on the machine in question, I'll try out the patch you posted and let you know. Thanks a lot for working on this, and apologies for having been shtum these past few days.

**Comment by MasterP-theGu** [comment]
It works perfectly! :D 
There are a couple of xpm's that fail converting:
```
> fvwm-menu-desktop | grep Fail
Fail to convert /usr/share/icons/hicolor/24x24/apps/xdvi.xpm.
Fail to convert /usr/share/pixmaps/xsane.xpm.
%s icon or default icon not found!
%s icon or default icon not found!
Fail to convert /usr/share/pixmaps/audacity.xpm.
Fail to convert /usr/share/pixmaps/gxkb.xpm.
Fail to convert /usr/share/icons/hicolor/24x24/apps/xdvi.xpm.
Fail to convert /usr/share/pixmaps/xsane.xpm.
Fail to convert /usr/share/pixmaps/audacity.xpm.
Fail to convert /usr/share/pixmaps/gxkb.xpm.
```
They're all original xpm's from /usr/share/pixmaps and the one I created using convert for one of my previous reports in this thread.
Other xpm's from /usr/share/pixmaps work fine and appear in the menu. I attach all the XPMs, maybe you find out what prevents some from working.
Cheers!

[MasterPsXPMs.zip](https://github.com/fvwmorg/fvwm3/files/5052283/MasterPsXPMs.zip)

**Comment by mikeandmore** [comment]
@MasterP-theGu these XPM files are weird. I can only open some of them with GraphicsMagick, and none with PIL/Pillow. I guess I'll just skip these.

**Comment by MasterP-theGu** [comment]
@mikeandmore I cannot judge the weirdness of XPM files. :D 
But I can add info. All of the original XPMs that I packed are included in the official arch packages for armv7h architecture, hence every Arch user will have the same weird files, at least on this architecture.
Strangely enough, I can open all of them with gm (1.3.35-2), but my pillows (7.2.0-1 as well as 6.2.1-1 w/python2) fail, too, even if I call them directly rather than from what you do in your script. 
Maybe this helps, maybe not, so please feel free to disregard.
