### ISSUE TITLE
Function to ignore screen boundaries in multi-monitor setups (when maximizing/full-screening)

### ISSUE THREAD

**Issue by wyatt8740** [fvwmorg/fvwm3#186]
This is a request, because I didn't see it in the man page; admittedly, I just searched through it using some common terms.

Basically, I'd like something whereby the entire display space can be treated as a single logical screen (for video walls, for instance). When maximizing a window, therefore, it would span across all monitors.

I was able to imitate this using the `Xinerama` command to turn off xinerama enhancements in FVWM2.

Things like `DesktopSize 1920x2400` (with two 1920x1200 panels vertically stacked) do not seem to have the effect I desire. Nor do things like `Maximize ewmhiwa` (although I understand why that second one doesn't work; I was just getting a little desperate).

I don't really want to have to have a separate version of fvwm3 compiled without RandR support and need to end my X session to switch between them.

**Comment by ThomasAdam** [comment]
Hi @wyatt8740,

You can wrangle `xrandr` to do this with version >=1.5.0 by specifying your own monitor size (which in you case would be the combined logical size of both your monitors).  Then you could make `fvwm` honor that screen however you liked.

The other approach is to write your own fvwm function which passes the parameters to `Maximize` to make such a window cover both monitors.

RandR is not an optional dependency in `fvwm3` and you'd have a hard time compiling a version without it.

**Comment by wyatt8740** [comment]
Ah, thanks, @ThomasAdam . If it's not optional, the man page (`doc/fvwm/fvwm3.1`) needs updating to address that.

> If Fvwm has been compiled wiith RandR support then it tracks the outputs (displays) which it finds.

**Comment by wyatt8740** [comment]
(I'll close this; I'm still not sure which xrandr option I need exactly, but there are just a few that are probable I think. My first guess is `--fb`.)

**Comment by ThomasAdam** [comment]
@wyatt8740,

If the man page is misleading, then please do submit a PR to address that...

**Comment by wyatt8740** [comment]
Will do; sorry. I was in a rush earlier.

**Comment by wyatt8740** [comment]
Will do; sorry. I was in a rush earlier.
