### ISSUE TITLE
SnapAttraction: consider both axis of adjacent window during move

### ISSUE THREAD

**Issue by kamgha** [fvwmorg/fvwm3#189]
This is probably rather a proposal to improve the behaviour of `SnapAttraction` than a bug:

The example uses `Style * SnapAttraction 40 SameType Screen` and I am referring to the behaviour of windows in my use case, icons could be affected in the same way as well.

I'd like to be able to position a window adjacent to another window, and having both snap it to the same y-position (or x-position, depending on which axis is in question). This is currently not possible, unless I temporarily position another window above the target and let the new window snap into the created corner.

Please have a look at the attached video: I'd like to position the right 'xterm' window adjacent to the left 'xterm', and on the same height/y-coordinate (starting at 7 seconds into the video). Similar to how I positioned the big 'xclock' to the 'login' window (at around 2 seconds into the video), which was possible due to the window/bar above it.

[fvwm-snapattraction.zip](https://github.com/fvwmorg/fvwm3/files/5119333/fvwm-snapattraction.zip)

**Comment by somiaj** [comment]
Would use SnapGrid work for your use case? (this way you can snap all windows to a grid to allow same x or y value?)

**Comment by kamgha** [comment]
No, `SnapGrid` creates a fixed grid on the whole screen. The desired snap is for an adjacent window at an arbitrary position, e. g. to match the top, the bottom, the left or the right edge into a line. Example: Two xterm windows, same dimensions, shall be put side-by-side. The current behaviour allows to snap them together, but not snap their top/bottom lines together to form a wider box.

Here is another idea: Perhaps a `SnapLine` (horizontal/vertical, screen, desk) instruction could be introduced as well, to create more flexible snap behaviours than `SnapGrid`, like seen in creative tools like Illustrator. However, this (like `SnapGrid`) would be for the whole screen, as opposed to a nearby window with `SnapAttraction`. The `SnapLine`s could be updated after each move of a window in the config. Is there an event like "OnSnap" and its counterpart for `SnapAttraction`? Then this would allow to create the proposed behaviour from the first post as well.

**Comment by somiaj** [comment]
But you could snap both of the xterms to the same grid line, giving them the same height. Just stating you can almost get your desired result if your desired result is to have them at the same height. Anyways, just a suggestion.

**Comment by kamgha** [comment]
The `SnapGrid` is fixed onto the whole screen, `SnapAttraction` snaps only on nearby windows, which themselves can be at an arbitrary position.

In general, this is a proposal to improve the behaviour of `SnapAttraction`. If the current behaviour is indeed intended, the other idea may allow for more flexible configurations.

**Comment by ThomasAdam** [comment]
I'm certainly not going to be adding yet another option.

The current behaviour was never intended to support your suggestion, @kamgha -- but it's one that should be fixed as such.  I just haven't given any thought about how to do this.  I suspect changing `SnapAttraction` is the correct thing to do.

**Comment by ThomasAdam** [comment]
I'm closing this for now.  Although there's nothing wrong with this idea, I think we have a good enough SnapAttraction, and I don't feel we need to support more niche modes of operation.  Things like this get complicated quite quickly.
