### ISSUE TITLE
Unable to build 1.0, bson.h not found [FreeBSD 12.1]

### ISSUE THREAD

**Issue by afhp-2020** [fvwmorg/fvwm3#200]
I saw the release of 1.0, so I cloned the repository into a new directory and started building.

The first run of `./autogen.sh` complained about libbson, so the package was installed. The second run completed without error. There is no error reported by `./configure` either.

`make` fails with:
```
 FvwmMFL.c:30:10: fatal error: 'bson/bson.h' file not found
 #include <bson/bson.h>
```
Build system is FreeBSD 12.1-RELEASE-p5 with all packages up-to-date as of 2020-09-03.

[configure.log](https://github.com/fvwmorg/fvwm3/files/5171697/configure.log)
[make.log](https://github.com/fvwmorg/fvwm3/files/5171699/make.log)

**Comment by ThomasAdam** [comment]
I wonder if this is `libbson/bson.h` versus just `bson.h`? Can you try making that change to FvwmMFL.c?

**Comment by afhp-2020** [comment]
Now that you pointed me in the right direction...

Replacing the include with `libbson/bson.h` also failed.

However, `pkg info -l libbson` yields
```
[...8<...]
/usr/local/include/libbson-1.0/bson.h
[...>8...]
```
So, replacing the include with `libbson-1.0/bson.h` seems to fix the issue. 

I suspect some special case will be needed in `configure` or an `ifdef` or something similar, so I'll re-test with a full build whenever ready.

Regards,
A.

**Comment by ThomasAdam** [comment]
Cool.  That's annoying as I tested an older version of FreeBSD.

Keep that patch for now, and let me know of any functional problems instead.

**Comment by ThomasAdam** [comment]
Hi @afhp-2020,

Please take a look at the linked PR, and let me know if this fixes your issue.

Thanks,
Thomas

**Comment by afhp-2020** [comment]
Hello Thomas,

Sorry for the delay.

I just pulled ta/gh-200 and it built without error.

Regards,
A.
