### ISSUE TITLE
"version of go" misinterpreted by configure script?

### ISSUE THREAD

**Issue by MasterP-theGu** [fvwmorg/fvwm3#202]
Hi,
sorry I haven't had a lot of time recently to keep my fvwm3 up to date and build all versions. I've just built
`Version:     1.0.0 (1.0.0-4-gbe72081a)`
with `--enable-golang `option to get fvwm3-prompt working from within the fvwm3 build itself rather than from building it on its own and manually adding it. I haven't had any problem with the new prompt, so my go install seems to suffice for it. the configure output, however, says:
`With Golang support?                no: version of go (go1.15.1 linux/arm) <= 1.4.x`
I find it strange as 1.15.1 looks to me as if it was > than 1.4.x, so either the message or the maths are confusing?
Installed go package is: 
```
Name                     : go
Version                  : 2:1.15.1-1
Beschreibung             : Core compiler tools for the Go programming language
Architektur              : armv7h
URL                      : https://golang.org/
```

**Comment by MasterP-theGu** [comment]
Hi @ThomasAdam ,

yes, all's fine now :D Cheers!

Best,
Peter

**Comment by ThomasAdam** [comment]
Thanks. Will merge.

**Comment by MasterP-theGu** [comment]
Hi @ThomasAdam ,

yes, all's fine now :D Cheers!

Best,
Peter
