### ISSUE TITLE
_NET_WM_STATE was not updated for maximized windows

### ISSUE THREAD

**Issue by xuzhen** [fvwmorg/fvwm3#203]
Steps to reproduce:
1. Bind Alt-M ```Key M A M Silent Maximize```
2. run ```xprop | grep _NET_WM_STATE``` to show the property of a non-maximized window. It should be empty
3. Press Alt-M to maximizing that window
4. run `xprop | grep _NET_WM_STATE` again. It is still empty.

After changing https://github.com/fvwmorg/fvwm3/blob/master/fvwm/ewmh_events.c#L737 and https://github.com/fvwmorg/fvwm3/blob/master/fvwm/ewmh_events.c#L812 from ```#if 0``` to ```#if 1```, the output in step 4 became ```_NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_HORIZ, _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_MAXIMIZED_VERT```

**Comment by ThomasAdam** [comment]
Hi @xuzhen,

Interesting. Please can you submit a PR?
