### ISSUE TITLE
fvwm3 man and default paths to config files?

### ISSUE THREAD

**Issue by dirteat** [fvwmorg/fvwm3#206]
Hi there,
I've just packaged fvwm3 on Mageia linux, because I love it and I am a 20 years-long user of fvwm2. So far, it just works fine with our distributed config. I've just spotted two things:

1) looks like there is no "man fvwm3" generated

2) I think some "recap" of the default paths and names of the config files searched by fvwm3 when it starts would be welcome, maybe in the missing man?
We used to have a plethora of options .fvwm/config .fvwm/.fvwm2rc etc... and some confusion exists as if these files should be renamed as .fvwm3 .fvwm3rc or not etc...

Cheers,
Chris.

**Comment by ThomasAdam** [comment]
Hi @dirteat 

To generate the man page, you'll need to use: `configure --enable-mandoc`.

As for config path changes, there aren't any yet.

**Comment by dirteat** [comment]
Perfect! Done and reading it, beautiful!

Thank you.
