### ISSUE TITLE
Man page `fvwm3.1` not built by default

### ISSUE THREAD

**Issue by djwf** [fvwmorg/fvwm3#246]
When making and installing fvwm3 from the git repository, using the following commands, the file `fvwm3.1` is not built or installed.

```sh
./autogen.sh
./configure
make
make install
```

This is unexpected given the first sentence of the second paragraph in `doc/README`: "By default, only the man page is generated."

If I add `--enable-mandoc` to the configure command, and run the commands below, then the `fvwm3.1` file is created.

```sh
./autogen.sh
./configure --enable-mandoc
make
make install
```

This behavior may be intentional, and I figured I'd check before submitting a PR to fix either the `README` *or* the `Makefile.am`.

So: is the behavior intentional?

**Comment by ThomasAdam** [comment]
Hi @djwf 

Hehe! Thanks for your eagie eyes! It's deliberate, and the README is wrong. Please submit a PR. Documentation is now opt-in.

Kindly,
Thomas

**Comment by djwf** [comment]
Got it - so should all the man pages be omitted by default? Or just the main page? I ask to figure out what should be in the PR.

**Comment by ThomasAdam** [comment]
Hi @djwf 

It's technically just the main fvwm3 page as that's what is built via the snake which is docbook.

I wouldn't draw a distinction though, I'd rather the PR just removed the assumption that manages are built for free.

**Comment by djwf** [comment]
Got it, PR will be inbound shortly!
