### ISSUE TITLE
[feature-request] Global desktop with predefined resolutions

### ISSUE THREAD

**Issue by suntong** [fvwmorg/fvwm3#248]
> - A desktop is attached to a screen. These are viewports into a monitor, of which there could be many. 
> - Desktops are separate from each attached screen, although it would be possible to have one "global" desktop which operated across all screens.

Is it possible to define global desktops with fixed resolutions? like 1920x1080, 1600x1024, 1440x900, 1368x768, 1280x720, 1024x768, etc

There are many reasons that such feature is desirable, for e.g.,

- When sharing screen during remote meetings, high resolution source screen device will result in tiny fonts on the receiving ends with lower resolutions, thus switching to a lower resolution will be a better option than zooming in on everything
- When using projectors, the laptop will normally have higher resolutions than the projectors allowed, although I've seen cases that the system can adapt to lower resolution device automatically, but when it fails, a manual picked lower resolution would be the best bet.
- When playing videos with low dimension, say 1024x768, or 960x540, or even 800x600, lowering the screen resolution will be a better option than scaling up the videos by software.

Please consider. thx.

**Comment by ThomasAdam** [comment]
Hi @suntong,

You might be able to wrangle `RandR` to do this, although this isnt' something Fvwm directly can help you with.
