### ISSUE TITLE
Maximize on second monitor gives wrong window size

### ISSUE THREAD

**Issue by phileimer** [fvwmorg/fvwm3#250]
I have 2 monitors: 
monitor 1: HDMI-2 connected primary 1920x1080+0+0
monitor 2: DVI-I-1 connected 1280x1024+1920+0

If I maximize a window on monitor 2, I get an oversized window: 1920x1080, instead of 1280x1024.

With the attached patch applied to 1.0.1, I get back the right behavior.
[fvwm3_maximize.txt](https://github.com/fvwmorg/fvwm3/files/5367225/fvwm3_maximize.txt)

**Comment by ThomasAdam** [comment]
Please raise a PR for this patch.

**Comment by ThomasAdam** [comment]
Fixed via 57050fb9b6eb1e5cf903a8f333409ba5caa38040
