### ISSUE TITLE
FvwmPager and FvwmIconMan do not update after GotoDesk

### ISSUE THREAD

**Issue by phintsan** [fvwmorg/fvwm3#262]
After upgrading to Fvwm3 1.0.1 from 1.0.0, FvwmPager and FvwmIconMan do not update after switching to other desk with GotoDesk. They keep displaying the old window configuration instead. Clicking on FvwmPager virtual desk resolves the issue.

The issue happens with the default configuration. For example:

- On Desk 0, open any window.
- Change to Desk 1 by clicking on FvwmPager desk indicator.
- Observe how Desk 0 window configuration stays on the Pager window.
- Click on the FvwmPager miniature desk window (eg. change to another page) and observe how window configuration is updated.

I bisected this fault to commit e557dd3d5f83caab349d52fe9afee8375514798e
By commenting out if-statement on virtual.c:1537 the problem is resolved.
The bug occurs only when DisplayConfiguration is global.

This may be related to #223.

**Comment by ThomasAdam** [comment]
Hi @phintsan 

Thanks for this report.  This change looks good to me.  Please can you make a pull-request, and I'll merge it.  I've just tested this when `DesktopConfiguration per-monitor` is set and couldn't see any side-effects.  I must have been thinking something odd when I wrote that.  ;)

This doesn't seem to be related to #223.

**Comment by phintsan** [comment]
Thanks for your prompt reply. 

I left the if-statement there to prevent self-assignment, even though in this case it would be harmless.
Feel free to edit the commit message as it is based on my hypothetical assessment of the root cause.
