### ISSUE TITLE
FvwmButtons Geometry - @g tag positions objects on active monitor instead of globally 

### ISSUE THREAD

**Issue by MidFavila** [fvwmorg/fvwm3#269]
I use the @g tag to position my FvwmButtons panel dynamically, along with arithmetic operations. In 2.6.9 the following string positions it to the right edge of the X screen.

*VerticalPanel: Geometry 136x$[vp.height]-0-0@g

Using a fresh install from source of FVWM2, this works fine; however, using a fresh install of 3 results in the panel and other @g-tagged elements spawning on the active X monitor, instead of the expected behavior.

To explain further, I have a three-head configuration and need my Buttons panel on the extreme right of the desktop. However, upon initializing the Buttons panel, it will appear on the monitor that currently has the cursor. This behavior only occurs when the element's Geometry is tagged with @g and can be observed in the default configuration as well, by appending @g to line 609. 

For reference, regular untagged positioning of elements works fine. Let me know if any more details are needed.

Thanks.

**Comment by ThomasAdam** [comment]
Hi @MidFavila,

Yes -- this is because in my infinite wisdom, thought it would be a good idea to assume that anything after the `@` symbol was an actual output name, rater than something relative, such as `g` for global.  Will fix.

**Comment by MidFavila** [comment]
Awesome, glad to hear that.

**Comment by ThomasAdam** [comment]
Hi @MidFavila 

Please take a look at PR #270 (branch:  `ta/gh-269`) and let me know if it works for you.  Admittedly, I've only really checked it compiles, and done very minimal testing -- so set your expectations accordingly.  :P

**Comment by MidFavila** [comment]
I've pulled your branch and tested it; the @g tag and friends are fine, now. Thanks for the quick PR.

I did notice some other issues relating to FvwmScript and EwmhStruts, which I can open a new set of reports for, if you'd like.

**Comment by ThomasAdam** [comment]
Hi @MidFavila 

OK, thank you. I'll merge that later. As for your other observations, please open as many issues as you need to.

**Comment by MidFavila** [comment]
Understood. I'll close this report and open some more.
