### ISSUE TITLE
Theme support that integrates with Gnome, KDE and GTK

### ISSUE THREAD

**Issue by kevingnet** [fvwmorg/fvwm3#27]
I've put together a package of files, tools including a config file (origin is mostly from the FVWM official site) which I've modified and it supports themes that extend to gtk, kde and gnome for a more uniform look.
https://github.com/kevingnet/fvwm_themed

**Comment by ThomasAdam** [comment]
Hi,

Thanks for the link. What would you suggest I do with the link?

**Comment by ThomasAdam** [comment]
Feel free to move this information to our [wiki](https://fvwmwiki.org) -- closing for now.
