### ISSUE TITLE
EwmhStruts - Does not affect entirety of X screen, only specific monitor

### ISSUE THREAD

**Issue by MidFavila** [fvwmorg/fvwm3#271]
When using EwmhStruts in 2.6.9 and early builds of FVWM3, EwmhStruts normally behaves in a "global" manner, affecting the entire X screen. In the latest git pull, however, it only appears to affect one monitor (the leftmost?) in regards to horizontal reservations.

I use a triple-head configuration; DP-0, DP-1, and DP-2, with DP-0 as the leftmost head, 1 in the middle, and 2 on the right. However, the following string only produces reserved space on the right side of DP-0; in prior versions, it would have reserved that space on DP-2. 

EwmhBaseStruts 0 137 32 0

Vertical reservation, in this case the topmost 32 pixels, does work globally. Let me know if any more information or clarification is needed.

**Comment by lgsobalvarro** [comment]
You can define a EwmhBaseStruts for each monitor:

EwmhBaseStruts DP-0 foo
EwmhBaseStruts DP-1 foo
EwmhBaseStruts DP-2 0 137 32 0

**Comment by MidFavila** [comment]
Alright, this is my bad, then. I didn't see anything marked in the changelogs; since this is expected behavior and not a bug, I'll close the issue now.

Thanks.

**Comment by MidFavila** [comment]
After adjusting my configuration file with the suggested syntax, EwmhBaseStruts simply ceases to function at all; if I'm still in error, could you provide a pointer to the relevant section of the manual for myself and others in the future?

**Comment by lgsobalvarro** [comment]
My bad, I gave you the wrong syntax:

EwmhBaseStruts screen DP-X foo

**Comment by MidFavila** [comment]
So, upsides and downsides to report. The issue with screen specification and syntax was a me not staying up to date thing; however, the issue with specifying horizontal reservations remains. 

Using the following string, I can successfully manipulate boundaries along the top and bottom of my rightmost display; however, horizontal boundaries still fail to apply. 

EwmhBaseStruts screen DP-2 0 137 32 0

The same exact string specified with my leftmost monitor (DP-0) also fails to apply horizontal boundaries. 

Oddly, they only seem to apply when the screen is not specified; please advise next steps.

**Comment by ThomasAdam** [comment]
Hi @MidFavila 

Hmm.  So if I set:

```
EwmhBaseStruts screen Virtual-1 0 150 50 0
EwmhBaseStruts screen Virtual-2 0 0 0 0
```

Then what I see (when I use xterm) on both monitors when I maximize them, is a fully-maximized xterm on `Virtual-2`, and a window on `Virtual-1` which is 150 from the right, and 50 from the top.   See the screenshot below.  Am I missing something obvious here?  Note that I do not have `Style * ResizeHintOverride` set which means regardless of having a bottom strut of `0` set, there will always be a slight gap.

![fvwm3-example](https://user-images.githubusercontent.com/101281/97093339-ee80c080-1642-11eb-9eb9-989d493d3e7d.png)

**Comment by MidFavila** [comment]
After running over the issue some more on IRC, I'm putting up the details of my XRandR configuration and the FVWM3 debug log, as requested. 



[log.txt](https://github.com/fvwmorg/fvwm3/files/5435591/log.txt)
[xrandr_out.txt](https://github.com/fvwmorg/fvwm3/files/5435592/xrandr_out.txt)
