### ISSUE TITLE
FvwmScript - Crashes on input to TextField widget

### ISSUE THREAD

**Issue by MidFavila** [fvwmorg/fvwm3#272]
In both 2.6.9 and all versions of FVWM3 I have tested, the use of the TextField widget, even when not assigned any function, will result in an immediate hard crash of FVWM, seemingly producing no error logs. This occurs when modifying the contents of the widget, via deletion or insertion with any input device. 

Below is a small unfinished script I wrote that was designed to take input and execute it; however, upon noticing the bug, it has been shelved before functional script was added. If this is an error on my part, apologies in advance.

Thanks.

WindowTitle {Run...}
WindowSize  512 64
WindowPosition 345 767

Widget 1
Property
 Title {Program to Execute...}
 Size 496 24
 Position 8 4
 Flags NoReliefString
 Type TextField
 Value 1
Main
 Case message of
  SingleClic :
  Begin
   Do {Quit}
  End
End

**Comment by ThomasAdam** [comment]
Hi @MidFavila 

Thanks. Is it leaving a corefile behind? If so, could you get a backtrace for me via gdb?

**Comment by MidFavila** [comment]
I'm not sure; would you be able tell me where a corefile would have been dumped? I don't see any in my home directory, for what it's worth.

**Comment by ThomasAdam** [comment]
Hi @MidFavila,

Are you sure this isn't because you have:

```
Case message of
SingleClic :
Begin
Do {Quit}
```

Which would send a message to `fvwm` to Quit, hence it looks like a segfault, but is a valid command.

If I change `Do {Quit}` to `Do {Exec xterm}` then I get an xterm appear.

**Comment by MidFavila** [comment]
Okay, yeah, my bad here... I should have triple-checked the documentation. Sorry for wasting your time with this report.
