### ISSUE TITLE
Fvwm and UI Design.

### ISSUE THREAD

**Issue by sarishinohara** [fvwmorg/fvwm3#279]
![1603800866](https://user-images.githubusercontent.com/37037970/97301613-417f9100-1858-11eb-8485-569d0d7606af.png)

With **FVWM's** Robust features, powerful modules and almost unlimited customization options, it could be the best tool For UI hobbyists to showcase their thoughts and ideas to the world of UI designing.

**Comment by ThomasAdam** [comment]
Awesome work!  If you have any feature requests, please submit them.  :)
