### ISSUE TITLE
EdgeResistance command not working?

### ISSUE THREAD

**Issue by JakeMoe** [fvwmorg/fvwm3#285]
Using my config from FVWM 2, I have a line "EdgeResistance 0" that doesn't seem to be working on FVWM 3; I can't move the mouse off the edge to the next page.  FvwmPager and keyboard shortcuts using GotoPage let me move to them fine.

**Comment by ThomasAdam** [comment]
Hi @JakeMoe 

Works for me, I think.   Can you attach your config to this issue, please?

**Comment by JakeMoe** [comment]
Sure thing; it's attached.  I was mainly checking that the option was still valid.  I can do some further testing with a minimal config to see if anything else is interfering.

It's worth noting, I suppose, that I have 3 monitors; one on a laptop, one monitor connected via HDMI, and one via HDMI througha  USB-C dock.  Not sure if that would affect anything, but figured I'd mention it.

[fvwmconfig.tar.gz](https://github.com/fvwmorg/fvwm3/files/5486319/fvwmconfig.tar.gz)

**Comment by JakeMoe** [comment]
I went with a minimum config, and still had the issue.

```
DesktopSize     3x3
EdgeResistance  0
EdgeScroll      100

DestroyFunc StartFunction
AddToFunc StartFunction
+ I Module FvwmPager

*FvwmPager: Geometry 75x50-0-0
```

FvwmPager also only appears some of the time.  Haven't opened a seperate ticket yet, figuring I'd tackle one issue at a time.  But is there any chance I haven't selected a needed configure/compile option, and the binaries aren't quite right?  I downloaded the code and just ran ./configure and make over it with no options, figuring I'd see if I needed more features later.

**Comment by JakeMoe** [comment]
Just ran into something odd; I was dragging a window, and I accidentally went off the bottom of the page on to the next page with no resistance.  Not sure if that's helpful or useful, but thought I'd add it here.

**Comment by ThomasAdam** [comment]
Hi @JakeMoe,

I haven't yet looked at why `FvwmPager` might not be opening all of the time (perhaps you should generate a separate issue for this?).

But in terms of `EdgeResistance`/`EdgeScroll` -- I think you're missing some values.  I'm using this:

```
DesktopConfiguration per-monitor
DesktopSize     3x3
EdgeResistance  500 500
EdgeScroll      100 100

DestroyModuleConfig FvwmPager:*
*FvwmPager: Monitor $$[monitor.current]
FvwmPager
```

... and have been playing with getting `EdgeScroll`ing to work across independent monitors.  It's not perfect, but you can compile the code on `ta/gh-285` if you wish to give it a go.  This goes some way to addressing the observation you had about when moving windows around, you'd end up flipping pages.  Please note that the code on `ta/gh-285` is still buggy -- but keep your observations here about it, and I'll incorporate this in to my code.

**Comment by JakeMoe** [comment]
Thanks for all your help, but unfortunately I no longer have access to the computer I was working on.  I suppose I'll have to close this ticket at this time; when I get a new computer built and FVWM 3 working again, I'll reopen if I still have an issue.

**Comment by ThomasAdam** [comment]
Hi @JakeMoe 

Fair enough.  I'm leaving this here for a little bit, but I'm expecting this bug to be fixed via the `ta/gh-285` branch.

**Comment by JakeMoe** [comment]
@ThomasAdam I've finally had a chance to look at this further on a new system (Arch now instead of Gentoo, with fvwm3 pulled in from AUR), and found I was having the same problem with the same config, even with the new patch you put in.  Reading the man page a bit more, I wound up putting these three in to make it work:

```
EdgeResistance 0 0
EdgeScroll 100 100
EdgeThickness 1
```

It seems to need all three to work; do both EdgeScroll and EdgeThickness default to 0?
