### ISSUE TITLE
bson_as_relaxed_extended_json() is not available

### ISSUE THREAD

**Issue by pancho-hideboo** [fvwmorg/fvwm3#286]
"bson_as_relaxed_extended_json()" is used in "fvwm3-1.0.1/modulesFvwmMFL/FvwmMFL.c".

However "bson_as_relaxed_extended_json()" is not defined in libbson-1.1.5 which I think as most recent version.
https://github.com/mongodb/libbson/releases/download/1.1.5/libbson-1.1.5.tar.gz

I used bson_as_json() instead.
Could be there any problem ?

**Comment by ThomasAdam** [comment]
Hi @pancho-hideboo 

Yep -- you'll need a newer version of `libbson`

**Comment by pancho-hideboo** [comment]
I can not find out libbson-1.17.2.
I can find libbson-1.9.5 at most.
https://github.com/mongodb/libbson/releases/download/1.9.5/libbson-1.9.5.tar.gz

Where can I get tarball of libbson (>= 1.16.2) ?

**Comment by ThomasAdam** [comment]
https://github.com/mongodb/mongo-c-driver
