### ISSUE TITLE
Add support for the XDG Base Directory Specification

### ISSUE THREAD

**Issue by cmplstofB** [fvwmorg/fvwm3#3]
According to [XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html "freedesktop.org") by freedesktop.org, user configuration files for FVWM3 ought to be stored under `$XDG_CONFIG_HOME/fvwm3` directory. (e.g. `~/.config/fvwm3/config.fvwm`)

Currently, the default configuration files are stored under `~/.fvwm` directory, and FVWM3 does not recognize the files under `$XDG_CONFIG_HOME/fvwm3` directory.

I propose that the configuration files for FVWM3 are stored under `$XDG_CONFIG_HOME/fvwm3` directory, not `~/.fvwm`.

**Comment by ThomasAdam** [comment]
Thank you. But, no. Symlink this if you need it.
