### ISSUE TITLE
Desktop App Menu Flickers

### ISSUE THREAD

**Issue by micadeyeye** [fvwmorg/fvwm3#308]
I am having some problems with FVWM. And I was wondering if someone can assist me to solve them. All pop-ups/drop-downs only flicker and by the time I want to choose an option, they are gone. Here are come concrete examples: clicking on the UMAtrix browser extension in order to enable JS via some URLs would rather only result in the User Interface showing for 1.5sec and it is all gone. NOScript extension drop-down too would not stay on so that I can choose. I can confirm that this problem is also seen in Libreoffice. I cannot click on any of the menu options. The "FILE" menutab, for example, shows for 1.5sec or so and it's gone. I can confirm that it is persistent across all pkgs. To make matter worst, I cannot enter password in some textfields. I would have to go type them in a textfile and then copy-paste into the textfield. For these difficult textfields, by the time I type the first three or more characters, all previous ones are gone. I can confirm that this problem is only peculiar to FVWM; all the pkgs, when used in other desktop environments - OpenBox, MATE, GNOME, etc, - are not having the problems.

The FVWM config is here - https://paste.mozilla.org/3na7CJFW. And the problems are replicated in these two videos -  https://cutt.ly/GhlFGfQ   and  https://cutt.ly/LhlFAWL .  I would appreciate your assistance.

**Comment by ThomasAdam** [comment]
Hey @micadeyeye 

Sorry to hear this isn't working for you,  Before I dive into this, are you able to confirm if this problem you're experiencing is specific to Fvwm, or have you seen this elsewhere?

Kindly,
Thomas

**Comment by danespen** [comment]
micadeyeye <notifications@github.com> writes:

> I am having some problems with FVWM. And I was wondering if someone
> can assist me to solve them. All pop-ups/drop-downs only flicker and
> by the time I want to choose an option, they are gone. Here are come
> concrete examples: clicking on the UMAtrix browser extension in order
> to enable JS via some URLs would rather only result in the User
> Interface showing for 1.5sec and it is all gone. NOScript extension
> drop-down too would not stay on so that I can choose. I can confirm
> that this problem is also seen in Libreoffice. I cannot click on any
> of the menu options. The "FILE" menutab, for example, shows for 1.5sec
> or so and it's gone. I can confirm that it is persistent across all
> pkgs. To make matter worst, I cannot enter password in some
> textfields. I would have to go type them in a textfile and then
> copy-paste into the textfield. For these difficult textfields, by the
> time I type the first three or more characters, all previous ones are
> gone. I can confirm that this problem is only peculiar to FVWM; all
> the pkgs, when used in other desktop environments - OpenBox, MATE,
> GNOME, etc, - are not having the problems.
>
> The FVWM config is here - https://paste.mozilla.org/3na7CJFW. And the
> problems are replicated in these two videos - https://cutt.ly/GhlFGfQ
> and https://cutt.ly/LhlFAWL . I would appreciate your assistance.

That second video shows input fields in a form acting strange.
That's not something Fvwm has any control over.

That looks a little bit like what happened to me yesterday.
I accidentally left a pen laying on a connected drawing tablet.

I think the pen on the tablet was telling the computer button 2
was down.  I managed to restart Fvwm 3 times before I figured
out what was going on.  Button 2 on the root brings up my restart menu.

So, maybe look for a stuck key or some other physical problem.


-- 
Dan Espen

**Comment by micadeyeye** [comment]
Thanks to you two. 
It was indeed the keyboard; a key in it must have been stuck. It is however funky seeing that the problems were not occurring in other desktop environments. FVWM heavily uses the keys unlike other DEs.
