### ISSUE TITLE
Menu placement wrong with multi monitor when position given

### ISSUE THREAD

**Issue by codedmart** [fvwmorg/fvwm3#311]
The placement of a Menu when given position on multi monitor is incorrect when called from the secondary monitor. This is using `+ "More..."   Menu MenuWindowOpsLong This 100 0` in my config.

Primary monitor working:
![Working](https://user-images.githubusercontent.com/40686/101190108-2e10d400-3615-11eb-8ec7-51b8be1cab43.png)

Secondary monitor shows the menu on the primary screen. Not the app/screen I called it from:
![NotWorking](https://user-images.githubusercontent.com/40686/101190107-2d783d80-3615-11eb-95c7-2e41cde0caa3.png)

**Comment by ThomasAdam** [comment]
Hi @codedmart 

Hmm -- I can't reproduce this, and get the same results in `fvwm2`.

**Comment by ThomasAdam** [comment]
@codedmart 

I suspect you are wanting to use this instead:

```
"More..." Menu MenuWindowOpsLong Context 100 0
```

Where the literal word `Context` is relative (in this case) to the window.  This works for me, and seems to do what I *think* you're trying to do.

**Comment by codedmart** [comment]
Well I am not sure if it matters, but I am using `DesktopConfiguration per-monitor`. Either way `Context` seems to solve the problem, so closing. Thanks!
