### ISSUE TITLE
Panframes: switching between desktops not reliable / broken

### ISSUE THREAD

**Issue by MasterP-theGu** [fvwmorg/fvwm3#34]
Expected behaviour from fvwm2: mouse moved over /beyond the edge of desktop (left edge of left screen or right edge of right screen) switches desktop and is indicated in pager. Similarly top / bottom.

Behaviour in fvwm3 branch ta/desktops: top-bottom switch is only possible on main screen, left-right works on both screens. However, it's no longer reliable, sometimes it works, sometimes it doesn't and the mouse pointer simply hits the wall of the edge and can go beyond.
From my current workflow, my first guess is that remmina seems to make fvwm3 misbehave every now and then.

Behaviour in fvwm3 branch ta/gh-22: no switching with the mouse occurs at all. (The pager shows the RightPanel, though.)

Tested with standard config.

**Comment by ThomasAdam** [comment]
Yes, this is to do with the use of `panframes` to detect `InputNotify` events to switch pages.  Having these per-monitor would make things really interesting and annoying.

**Comment by MasterP-theGu** [comment]
:D I can see what you mean by "annoying". :D

**Comment by MasterP-theGu** [comment]
In gh-22 branch, strangely enough, I can switch **upwards** from my primary screen.
All other mouse-swiches are impossible.

**Comment by MasterP-theGu** [comment]
I know, this is a minor point, but I think I should leave some feedback here now that I have been using the gh-22 branch for some time now.
On my fvwm2-system, I have got used to starting windows _when_ever I need them and re-arrange them between the four pages of the desk as necessary. One such use case is that I usually have my main mail accounts open in three different instances of mutt on one page; I can then quickly move one alongside my webbrowser or the editor when I need it and put it back to the others once the task is done. I sometimes re-arrange my windows inside the pager rather than using the real windows to keep my order neat and clean.
In fvwm3 gh-22, moving the real windows has become impossible, but on the upside, the movement of windows _inside_ the pager (mouse-4) or changing the focus of the pager (mouse-3) seem to have become far more reliable and stable.
