### ISSUE TITLE
FvwmRearrange does not work on FVWM3

### ISSUE THREAD

**Issue by NsCDE** [fvwmorg/fvwm3#346]
Hi,

There is no core dump or some weird effect. It just prints this in X11 session log and exits:

`FvwmRearrange: internal inconsistency: unknown message 0x80000008`

Calling it repeatedly every second can make it work sometimes, but rarely.

**Comment by NsCDE** [comment]
Hi Thomas,

I have tried the fix, and message is exactly the same with the same message. No change.

**Comment by ThomasAdam** [comment]
Odd, it's working for me.

What's the exact FvwmRearrange command you're using?

**Comment by NsCDE** [comment]
Try multiple times. Wait minute or two, try again ... it has a strange dynamic. Sometimes it works. Options does not matter. For example:

/opt/fvwm3/bin/FvwmCommand 'Module FvwmRearrange -tile -maximize'
