### ISSUE TITLE
Support lists of fonts (for falling back on)

### ISSUE THREAD

**Issue by wyatt8740** [fvwmorg/fvwm3#37]
I was asked to create this issue on IRC after I brought it up there.

Quoting from the channel:
> I think FVWM3 should be able to use 'fallback' fonts, or maybe a list of fonts, for cases where a character isn't represented in the preferred font. Currently (in FVWM2) lots of japanese text is rendered as '??' characters since I am en_US.UTF-8 and using a font without CJK support.

It'd be good to handle it so that in the event of a glyph that is not in the primary/preferred font, a list of the second, third, and fourth… etc. fonts can be 'fallen back' on to supply the given character.

Example (in my mind, just so you get the general idea):

The current way it works:
```
# Tahoma just is chosen as an example of a somewhat common font that doesn't support CJK.
Style * Font "xft:Tahoma:size=8:bold"
```
CJK characters like 'あ' will render as `??`.

My suggestion is something like:
```
# Try to use tahoma for the characters it has support for, and try the TTF version of GNU Unifont as a fallback
Style * Font "xft:Tahoma:size=8:bold,xft:Unifont"
```
Maybe even make that a style attribute named 'Font**s**' instead of 'Font'. Of course, however is the easiest way to parse a list would be fine. I used commas just because that's how CSS does it.

**Comment by ThomasAdam** [comment]
Hi,

This seems to be the case already.  From `fvwm(1)`:

```
       A font name can be given as an extended XLFD.  This is a comma
       separated list of (simple) XLFD font names, for example:

           -adobe-courier-bold-r-normal--14-*,-*-courier-medium-r-normal--14-*

       Each simple font name is tried until a matching font with the locale
       charset is found and if this fails each simple font name is tried
       without constraint on the charset.
```

**Comment by wyatt8740** [comment]
@ThomasAdam I just tried this; my line looks like:
```
Style * Font "xft:Tahoma:size=8:antialias=false,xft:Noto Sans Mono CJK JP:size=8:antialias=false"
```
I have also tried:
```
Style * Font "xft:Tahoma:size=8:antialias=false","xft:Noto Sans Mono CJK JP:size=8:antialias=false"
```
And neither works. I get Tahoma and rectangles instead of CJK glyphs.
If I only specify Noto Sans Mono CJK JP, that works, but all non-CJK text uses that font.
