### ISSUE TITLE
SkipMapping disables StartsOnPage/StartsOnDesk

### ISSUE THREAD

**Issue by slalik** [fvwmorg/fvwm3#373]
I noticed a regression in version 1.0.2: with SkipMapping style, StartsOnPage/StartsOnDesk stop working.

I take the config
```
DesktopName 0 Desk0
DesktopName 1 Desk1
DesktopSize 1x1
```

If I add
```Style xterm StartsOnPage 1```
it works as expected, xterm starts on Desk1.

But if I add
```Style xterm SkipMapping, StartsOnPage 1```
xterm starts on Desk0

Moreover, if I add
```Style xterm SkipMapping```
and run
```xterm -xrm "*Desk:1"```
it starts on Desk0.

Without
```Style xterm SkipMapping```
```xterm -xrm "*Desk:1"```
works as expected.

There was no this problem in version 1.0.1.

* Fvwm3 version
fvwm3 1.0.2 (released)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS

* Linux distribution
Slackware 14.2

* Platform
Linux Intel(R) Xeon(R) CPU E3-1275 v5 @ 3.60GHz

**Comment by ThomasAdam** [comment]
Hi @slalik 

Thanks!  Please see the PR referenced here -- for reference, please checkout the `ta/gh-373` and let me know if that fixes things for you.  I'd also keep a very close eye out for any other unintended breakages as well.

Just FYI (since you mention it), I will be removing the Xrm method of being able to tell `fvwm3` where windows should be placed, so don't rely on that too much.

**Comment by slalik** [comment]
I applied the patch to released version 1.0.2. The result is the following. I have 2 monitors. They are configured by the command
```
xrandr --output HDMI-2 --primary --auto --output HDMI-1 --right-of HDMI-2 --auto
```
There is nothing about dual monitors in the fvwm config.

After the patch, StartsOnPage is respected then a program starts from the prime monitor and ignored if it starts from the second monitor. I checked for several programs.

Should I also checked `ta/gh-373`?
(I prefer released versions because I maintain fvwm3 for SlackBuilds.org)

**Comment by ThomasAdam** [comment]
> After the patch, StartsOnPage is respected then a program starts from the prime monitor and ignored if it starts from the second monitor. I checked for several programs.

Can you provide more information here?  What do you mean?

If you're wanting a specific style to apply to a specific screen, then you can use:

    Style foo StartsOnScreen <randr_name>

**Comment by slalik** [comment]
I did more experiments and I see that it depends on the cursor position. For example, I have
```
Style xeyes SkipMapping, StartsOnPage 1
```
If I start xeyes when the mouse cursor is on Desk0 on left (prime) monitor, xeyes start on Desk1, if the cursor is on Desk0 on the right monitor, xeyes start on Desk0.

I even tried to disable mouse with
```
xinput --set-prop "..." "Device Enabled" "0"
```
The result is the same depends on the cursor position at the moment of disabling.

**Comment by ThomasAdam** [comment]
Hi @slalik 

Yes, this is expected.  If you use `StartsOnScreen <randr_name>` -- this should help, otherwise, `fvwm3` is just guessing.

Either way, my original patch seems to have fixed your problem, yes?

**Comment by slalik** [comment]
Yes,
```
Style xeyes SkipMapping, StartsOnPage 1, StartsOnScreen HDMI-2
```
works, so the problem is fixed. Thank you!
