### ISSUE TITLE
fvwm crash with Program terminated with signal SIGABRT

### ISSUE THREAD

**Issue by domichel** [fvwmorg/fvwm3#383]
* fvwm3 --version
fvwm3 1.0.3 (1.0.2-13-g05117cc6)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS

* Gentoo Linux with kernel 5.9.0-rt16

* uname -sp
Linux AMD E-450 APU with Radeon(tm) HD Graphics

I wanted to change the recipe in fvwm-crystal. I get a crash with a core file. The last message I get into fvwm log file is "--- Recipe loaded ---" which is an Echo command at the last line of the recipe.

As crystal erase the log file at startup, I can join it next time it crash.
I don't know how to reproduce it because it doesn't happen each time I change the recipe.

It doesn't happen with Fvwm2.

With gdb I get:

```
Reading symbols from /usr/bin/fvwm3...
(No debugging symbols found in /usr/bin/fvwm3)
```
I can easily enable then if needed.

```
[New LWP 8217]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `fvwm3 -v -f /usr/bin/../share/fvwm-crystal/fvwm/config'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f1867b7e5c4 in raise () from /lib64/libc.so.6
```

```
(gdb) bt full
#0  0x00007f1867b7e5c4 in raise () at /lib64/libc.so.6
#1  0x00007f1867b68536 in abort () at /lib64/libc.so.6
#2  0x00007f1867bbeb57 in  () at /lib64/libc.so.6
#3  0x00007f1867bc60ba in  () at /lib64/libc.so.6
#4  0x00007f1867bc7d2b in  () at /lib64/libc.so.6
#5  0x000055636647848b in merge_styles ()
#6  0x0000556366480db3 in simplify_style_list ()
#7  0x000055636648f445 in HandleEvents ()
#8  0x000055636646a57e in main ()
```
It doesn't look to be helpful, so I will tell portage to not strip the symbols and reinstall fvwm3.

fvwm3 is started with "exec  /usr/bin/fvwm-crystal 2>.errors.fvwm-crystal". In that file I get:
...
double free or corruption (fasttop)
...

**Comment by domichel** [comment]
[.fvwm-crystal.log.txt](https://github.com/fvwmorg/fvwm3/files/5731121/default.fvwm-crystal.log.txt)

**Comment by slazav** [comment]
I managed to reproduce this crash, with fvwm-crystal (changing window decorations from the menu).
bt with debug symbols:
#0  0x00007ffff70c6891 in raise () from /lib64/libc.so.6
#1  0x00007ffff70b055b in abort () from /lib64/libc.so.6
#2  0x00007ffff71091b8 in ?? () from /lib64/libc.so.6
#3  0x00007ffff711056a in ?? () from /lib64/libc.so.6
#4  0x00007ffff711238d in ?? () from /lib64/libc.so.6
#5  0x000055555557511f in merge_styles (merged_style=merged_style@entry=0x55555578dde0,.
    add_style=add_style@entry=0x555555854640, do_free_src_and_alloc_copy=do_free_src_and_alloc_copy@entry=1)
    at style.c:397
#6  0x000055555557cac0 in __simplify_style_list () at style.c:1088
#7  simplify_style_list () at style.c:4739
#8  0x000055555558a4ed in HandleEvents () at events.c:4202
#9  0x000055555556766f in main (argc=<optimized out>, argv=<optimized out>) at fvwm3.c:2563
