### ISSUE TITLE
Applications not respecting screen/page

### ISSUE THREAD

**Issue by codedmart** [fvwmorg/fvwm3#389]
Thanks for reporting your bug here!  The following template will help with
giving as much information as possible so that it's easier to diagnose and
fix.

## Upfront Information

Please provide the following information by running the command and providing
the output.

* Fvwm3 version (run: `fvwm3 --version`)
```
fvwm3 1.0.1 (1.0.0-137-g1bebad17)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS
```

* Linux distribution or BSD name/version
Void linux and Gentoo linux

* Platform (run: `uname -sp`)
`uname -sp -> Linux unknown` 
`uname -a -> Linux void 5.9.14_1 #1 SMP 1607957763 x86_64 GNU/Linux`

## Expected Behaviour

Applications do not respect screen/page.

If I have an application on screen 1 page 1. Then I go to screen 1 page 10 I see part of the application off to the left of screen 1. If I go to screen 1 page 9 I see the application that I start and is on screen 1 page 1 on screen 2 regardless of page on screen 2.

If I have an application on screen 2 page 1. Then I go to screen 2 page 10 I see the application on screen 1 regardless of page on screen 1.

## Actual Behaviour

I would expect applications to only be visible on the screen/page that they are on.

## Enabling logging
Logs did not provide any information from this.

## Steps to Reproduce
```
DesktopSize 10x1

DesktopConfiguration per-monitor
```
Open and application on screen 1 page 1, then go to screen 1 page 10, and you should see part of the application on screen 1 page 10 that you opened on screen 1 page 1. Then go to screen 1 page 9, and you should see the application on screen 2 regardless of the page screen 2 is on.

* Does the problem also happen with Fvwm2?
No

## Does Fvwm3 crash?
No crash

## Extra Information
![2020-12-23 08-00-07](https://user-images.githubusercontent.com/40686/103012186-6dd22980-44f8-11eb-8daf-64956937f356.gif)

**Comment by ThomasAdam** [comment]
Hi @codedmart 

Thanks for your report.  I see you list:

```
DesktopSize 10x1
DesktopConfiguration per-monitor
```

Is that literally how you have it in your config?  If so, what happens to your problem if you swap the order of those two lines, so it now looks like this:

```
DesktopConfiguration per-monitor
DesktopSize 10x1
```

**Comment by codedmart** [comment]
Doesn't seem to make any difference if I change the order of those.

**Comment by codedmart** [comment]
Comment from irc:
> This also happens on fvwm2, and I see why now... I can't fix this.  The problem is that the coordinates will start to wrap around, when you consider that pages are just areas on a screen -- so if you have a linear set of pages (1x10) and your resolution is therefore low enough for those ten pages to overflow each other, that'll cause your problem.  As I say, no easy way round this.

I switched to a 3x3 anyways so this is fine with me to close.
