### ISSUE TITLE
StartsOnPage/StartsOnDesk ignored

### ISSUE THREAD

**Issue by afhp-2020** [fvwmorg/fvwm3#39]
Hello,

Using a config file I am adapting and correcting from fvwm2, I came across a regression regarding forced window placement on a given desktop.
Configuration is explicitely declared global (but it makes no difference) :
`DesktopConfiguration global`

I do not use pages, and 4 desktops are defined:
```
DesktopSize 1x1
DesktopName 0 Net
DesktopName 1 Dev
DesktopName 2 MM
DesktopName 3 Misc
EdgeScroll 0 0
EdgeThickness 0
```

Multimedia applications are set to open on Desktop 2:
```
Style vlc StartsOnPage 2
Style mpv StartsOnPage 2
```
(`StartsOnDesk 2` does no better)

Opening any application defined as above to open on a given desk results in the application actually opening on the current active desk.

This configuration was working as expected under fvwm2.

It should be noted that `StartsOnScreen` on the other hand works as documented.

**Comment by ThomasAdam** [comment]
Hi,

Yes, you're right.   Probably related to #22.

**Comment by ThomasAdam** [comment]
Can you retest this, please?  I've tested this with:

```
Style xeyes StartsOnScreen HDMI2, StartsOnPage 1 1, SkipMapping
```

... and starting xeyes: `xeyes +shape` puts that window on Page 1 1, on my second screen (which is not considered the `active` screen; that is, my mouse pointer is on a different monitor) -- so this is working OK.

Please confirm.

**Comment by afhp-2020** [comment]
Hello,

Not yet entirely familiar with git ; did a `git pull origin ta/gh-22`, recompiled, reinstalled and restarted from display manager.
(Note: compiling and installing with make ; sudo make install on FreeBSD, compiles and installs without error. Thanks for keeping the code system- and make-agnostic.)

Testing with current configuration elements, as in `Style mpv StartsOnPage 2`, as well as variations on your style definition above, in succession:

`Style xeyes StartsOnScreen DP-2, StartsOnDesk <n>` : as before, Screen is respected, Desk is ignored, the window appears on the current desk. Same with `StartOnPage <n>`.

Since I am not using pages, `StartsOnPage` with non-zero 2nd and/or 3rd argument obviously cause the window to not be shown. Otherwise, same behavior, the window appears on the current desk regardless of the first argument.

The presence or absence of `SkipMapping` has no effect.

**Comment by ThomasAdam** [comment]
Hi @afhp-2020 

Really fixed this time.  Please git pull on `ta/gh-22` as you've been doing and try again!

This is working for me:

`Style xeyes StartsOnDesk 4`

**Comment by afhp-2020** [comment]
Got lost in git merge so I re-cloned master and re-pulled ta/gh-22 again.

I am happy to report that the issue is fixed.

`Style xeyes StartsOnDesk <n>` issued at FvwmConsole, starting xeyes opens it on the specified desktop.
Similarly with existing `Style <application> StartsOnPage 2` in config file, specified applications open where expected.
