### ISSUE TITLE
FvwmCommand is missing a man page

### ISSUE THREAD

**Issue by ThomasAdam** [fvwmorg/fvwm3#393]
When `FvwmCommand` was replaced as a wrapper around `FvwmMFL` the existing man page was not included.

One needs to be written.

@NsCDE -- would you be interested?

**Comment by NsCDE** [comment]
As I answered on the list, yes. Existing one has to be adapted, or new one written. But this will wait a bit because of my other issues.

**Comment by ThomasAdam** [comment]
> As I answered on the list, yes. Existing one has to be adapted, or new one written. But this will wait a bit because of my other issues.

No rush at all, @NsCDE -- let me know if you need a hand.  Hope everything's going OK.

**Comment by NsCDE** [comment]
Hi

Just to give icmp echo-reply ... :-)

Existing man page needs to be adapted, or new one written. But this should still wait a bit because I have to settle some private issues. I cannot plunge myself into FVWM and NsCDE this month because I don't have a good multitasking. See you!

**Comment by ThomasAdam** [comment]
Hi @NsCDE 

I hope you're well.  I hate to ask, but do you think you'll have time to look at this man page soon?  The `1.0.3` release isn't far off and I'd like to include this.  If you can't do it, not a problem, as I'm sure I can put some words together.

Kindly,
Thomas

**Comment by NsCDE** [comment]
Hi @ThomasAdam 

I didn't forgot this, even have a reminder. Apart from regular job, I have a load of paperwork and tasks which I must to solve IRL and I hope this will be finished soon.

I will try to put this together during this week, but I cannot promise. :-(

**Comment by ThomasAdam** [comment]
Hey @NsCDE 

Not at problem -- we all have lives!  To get you started, I've created a pull-request #503 which you can use as a basis if you want it.

**Comment by ThomasAdam** [comment]
Hi @NsCDE 

I've merged this for now -- if we want to do anything further for this, post the 1.0.3 release, we can do.

**Comment by NsCDE** [comment]
Ok, thanks, and sorry for slowness on my side. As I said, I hope to be more on this what I like for couple of weeks.
Congrats on 1.0.3!
