### ISSUE TITLE
feature request: global menu support

### ISSUE THREAD

**Issue by nsklaus** [fvwmorg/fvwm3#4]
i'm openning this feature request following a talk on \#fvwm channel, to discuss the feasibility of adding global menu support on fvwm3.

## what are globalmenu / appmenu:
"it's a menu exported out of an application window via DBus and placed instead on a desktop panel. "

## implementation:
among the ideas that were discussed in the channel, it was expressed that perhaps it "could be implemented as a synchronous module written against libfvwm which relies on DBus". 

for reference: [freedesktop.org](https://www.freedesktop.org/software/gstreamer-sdk/data/docs/latest/gio/GMenuModel.html)
"The motivation for this abstract model of application controls is that modern user interfaces tend to make these controls available outside the application. Examples include global menus, jumplists, dash boards, etc."
that link is the closest match i could find to document the feature. please let me know if you find something better. 

## usage
on other desktops,  usualy a global shell variable is being set to enable / disable exporting the menus. it works with qt and gtk apps.
the menu displayed in the panel is the one from the focused application.
idealy, when no application are focused, then a default menu is displayed 
(e.g: some kind of desktop menu.. rearrange icons, create file, delete file and such)

## example of the feature as seen in other desktops

budgie:
![budgie](https://user-images.githubusercontent.com/6810861/58251462-f9effe00-7d63-11e9-8790-1f7cb7b42931.png)

elementary:
![elementary](https://user-images.githubusercontent.com/6810861/58251467-01170c00-7d64-11e9-9379-844f6d2ab473.png)

gnome:
![gnome](https://user-images.githubusercontent.com/6810861/58251482-08d6b080-7d64-11e9-92e0-651f6d61ecfe.png)

kde:
![kde3](https://user-images.githubusercontent.com/6810861/58251491-10965500-7d64-11e9-896f-048c9c512b7f.png)

xfce:
![xcfe](https://user-images.githubusercontent.com/6810861/58251508-168c3600-7d64-11e9-8b93-e5451c2f9d03.png)

**Comment by ThomasAdam** [comment]
Moved to TODO.  Thanks.

**Comment by nsklaus** [comment]
> Moved to TODO. Thanks.

maybe i'm not looking at the right file, i can't find it in the todo [here](https://github.com/fvwmorg/fvwm3/blob/master/dev-docs/TODO.md) ?

**Comment by ThomasAdam** [comment]
It's there -- just didn't push the branch out.  Now I have.

**Comment by nsklaus** [comment]
i understand better, thank you for telling.
