### ISSUE TITLE
Can't build FvwmPrompt for PowerPC 32-bit (golang.org/x/sys/unix doesn't build on PPC32 with gccgo, and regular go doesn't work at all)

### ISSUE THREAD

**Issue by wyatt8740** [fvwmorg/fvwm3#407]
## Upfront Information

Please provide the following information by running the command and providing
the output.

* Fvwm3 version (run: `fvwm3 --version`)
````
    fvwm3 1.0.3 (1.0.2-41-gf1f7c4e2)
    with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS
````
(git master as of today)

* Linux distribution or BSD name/version

* Platform (run: `uname -sp`)
````
Linux unknown
````
Debian Sid (Ports project, powerpc 32-bit; see [here](https://cdimage.debian.org/cdimage/ports/current/))
`uname -a`:
````
Linux wyatt-PowerBookG4-Debian 5.9.0-rc7-wyatt #1 Tue Sep 15 12:47:49 EDT 2020 ppc GNU/Linux
````
## Expected Behaviour
Compile FVWM3 with support for FVWMPrompt (by running `configure` with `--enable-golang`)

## Actual Behaviour
Using regular `gc`-based "go" is impossible on PowerPC 32-bit; gccgo seems to work with the `gccgo-go` package to an extent, but when trying to build `FvwmPrompt` hits a massive stream of error messages that basically indicate that PowerPC 32-bit [doesn't have any syscall support in go ](https://github.com/golang/go/issues/37443) (see that issue for a printout).

## Enabling logging
N/A; fails to build from source.
## Steps to Reproduce
See above; basically `./configure --enable-golang; make`
> Does the problem also happen with Fvwm2?

No, because Fvwm2 does not use Go for FvwmCommand.

> Include your configuration with this issue.

N/A; fails to build from source.

## Does Fvwm3 crash?
No.

## Extra Information
> Anything else we should know?

I am available to talk on IRC if you'd like to discuss further; additionally, as a really ugly workaround I can use OpenBSD's netcat like so:
````
#! /usr/bin/env/sh
if [ "$#" -gt 0 ]; then
  echo "$@" | nohup nc.openbsd -q 1 -U /tmp/fvwm_mfl.sock > /dev/null 2>&1
else
  1>&2 echo 'Error: no commands to issue were given. Exiting.'
fi
````
> Feel free to take a screen capture or video and upload to this issue if you
  feel it would help.

It wouldn't, but do see the output from [here](https://github.com/golang/go/issues/37443).

> Attach `$HOME/.fvwm/fvwm3-output.log` from the step above.

N/A.

**Comment by ThomasAdam** [comment]
Hi @wyatt8740 

Well, there's nothing fvwm3 can do to help you with this.  PowerPC 32-bit architecture is interesting I'm sure, but it's not something I'm keen to address "supporting" in fvwm3 -- which, AFAICT, would be to do something which befitted a language your  hardware accepted.

You can either keep using your openbsd nc wrapper (or just use `FvwmCommand` -- same thing, just in Python), or disable go in fvwm3's `configure` step, and let `FvwmConsole` compile instead if you really want a prompt per-se.

By all means, catch me on IRC if there's anything else you want to mention, but I'm closing this for now.
