### ISSUE TITLE
Replace libbson with cJSON

### ISSUE THREAD

**Issue by ThomasAdam** [fvwmorg/fvwm3#408]
Currently, `fvwm3` uses `libbson` (from `mongodb`) to send JSON information between `fvwm3` and `modules`, but also to the end-user (via the `Status` command).  One nice property of `libbson` is that the API it uses to compose JSON is quite compact (and hence less verbose).  However, there  are a few downsides:

* `libbson` is tangled with `mongodb` and is not packaged well across Linux/BSD to the point where downstream packagers have had to package `libbson` as a prerequisite dependency, placing more burden on the maintainer.
* `libbson` is very memory-intensive, relative to what it is doing (JSON).

Other alternatives exist.  However, in thinking about the amount of JSON that `fvwm3` could use, there is very little IPC involving large amounts of data where we care about compressing it, and hence introducing that API.

cJSON has a good enough API that we could use that to send JSON, and has the advantage that it's small enough to be embedded directly in `fvwm3`'s source repository, without needing another external dependency.

This therefore removes the dependency on `libbson` from `fvwm3`, and since `cJSON` is part of the source tree, no other external dependency is required.

**Comment by lgsobalvarro** [comment]
Yes. Msgpack is available in the main OpenSUSE repos. That means that OpenSUSE (and by extension SUSE and Gecko users) wouldn't have to add an extra repo (databases) in order to be able to use fvwm3.

I would also be able to maintain a fvwm3 package via Open Build Services for OpenSUSE without any issues.

**Comment by BrianA-MN** [comment]
Both libbson, mongodb, and msgpack are available for Slackware users in the Slackbuilds repository.  Although not accepted by the Slackware maintainer, Slackbuilds.org is available to all Slackware users and maintains higher than normal testing of submissions from packagers to assure they don't break something else or conflict with standard packages.  HTH.
