### ISSUE TITLE
killing stalonetray also kills RightPanel

### ISSUE THREAD

**Issue by MasterP-theGu** [fvwmorg/fvwm3#420]
Thanks for reporting your bug here!  The following template will help with
giving as much information as possible so that it's easier to diagnose and
fix.

## Upfront Information

Please provide the following information by running the command and providing
the output.

* Fvwm3 version
fvwm3 1.0.3 (1.0.2-46-g4e56e5fe)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS
 
* Linux distribution or BSD name/version
archlinuxarm armv7

* Platform (run: `uname -sp`)
armv7 
## Expected Behaviour

What were you trying to do?  Please explain the problem.
`killall stalonetray `kills stalonetray without collateral damage

## Actual Behaviour

What should have happened, but didn't?

only stalonetray should have died, no other program or Module should have been killed off.
The whole RightPanel, however, vanishes / dies.

## Enabling logging

The resulting logfile can be found in `$HOME/.fvwm/fvwm3-output.log`.

This is the relevant part of the output.log:

```
[1612103837.344620]  log opened (because of SIGUSR2)
[1612103843.859428] setup_window_placement: Expanding screen from 'null' -> ''
[1612103843.859594] ewmh_ComputeAndSetWorkArea: monitor 'HDMI-1': {l: 120, r: 0, t: 0, b: 0} {x: 120, y: 0, w: 3080, h: 1080}
[1612103843.859617] EWMH_GetWorkAreaIntersection: mon: HDMI-1 {ax: 120, ay: 0, aw: 3080, ah: 1080
[1612103843.859633] EWMH_GetWorkAreaIntersection: mon: HDMI-1 {x: 0, y: 0, w: 3200, h: 1080
[1612103843.859648] EWMH_GetWorkAreaIntersection: mon: HDMI-1 finalising: {x: 120, y: 0, w: 3080, h: 1080}
[1612103843.859750] ewmh_ComputeAndSetWorkArea: monitor 'HDMI-1': {l: 120, r: 0, t: 0, b: 0} {x: 120, y: 0, w: 3080, h: 1080}
[1612103843.859770] EWMH_GetWorkAreaIntersection: mon: HDMI-1 {ax: 120, ay: 0, aw: 3080, ah: 1080
[1612103843.859784] EWMH_GetWorkAreaIntersection: mon: HDMI-1 {x: 0, y: 0, w: 1920, h: 1080
[1612103843.859800] EWMH_GetWorkAreaIntersection: mon: HDMI-1 finalising: {x: 120, y: 0, w: 1800, h: 1080}
[1612103871.762491] ewmh_ComputeAndSetWorkArea: monitor 'HDMI-1': {l: 120, r: 0, t: 0, b: 0} {x: 120, y: 0, w: 3080, h: 1080}
[1612103871.763363] ewmh_ComputeAndSetWorkArea: monitor 'HDMI-1': {l: 120, r: 0, t: 0, b: 0} {x: 120, y: 0, w: 3080, h: 1080}
[1612103871.766450] ewmh_ComputeAndSetWorkArea: monitor 'HDMI-1': {l: 120, r: 0, t: 0, b: 0} {x: 120, y: 0, w: 3080, h: 1080}
[1612103871.776032] ewmh_ComputeAndSetWorkArea: monitor 'HDMI-1': {l: 120, r: 0, t: 0, b: 0} {x: 120, y: 0, w: 3080, h: 1080}
[1612103871.778000] ewmh_ComputeAndSetWorkArea: monitor 'HDMI-1': {l: 120, r: 0, t: 0, b: 0} {x: 120, y: 0, w: 3080, h: 1080}
[1612103871.811166] ewmh_ComputeAndSetWorkArea: monitor 'HDMI-1': {l: 120, r: 0, t: 0, b: 0} {x: 120, y: 0, w: 3080, h: 1080}

```

That last line would be repeated ad infinitum (?) and only stops appearing when I restart fvwm3.

## Steps to Reproduce

How can the problem be reproduced?  For this, the following is helpful:

* Reduce the problem to the smallest `fvwm` configuration example (where
  possible).  Start with a blank config file (`fvwm3 -f/dev/null`) and go from
  there.
n/a (RightPanel needed)

* Does the problem also happen with Fvwm2?
Strangely enough, yes. Although I am running both with the same config and parallel, synchronous on the same machine, so I don't know if that counts.

Include your configuration with this issue.

I use the standard config with only a few modifications. Here's the section on the RightPanel:
```
# Note - To use the system tray you must have "stalonetray" installed.
DestroyModuleConfig RightPanel:*
*RightPanel: Geometry 120x$[vp.height]+0+0
*RightPanel: Colorset 10
*RightPanel: Rows $[vp.height]
*RightPanel: Columns 120
*RightPanel: Frame 0
*RightPanel: Font "xft:Sans:Bold:size=10:antialias=True"
*RightPanel: (120x45, Icon "fvwm-logo-small.png", Frame 0)
*RightPanel: (120x5, Frame 0)
*RightPanel: (10x20, Frame 0)
*RightPanel: (25x20, Id desk0, Title "0", Action (Mouse 1) GotoDesk 0 0, Colorset 11, ActiveColorset 12, Frame 0)
*RightPanel: (25x20, Id desk1, Title "1", Action (Mouse 1) GotoDesk 0 1, ActiveColorset 12, Frame 0)
*RightPanel: (25x20, Id desk2, Title "2", Action (Mouse 1) GotoDesk 0 2, ActiveColorset 12, Frame 0)
*RightPanel: (25x20, Id desk3, Title "3", Action (Mouse 1) GotoDesk 0 3, ActiveColorset 12, Frame 0)
*RightPanel: (10x20, Frame 0)
*RightPanel: (5x80, Frame 0)
*RightPanel: (110x80, Swallow FvwmPager 'Module FvwmPager *', Frame 0)
*RightPanel: (5x80, Frame 0)
*RightPanel: (120x5, Frame 0)
Test (x stalonetray) *RightPanel: (120x20, Swallow(NoClose,UseOld) \
    stalonetray 'Exec exec stalonetray --config \
    "$[FVWM_DATADIR]/default-config/.stalonetrayrc"', Frame 0)
Test (x stalonetray) PipeRead 'echo "*RightPanel: (120x$(($[vp.height]-225)), \
    Top, Swallow FvwmIconMan \'Module FvwmIconMan\', Frame 0)"'
Test (!x stalonetray) PipeRead 'echo "*RightPanel: (120x$(($[vp.height]-205)),\
    Top, Swallow FvwmIconMan \'Module FvwmIconMan\', Frame 0)"'
*RightPanel: (120x45, Swallow DateTime 'Module FvwmScript FvwmScript-DateTime',\
    Frame 0)
*RightPanel: (120x5, Frame 0)

# FvwmPager
```

## Does Fvwm3 crash?
no.

## Extra Information

* Anything else we should know?

stalonetray 0.8.3 [ XPM:yes DEBUG:yes KDE:yes ]

* Feel free to take a screen capture or video and upload to this issue if you
  feel it would help.

* Attach `$HOME/.fvwm/fvwm3-output.log` from the step above.
cf. above

**Comment by ThomasAdam** [comment]
Hi @MasterP-theGu 

Thanks for the report.  Is there anything logged to stderr (usually `~/.xsession-errors` or some other file if your display manager isn't XDM) when you kill stalonetray?  Is FvwmButtons leaving a corefile somewhere?

There's nothing inherently bad with the config you've supplied, so I'm presuming that FvwmButtons is crashing.

**Comment by MasterP-theGu** [comment]
Hi @ThomasAdam,

I'm not using a display manager, so I guess the right place to look for errors is `/var/log/Xorg.0.log`. Nothing happens there when I kill stalonetray. So far I haven't found a corefile for FvwmButtons, yet. The broadest search was when I've looked for a file under ~/ that contains FvwmButtons in its name -- do you have another idea for the location or name of the corefile?

**Comment by lgsobalvarro** [comment]
I can reproduce this with the default config.

Just as @MasterP-theGu reports a `killall stalonetray` will kill FvwmButtons.

However... `kill -9 *stalonetray process number*` does not crash FvwmButtons

Using xkill will also crash FvwmButtons. This is what xkill logs:
>Select the window whose client you wish to kill with button 1....
>xkill:  killing creator of resource 0x2200001
>X11 error: BadWindow (invalid Window parameter) (request: X_GetWindowAttributes, resource 0x3)
>X11 error: BadWindow (invalid Window parameter) (request: X_GetWindowAttributes, resource 0x3)
>X11 error 3 detected at debug.c:140:print_icon_data
>X11 error: BadWindow (invalid Window parameter) (request: X_ChangeWindowAttributes, resource 0x2)
>X11 error: BadWindow (invalid Window parameter) (request: X_UnmapWindow, resource 0xa)
>X11 error: BadWindow (invalid Window parameter) (request: X_ReparentWindow, resource 0x7)
>X11 error: BadWindow (invalid Window parameter) (request: X_ConfigureWindow, resource 0xc)
>X11 error: BadWindow (invalid Window parameter) (request: X_MapWindow, resource 0x8)
>X11 error: BadWindow (invalid Window parameter) (request: X_DestroyWindow, resource 0x4)
>X11 error: BadWindow (invalid Window parameter) (request: X_ChangeProperty, resource 0x12)
>X11 error: BadWindow (invalid Window parameter) (request: X_SendEvent, resource 0x19)
>X11 error: BadWindow (invalid Window parameter) (request: X_GetWindowAttributes, resource 0x3)
>X11 error 3 detected at xutils.c:259:x11_get_window_size
>X11 error: BadWindow (invalid Window parameter) (request: X_ChangeProperty, resource 0x12)
>X11 error: BadWindow (invalid Window parameter) (request: X_ConfigureWindow, resource 0xc)
>X11 error 3 detected at xutils.c:132:x11_get_window_prop32

My xorg-session.log does not show anything out of the ordinary. There is nothing neither in fvwm3-output.log related to FvwmButtons or stalonetray.

**Comment by ThomasAdam** [comment]
Stalonetray bug.  Please report this to them.
