### ISSUE TITLE
rename binary fvwm3 -> fvwm

### ISSUE THREAD

**Issue by slazav** [fvwmorg/fvwm3#440]
If one wants to make fvwm3 package, there are two good choices:
- it replaces old fvwm
- it can be installed together with old fvwm

In the first case it's good to rename fvwm3 binary+manpage to fvwm. In the second case something should be done with other file conflicts (module manpages, fvwm-config/fvwm-root programs). I think replacing of fvwm2 should be done here.

**Comment by ThomasAdam** [comment]
Hi @slazav 

Possibly in the future.  For now, there are the `--program-prefix`, `--program-suffix`, and `--program-transform-name` options to `./configure` which you can use to help with this.

But I won't be doing anything about any of this just yet -- this would be a wider change than just the `fvwm3` binary name.  Now is not the time.

**Comment by slazav** [comment]
It's certainly not a big problem, it's easy to rename files when making the package. I just wanted to say about this choice. It always happens when you start thinking how to install fvwm3 in your system.
