### ISSUE TITLE
_NET_CURRENT_DESKTOP tracking breaks google-chrome

### ISSUE THREAD

**Issue by ThomasAdam** [fvwmorg/fvwm3#442]
Google-chrome/Chromium allow for windows and tabs to be moved between one another.  This means the user is able to drag and drop tabs between different windows.

However, the browser only provides this functionality if the current desktop (via `_NET_CURRENT_DESKTOP`) matches.  Chromium appears to be doing some clever mouse-tracking in order to know wher windows/tabs are coming from.  With `DesktopConfiguration global` this always works, since with >1 monitor, the desktop is the same on both screens.  However, if one is using `DesktopConfiguration per-monitor` and one of the browser windows happens to be on different desktops to one another, then this functionality breaks.

Currently, `_NET_CURRENT_DESKTOP` is only updated when a `new_desk` event occurs.  It's logical to assume this check should be updated on other events, such as when focus changes, but only when the monitors differ, and/or the desktops are different, and/or a window is being moved between screens.

**Comment by lgsobalvarro** [comment]
I have noticed this too with Brave Browser. It works but somehow is... clunky.
