### ISSUE TITLE
(CurrentPage, AnyScreen) calculation slightly too generous. (Regression cf. fvwm2.)

### ISSUE THREAD

**Issue by taobert** [fvwmorg/fvwm3#443]
Thanks for reporting your bug here!  The following template will help with
giving as much information as possible so that it's easier to diagnose and
fix.

## Upfront Information

Please provide the following information by running the command and providing
the output.

* Fvwm3 version (run: `fvwm3 --version`)

Current git master:
```
# fvwm3 --version
fvwm3 1.0.3 (1.0.2-58-g5114d153)
with support for:  ReadLine, PNG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS

fvwm3 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of fvwm under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

* Linux distribution or BSD name/version

Debian Sid
```
# uname -a
Linux draven 5.10.0-3-amd64 #1 SMP Debian 5.10.13-1 (2021-02-06) x86_64 GNU/Linux
```
* Platform (run: `uname -sp`)
```
# uname -sp
Linux unknown
# grep model /proc/cpuinfo |tail -n1
model name      : Intel(R) Core(TM) i7-4930K CPU @ 3.40GHz
```
## Expected Behaviour

`Prev (CurrentPage, AnyScreen) Focus` should cycle between windows on any screen of the current page,
but not focus any windows on other pages.

## Actual Behaviour

`Prev (CurrentPage, AnyScreen) Focus` will include maximised windows on adjacent pages in it's focusing.
`Prev (CurrentPage) Focus` does not include any windows on adjacent pages.
Windows which are 1px away from the page border do not become focused (see comments in attached config.mwe.txt),
so "maximizing" a window to less than the full screen size seems to work around this inappropriate focusing.

## Enabling logging

I've attached a log file, but it doesn't correspond precisely to the reproduction steps below.
If you need one which matches better, i'll try.

As an aside, clicking on the file `Attach files` bar and navigating to a file (i haven't tried other methods)
doesn't allow me to upload the logfile without renaming (as `.log` is an unsupported suffix).

## Steps to Reproduce

How can the problem be reproduced?  For this, the following is helpful:

I've attached a MWE config file. After starting with this file, 
1. create a couple of xterms (right mouse menu),
2. mouse to the page below
3. create another xterm
4. maximise this xterm (`Alt-Enter` while focused)
5. mouse back up to the top page
6. `Alt-Tab` to switch between xterms, and get drawn back to the lower page's xterm.
7. go back and confirm that focusing is correct when the third xterm is not maximized.

* Does the problem also happen with Fvwm2?

No.

## Does Fvwm3 crash?
 
No.

## Extra Information

[config.mwe.txt](https://github.com/fvwmorg/fvwm3/files/6027060/config.mwe.txt)
[fvwm3-output.log.txt](https://github.com/fvwmorg/fvwm3/files/6026978/fvwm3-output.log.txt)

**Comment by ThomasAdam** [comment]
Hey @taobert 

Hmm.  Can you check `ta/gh-443` and let me know if that fixes things?

**Comment by taobert** [comment]
Looks good.
Love ya work.:)

**Comment by taobert** [comment]
Somewhat as an aside, i see in `dev-docs/NEW-COMMANDS.md` the lines:
```
Desktops are linear in their arrangement.  There is no concept of pages within
a desktop (as there is with FVWM2).
```

Will `DeskTopSize` be disappearing?

**Comment by ThomasAdam** [comment]
Hi @taobert 

No -- that's just some ideas, and I forget now why I mentioned it.

**Comment by ThomasAdam** [comment]
Hi @taobert 

I forgot to mention, your `MyMaximize` function can be replaced with the builtin command `Maximize fullscreen` so you don't need to mess with removing window decorations, etc.
