### ISSUE TITLE
DesktopSize 1x1 is not respected

### ISSUE THREAD

**Issue by mkarmona** [fvwmorg/fvwm3#45]
`DesktopSize 1x1` configuration is not respected and the mouse can still freely move on edges. My fvwm3 configuration is accessible [here](https://github.com/mkarmona/rc/blob/master/.fvwm/config#L148) and I am currently using _Fvwm3 master branch_.

**Comment by ThomasAdam** [comment]
Hi,

Thanks.  Please use the `ta/gh-22` branch -- you might have more success there.  Let me know if you're still having problems.  I know it's not working correctly on `master` at the moment.

**Comment by mkarmona** [comment]
@ThomasAdam , it is now working, thanks.
