### ISSUE TITLE
Actions from a pinned menu are triggered by mouse move instead of mouse release

### ISSUE THREAD

**Issue by mrtycho** [fvwmorg/fvwm3#456]
## Upfront Information

Version: fvwm3 1.0.3 (1.0.2-99-g3c32c16d)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS

Distribution: 
Manjaro Linux

Kernel: 
Linux nuc 5.4.100-1-MANJARO #1 SMP PREEMPT Tue Feb 23 15:31:04 UTC 2021 x86_64 GNU/Linux

## Actions to reproduce
- Open a menu (with a menu title, e.g. the Fvwm menu of the default config)
- Middle-click its menu title to pin the menu. The menu receives a window decoration
- Left-click on a menu item of the pinned menu to trigger its action (e.g. launch an application)

## Expected Behaviour

- The action of the menu item is triggered the same way as with an unpinned menu and is started when the left mouse button is released

## Actual Behaviour

- The action is triggered when the mouse cursor is moved outside the window of the pinned menu after clicking on the entry. Only releasing the left mouse button has no effect.
- The problem only affects pinned menus

## Enabling Logging

fvwm3 doesn't crash and there is no hint in the log file ~/.fvwm/fvwm3-output.log when the menu was pinned and the action was triggered.

## Extra Information
- I was able to reproduce the bug using the default configuration of fvwm3.
- The behaviour is as expected when I use fvwm2 together with the same config.

**Comment by ThomasAdam** [comment]
Hi @mrtycho,

This also happens with fvwm2.

Can you `git bisect` the commit which introduces this?

**Comment by mrtycho** [comment]
Hello @ThomasAdam 
 
Yes, you are right. I checked again using fvwm2 2.6.9 using Manjaro and with version 2.6.7 on OpenSuse Leap and it also happened. In the default config of OpenSuse ManualPlacement is used and so the problem was not that obvious. I will check some older versions of fvwm2.

**Comment by ThomasAdam** [comment]
@mrtycho 

Please can you try the `ta/gh-456` branch and let me know if this fixes the issue for you?

Thanks.

**Comment by mrtycho** [comment]
@ThomasAdam 
ok, this fixes the issue: the programs now launch like using unpinned menus. However, some programs seem to ignore my keyboard input with this version - even with unpinned menus or when started . If I e.g. start a xterm  I'm unable to write into it.  In Emacs, menus do not show up any more.

**Comment by ThomasAdam** [comment]
Hi @mrtycho 

Apologies -- the keyboard was still being grabbed.  Please pull from the same branch, and try again?

Thanks for testing this!

**Comment by mrtycho** [comment]
hi @ThomasAdam 
I think it is working now with your last change. I did some testing and I didn't find any problems. It also works with multiple pinned menus. 
Thank you very much!
