### ISSUE TITLE
The restart process does not restore custom window colorsets

### ISSUE THREAD

**Issue by mkarmona** [fvwmorg/fvwm3#46]
I do not use window titles so when I _stick_ a window I change its active and inactive colorsets to recognise it. The applied function is
```
DestroyFunc StickAndColor
AddToFunc StickAndColor
+ I ThisWindow (!Sticky) Stick
+ I TestRc (Match) ThisWindow WindowStyle BorderColorset 20, HilightBorderColorset 21
+ I TestRc (Match) Break
+ I ThisWindow (Sticky) Stick
+ I TestRc (Match) ThisWindow WindowStyle BorderColorset 3, HilightBorderColorset 4
```
After having some sticky windows working as expected I trigger the Fvwm restart action and the applied colorsets are not there anymore, sticky status keeps applied though. 
1. Should I expect this to happen? 
2. Is there a more appropriate way of implementing this behaviour?

**Comment by ThomasAdam** [comment]
Hi,

WindowStyles don't persist across restarts. Suggest you use either FvwmEvent or InitialMapComnand style.
