### ISSUE TITLE
FvwmEvent does not contain the event stick and destick

### ISSUE THREAD

**Issue by mkarmona** [fvwmorg/fvwm3#47]
Following previous [recommendations](https://github.com/fvwmorg/fvwm3/issues/46), I was unable [capturing](https://github.com/fvwmorg/fvwm3/blob/master/modules/FvwmEvent/FvwmEvent.c#L113) events of the type `stick`. I guess this can be unified with [another open issue](https://github.com/fvwmorg/fvwm3/issues/26).

**Comment by ThomasAdam** [comment]
Yes you can.  When you change certain window properties, a `ConfigureWindow` packet is send to all modules.  You can use FvwmEvent and the `configure_window` directive to inspect the windows which changed as a result of this.
