### ISSUE TITLE
Moving shaded windows across screens

### ISSUE THREAD

**Issue by lgsobalvarro** [fvwmorg/fvwm3#473]
* Fvwm3 version (run: `fvwm3 --version`)
1.0.3 (1.0.2-99-g3c32c16d)

* Linux distribution or BSD name/version
OpenSUSE Tumbleweed

* Platform (run: `uname -sp`)
Linux x86_64

## Actual Behaviour

I moved a shaded window from Screen 1 (Main, edp) to Screen2 (hdmi-0-a), and then unshaded it. The window was lost. 

Alt-tabbing placed it again where it was originally placed on Screen2

## Steps to Reproduce

1. Shade a window
2. Move Shaded window from Screen 1, to Screen 2
3. Unshade window.

**Comment by ThomasAdam** [comment]
The steps reproducing this are more subtle:

1. Set `DesktopSize 3x3`
2. Set `DesktopConfiguration per-monitor`
3. Make each monitor have a separate desktop to one another
4. Move to the first screen, random page
5. Open a window - shade it.
6. Move it to the second monitor
7. Unshade it.

Problem occurs.

**Comment by lgsobalvarro** [comment]
Yes, you are right. I forgot to mention a couple of things. I'll clarify then:

1. DesktopConfiguration is set as per-monitor
2. DesktopSize is set to 2x8
3. Only one desktop (0) is being used 

Further testing has shown me that the issue presents itself when the page where the window is moved is different of 0,0.
When the window is unshaded it seems to move to 0,0, however the window does not look as expected. 
![Screenshot_20210410_133926](https://user-images.githubusercontent.com/1160397/114281186-8b24f800-9a02-11eb-8adc-ef92fb0b5548.png)

Shading and unshading again seems to fix the problem.

My config has not changed much since last time I shared with you.

Also: Moving a shaded window from Screen2 to Screen1 and unshading it do not cause this problem.

**Comment by ThomasAdam** [comment]
Hi @lgsobalvarro 

Thanks.  Please can you try the `ta/gh-473` branch -- I think the code there fixes this issue?

**Comment by lgsobalvarro** [comment]
It works now. I can't reproduce this anymore after trying ta/gh-473
