### ISSUE TITLE
Font shadow offset miscalculated

### ISSUE THREAD

**Issue by NsCDE** [fvwmorg/fvwm3#475]
Hi ... playing around and find things ...

* Fvwm3 version: fvwm3 1.0.3 (1.0.2-109-g42414a3f)

* Linux distribution: Fedora 33

* Platform: Linux x86_64

## Expected Behaviour

Thin font shadow as with fvwm2 and fvwm3 versions older than 1. 1. 2021.

## Actual Behaviour

Font shadow has offset of 1-2 cm instead of 1 mm. (see pictures)

## Steps to Reproduce

1. Start NsCDE 1.1 or current master with fvwm3 master
2. Launch Style Manager main window and see shadows

Actual configuration is this:

It is in lines 41 and 42 of /opt/NsCDE/lib/scripts/StyleMgr but it is composed of variables and hard to read. The final result is:

`Shadow=2 0 SE:xft:DejaVu Sans:Medium:Book:size=9:antialias=0`

Changing font does not resolves this.

* Does the problem also happen with Fvwm2?

No

## Does Fvwm3 crash?

No

## Extra Information

* Anything else we should know?

Looks like this bug is introduced with d7a2eb625aac2b82ce70f493bf8c625be26aee50 or 070f35547522c30b87e922f5fe2344583ffa3880 or b92b5201eac2c1962beb367f10e757ca85e07c39 because it looks normally if I checkout some commit before d7a2eb625aac2b82ce70f493bf8c625be26aee50.

![StyleMgr-Good](https://user-images.githubusercontent.com/48650374/114320384-07f4c680-9b16-11eb-9eb1-863f2ace3a94.png)
![StyleMgr-bad](https://user-images.githubusercontent.com/48650374/114320386-0925f380-9b16-11eb-8c75-39d0cbdc7bc8.png)

**Comment by ThomasAdam** [comment]
@mikeandmore,

Can you take a look at this, please?

**Comment by mikeandmore** [comment]
Does this happen without the shadow?

**Comment by NsCDE** [comment]
> Does this happen without the shadow?

No.

**Comment by mikeandmore** [comment]
I see. I'll take a look at this tonight or tomorrow.
