### ISSUE TITLE
fvwm/session.c has left FVWM_SM_DEBUG_FILES enabled

### ISSUE THREAD

**Issue by pm215** [fvwmorg/fvwm3#480]
In fvwm/session.c the debug definition FVWM_SM_DEBUG_FILES is defined, which means that whenever it saves or reloads window states it copies state files into /tmp/fs-save and /tmp/fs-load directories.

This seems to me like an accidentally left-enabled bit of debug (it was enabled in  commit 974902aeb39c275 in 2016, and that commit's commit message doesn't mention enabling the debug as a deliberate choice).

Should the #define be commented out like the other FVWM_SM_DEBUG* lines ?

(I noticed this because the system() calls in the debug code trigger a compile warning because they don't do anything with the return value from system().)

**Comment by ThomasAdam** [comment]
Hi @pm215 

It's a little dirty, but very useful for debugging, which is why I probably left it enabled all those years ago.  We could probably harden the `system()` check though, but I rather this stays.

**Comment by pm215** [comment]
I'd definitely rather my window manager wasn't writing debug info to fixed-filename temporary files in /tmp. If these have a good purpose they ought to be somewhere fvwm-specific, surely ?

**Comment by ThomasAdam** [comment]
Then we should change it to be relative to `FVWM_USERDIR`.

**Comment by ThomasAdam** [comment]
I'm just going to remove this for now -- if we ever need to do anything else, we can code for that.
