### ISSUE TITLE
Special characters (umlauts) are sometimes not displayed correctly in the window title

### ISSUE THREAD

**Issue by mrtycho** [fvwmorg/fvwm3#482]
* Fvwm3 version (run: `fvwm3 --version`)
fvwm3 1.0.3 (1.0.2-103-g8f3692fc)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS

* Linux distribution or BSD name/version
Linux nuc 5.10.32-1-MANJARO #1 SMP Wed Apr 21 14:54:10 UTC 2021 x86_64 GNU/Linux

* Platform (run: `uname -sp`)
Linux unknown

## Expected Behaviour

Launch a program that has an umlaut in its name, e.g. pavucontrol = Lautstärkeregler (German)
"Lautstärkeregler" is shown in the title of the new window.

## Actual Behaviour

Instead of the umlaut "ä" there is a different character shown:
![shot1](https://user-images.githubusercontent.com/5375363/117181766-e1087800-add5-11eb-8a51-9a063f9f8e63.png)

Name and Icon Name are using a wrong character.

## Steps to Reproduce

For this bug report I used the default configuration of fvwm3 and I'm using LANG=de_DE.UTF-8

* Does the problem also happen with Fvwm2? No, I didn't notice this problem with older versions.

Include your configuration with this issue.
=default configuration of fvwm3

## Does Fvwm3 crash?
No

## Extra Information

* Anything else we should know?
I found a kind of a workaround: I did the following changes to the config

`Style * Font      "xft:Sans:size=8:antialias=True"`
`Style * IconFont  "xft:Sans:Bold:size=8:antialias=True"`
`Style * TitleFormat %i\n`
`# Style * !Icon`

This results in the following
![shot2](https://user-images.githubusercontent.com/5375363/117182693-f7630380-add6-11eb-8eb1-89e2a14371f7.png)

After this the icon name now looks as expected and so I can use %i as TitleFormat.

* In a web browser or file manager that shows a path with umlauts in the title bar, the problem does not initially occur. But after a fvwm restart, the title is also displayed incorrectly. Maybe only the initial window title is affected.

* I don't know if this problem also occurs with other special characters and other languages, using ä,ö,ü,ß I run into this problem.

**Comment by ThomasAdam** [comment]
Hi @mrtycho 

What locale settings are you using?  For example:

```
% locale
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=en_GB.UTF-8
```

**Comment by mrtycho** [comment]
Hi @ThomasAdam 

my locale settings are
```
LANG=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES=de_DE.UTF-8
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```

**Comment by ThomasAdam** [comment]
Hi @mrtycho 

If you:

 `export LC_ALL=de_DE.UTF-8` in your `.xsession` (or however you start X11), *PRIOR* to starting `fvwm3`, does that help at all?

**Comment by mrtycho** [comment]
Hi @ThomasAdam 

ok, I added the export to the .xprofile file and after I restarted X11 LC_ALL was set to de_DE.UTF8. Unfortunatly this didn't help.
(To be on the safe side, I started fvwm3 again with --replace.)

**Comment by lgsobalvarro** [comment]
I think @MasterP-theGu mentioned this issue some time ago in IRC, too.

**Comment by MasterP-theGu** [comment]
Yes, I did. Funnily enough, it was the Lautstärkeregler, too, that made me realise the problem.
Here's an extract from the IRC log to have things together in one place, also for the screenshots.

Those issues had come up on a RaspberryPi 4 with ArchlinuxARM and - as far as fonts and locales are concerned - standard config.
The same issue of the missing "ä" and Umlauts can be seen on my standard Intel based PC running OpenSuSE 15.2 and using the self-same config as on the Pi.

It might be a question of where the text in the window title comes from. As you can see, if it's the name of the programme, the Umlauts don't work, if it's the name of a page opened in Firefox, Umlauts do work. Are there different algorithms involved?



>  <Master_P_the_Gu> Hi all, I wonder if this is an fvwm issue or if I've ruined some code-config somewhere else? One window is qt, the other is gtk, in both cases the letters "ärk" are missing. https://i.imgur.com/U51aGWk.png

>  <Master_P_the_Gu> To confuse the idea of font (sorry!) https://i.imgur.com/2gE4pkD.png
 <Master_P_the_Gu> The capital "Ö" works fine, the small "ö" doesn't. Would that still make sense with font/charmap issues? 

LC_ALL is empty as a standard. Now that I've read this, I'll try my best setting it in my .Xresources. Will come back here with results.

**Comment by ThomasAdam** [comment]
Might be the same as #684
