### ISSUE TITLE
Default Configuration for Transient Windows

### ISSUE THREAD

**Issue by phileimer** [fvwmorg/fvwm3#484]
The out of the box configuration for transient windows does not provide the obvious behavior we could expect, i.e:
* no border on splash screens (for example Eclipse or Google Earth)
* correct management of Firefox/Thunderbird with/without title bar configuration
* close button displayed on transient windows

Everything is already present as Fvwm configuration options to fine tune transient windows.
On my opinion, only defaults are to be modified.

Here is the minimal configuration I struggled to find to have correct transient windows:
   Style * MwmDecor, DecorateTransient, HintOverride
   ButtonStyle 2 - Clear

Button 2 being the close button on my system.

@ThomasAdam: I let you decide whether it's worth modifying the default configuration this way.

**Comment by ThomasAdam** [comment]
Hi @phileimer 

I think this is one of those areas where this is exactly what a user would need to do, beyond what the default provides.  I appreciate the syntax is alien and not intuitive, but what you have works fine for you, and I'm inclined to leave the matter there.

**Comment by phileimer** [comment]
I agree.
At least my feedback may help others to configure their system.
