### ISSUE TITLE
Ideas for new default config

### ISSUE THREAD

**Issue by MasterP-theGu** [fvwmorg/fvwm3#49]
My primary screen is the left one and having the RightPanel in the left margin has made a lot of sense to me for quite a while. So I thought, others whose primary screen is the left one might have similar feelings. And as fvwm3 might want to come with a new/updated standard config, I thought we could have a collection of ideas for this fvwm3-standard-config here. As I can only start this from a user perspective, I shall suggest _results_ rather than _ways / codes_, but if you have code, I'm sure nobody will be disappointed with it being shared here.

**Make standard panel LeftPanel**
or have a switch in the config to choose between left or right margin
currently: `*RightPanel: Geometry 120x$[vp.height]-0+0 `**v  new** `*LeftPanel: Geometry 120x$[vp.height]+0+0`
On a switch-level I could think of something like `set panel = left`
or, which could be discussed, have a general switch in a top-section of the config as to which screen is the main one and/or whether we have global or per-monitor configuration and have the position of the panel and possibly all kinds of other things depending on this, so something like
`set primary screen = left -> panel=left` **v** `set primary screen = right -> panel = right`

**Comment by ThomasAdam** [comment]
Hi,

Closing this as there's nothing else to do that can't be solved through editing the fvwm config.
