### ISSUE TITLE
Documentation: man pages should honour `program-transform-name`

### ISSUE THREAD

**Issue by ThomasAdam** [fvwmorg/fvwm3#492]
In order to make `fvwm3` installable alongside `fvwm2`, one should be able to make use of autotools' renaming mechanisms (https://www.gnu.org/software/automake/manual/automake.html#Renaming).  This should apply to manpages as well.

In speaking with @somiaj there are a few cases where this applies:

```
# ls ~/tmp/fvwm2/bin/
Fvwm2Command
fvwm2-bug
fvwm2-convert-2.6
fvwm2-menu-directory
fvwm2-menu-xlock
fvwm2-root
xpmroot
fvwm2
fvwm2-config
fvwm2-menu-desktop
fvwm2-menu-headlines
fvwm2-perllib
fvwm22


# ls ~/tmp/fvwm2/share/man/man1/
Fvwm2Command.1
FvwmAnimate.1
FvwmAuto.1
FvwmBacker.1
FvwmBanner.1
FvwmButtons.1
FvwmConsoleC.pl.1
FvwmConsole.1
FvwmCpp.1
FvwmEvent.1
FvwmForm.1
FvwmIconMan.1
FvwmIdent.1
FvwmM4.1
FvwmPager.1
FvwmPerl.1
FvwmProxy.1
FvwmRearrange.1
FvwmScript.1
fvwm2-bug.1
fvwm2-config.1
fvwm2-convert-2.6.1
fvwm2-menu-desktop.1
fvwm2-menu-headlines.1
fvwm2-menu-xlock.1
fvwm2-perllib.1
fvwm2-root.1
fvwm2.1
fvwm22.1
xpmroot.1
```

**Comment by somiaj** [comment]
The above shows what `--program-transform-name='s/vwm/vwm2/'` does in fvwm2.

This shows what `--program-transform-name='/vwm[^3]/ s/vwm/vwm3/'` does in fvwm3.

```
# ls ~/tmp/fvwm3/bin/
FvwmCommand
fvwm3
fvwm3-config
fvwm3-convert-2.6
fvwm3-menu-desktop
fvwm3-menu-directory
fvwm3-menu-xlock
fvwm3-perllib
fvwm3-root

# ls ~/tmp/fvwm3/share/man/man1/
FvwmAnimate.1
FvwmAuto.1
FvwmBacker.1
FvwmButtons.1
FvwmConsole.1
FvwmEvent.1
FvwmForm.1
FvwmIconMan.1
FvwmIdent.1
FvwmMFL.1
FvwmPager.1
FvwmPerl.1
FvwmPrompt.1
FvwmRearrange.1
FvwmScript.1
fvwm3-menu-directory.1
fvwm3-menu-xlock.1
fvwm3-perllib.1
fvwm3.1
fvwm-config.1
fvwm-convert-2.6.1
fvwm-menu-desktop.1
fvwm-root.1
```

As seen, the binary `FvwmCommand` and the manpages `fvwm-{config,convert,menu-desktop,root}` are no longer changed by this configuration option.

**Comment by somiaj** [comment]
While at it, might want to check/ensure that the options `--program-prefix=PREFIX` and `--program-suffix-SUFFIX` also work on the files listed above.
