### ISSUE TITLE
AnimatedMove

### ISSUE THREAD

**Issue by googreygreen** [fvwmorg/fvwm3#513]
OS ArchLinux, Manjaro and Garuda
version fvwm3: 1.0.3 (1.0.2-132-g5f1cf518)

I switched to fvwm3 and the construction for animation stopped working.

```
DestroyFunc StartDashBoard
AddtoFunc StartDashBoard
+ I FvwmButtons DashBoard
+ I Wait DashBoard
+ I Next (DashBoard) State 1 True

DestroyModuleConfig DashBoard:*
*DashBoard: Geometry 920x120+0+0
*DashBoard: Colorset 10
*DashBoard: Rows 120
*DashBoard: Columns 920 
*DashBoard: Frame 0
*DashBoard: Font "xft:Sans:Bold:size=10:antialias=True"
*DashBoard: (120x45, Icon "fvwm-logo-small.png", Frame 0)
*DashBoard: (Size 360x120, Frame 0, Colorset 0, Swallow "FvwmPager" 'Module FvwmPager' )
*DashBoard: (120x45, Swallow DateTime 'Module FvwmScript FvwmScript-DateTime',\
    Frame 0)

DestroyFunc  ShowTheDashBoard
AddToFunc    ShowTheDashBoard
+ I None (DashBoard) StartDashBoard
+ I Next (! DashBoard State 1) AnimatedMove 0p 0p
+ I TestRc (Match) All (DashBoard) Focus
+ I TestRc (Match) All (DashBoard) WarpToWindow 50 0 
+ I TestRc (NoMatch) All (DashBoard) AnimatedMove 0p -$[vp.height]p 
+ I Next (DashBoard) State 1 toggle

Style DashBoard WindowListSkip, BorderWidth 0, !Handles, Sticky, !RoundedCorners, !Title, ResizeHintOverride
Key escape A 4 ShowTheDashBoard
```

It should show the panel (FvwmButton) and hide it on hotkey.
In the previous version it showed and disappears, the re-call grabs a random window and hides it
After updating fvwm3 stopped hiding windows. Now he drags windows at coordinates 0p 0p and stopped swallowing FvwmPager

**Comment by ThomasAdam** [comment]
Hi @googreygreen 

Please can you try the `ta/gh-513` branch in git, and let me know if this fixes your problem?

Thanks,
Thomas

**Comment by ThomasAdam** [comment]
I'll merge this to `master` now -- do try that instead.  I've had this running all day without any hiccups, so do start a new bug report if there's anything else broken.
