### ISSUE TITLE
Set min. size for windows shown in pager

### ISSUE THREAD

**Issue by lgsobalvarro** [fvwmorg/fvwm3#542]
## Describe the new feature
Due the resent changes made to Pager in FVWM3 (Master branch), the minimum size for windows shown in the pager was set to 5px. This can not be changed in the config, nor is there a way to tell Pager not to show selected windows in a similar fashion as it can be done with IconMan and WinList. 

## How might fvwm3 need to change?
Add a feature that allows you to control the minimum size of windows shown in pager. And a way to tell pager to ignore a particular window as can be done with WinList and IconMan via `WindowListSkip`

## Can this be achieved through scripting?
Not right now. The minimum size can not be changed. 
Nor do I know a way to tell pager to Ignore itself or a particular window, or windows when their state is Foo.

**Comment by somiaj** [comment]
Check out js/gh-541. I have added a `WindowMinSize` option you can use to set the minimum size of a window (instead of having a hard coded default).

There is already a `UseSkipList` option you can use to have the pager ignore windows with the `WindowListSkip` style set.
