### ISSUE TITLE
EdgeLeaveCommand don't work or need a page change to work

### ISSUE THREAD

**Issue by domichel** [fvwmorg/fvwm3#543]
## Upfront Information
fvwm3 1.0.4 (1.0.3-16-g68579fe8)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS

gentoo ~amd64

Linux AMD E-450 APU with Radeon(tm) HD Graphics

## Expected Behaviour
The TopPanelOnTop function toggle the TopPanel between the top and bottom layers.
'EdgeLeaveCommand Top TopPanelOnTop' should automatize that toggling when the mouse leave the top edge of the screen.

## Actual Behaviour
When put as it into the config file, the EdgeLeaveCommand do nothing.
When started from the StartCommand or FvwmPrompt, a page change is needed for it to work.

**Comment by domichel** [comment]
[config_EdgeLeaveCommand.txt](https://github.com/fvwmorg/fvwm3/files/6673670/config_EdgeLeaveCommand.txt)

**Comment by ThomasAdam** [comment]
Hi @domichel 

Please try out the `ta/gh-543` branch which should fix the issue you've described.

**Comment by ThomasAdam** [comment]
I've merged this to `master` now -- so please test this there, and open up a new issue if there's anything broken.
