### ISSUE TITLE
Move X Y Warp doesn't move pointer to window.

### ISSUE THREAD

**Issue by somiaj** [fvwmorg/fvwm3#551]
The Warp option in the Move command is not correctly warping the pointer to the top left corner of the window it moves.

The pointer is moved, but not to the correct location. I did not see any pattern in how the pointer was moved.

Also if the window doesn't move, the pointer isn't moved even if it is not on the window (if you say run the same Move command twice in a row, the pointer isn't moved the second time).

My test examples were things like

```
Move -10p -10p Warp
Move +10p -10p Warp
```

**Comment by ThomasAdam** [comment]
Yeah -- try it out on fvwm2, do you see the same thing?

**Comment by somiaj** [comment]
I am also able to reproduce this in fvwm2.

After a few more tests it doesn't appear to move the pointer to where the window was. Instead it appears to move the pointer by the exact same dx and dy the window moves. So if the window moves 100p left and 10p up, it moves the pointer in the same way from the current pointer's position. This would also explain why the pointer doesn't move if the window doesn't move.
