### ISSUE TITLE
Man Pages Cleanup

### ISSUE THREAD

**Issue by lgsobalvarro** [fvwmorg/fvwm3#554]
## Upfront Information

FVWM3 man page mention different modules like FvwmM4, FvwmCpp, FvwmBanner and so on that are no longer present. 
A clean up is required.
This is also probably needed for the man pages for some of the modules too.

**Comment by ThomasAdam** [comment]
Yes, I agree.

Additionally, we should audit the formatting of the main `fvwm.adoc` file, as I suspect there's a few formatting errors.
