### ISSUE TITLE
Games full-screen broken with Steam Proton

### ISSUE THREAD

**Issue by sebaro** [fvwmorg/fvwm3#574]
With Proton 5.13 games can’t enter full-screen correctly. It’s fine with Proton 5.0. Also fine with other WM and DE.

My display resolution is 1280x1024 and game resolution is set to 800x600.
The game doesn't start in full-screen but windowed mode (maximized).
Also the mouse position is not detected correctly, I have to click above game's clickable items/buttons.

If I change the game resolution to 1280x1024, the game flickers on start and it gets in full-screen but not correctly, I can see parts of the desktop. Toggling full-screen off/on in game setting fixes this issue but I have to do it every time I start the game.

Tried 5.13-5, 5.13-6, 6.3-5.
Proton 5.0 is working fine.

Games:
The Witcher 1 (20900)
Railroad Tycoon II: Platinum (7620)

My config https://pastebin.com/Pte0ciWb

>fvwm3 --version
fvwm3 1.0.4 (1.0.3-111-gc5dda21c)
with support for:  XPM, PNG, SVG, Shape, XShm, SM, XRandR, XRender, XCursor, XFT, NLS

**Comment by ThomasAdam** [comment]
Hi @sebaro 

Is there something I can download and try to reproduce this?

Can you also capture the output from `xprop` on the window when it's claiming to be in a fullscreened state?

**Comment by sebaro** [comment]
Any free game without Linux support.

Attached xprop for the steam client and 2 games.
[steam.txt](https://github.com/fvwmorg/fvwm3/files/6795774/steam.txt)
[game.txt](https://github.com/fvwmorg/fvwm3/files/6795775/game.txt)
[game2.txt](https://github.com/fvwmorg/fvwm3/files/6795793/game2.txt)

**Comment by ThomasAdam** [comment]
Hi @sebaro 

Thanks.  I think all you need to do is add the following to your config:

```
Style * MWMFunctions, MWMDecor, HintOverride
```

**Comment by sebaro** [comment]
Thanks Thomas,
This fixes the issue for one game I've tried but not for Railroad Tycoon 2. The flickering is gone but the full-screen is still not correct. It seems like the titlebar and borders are just hidden not removed, because I can see the desktop where the titlebar was and the mouse position is delayed with the titlebar height (attached screen capture).

![rt2](https://user-images.githubusercontent.com/12168595/125249322-c8e53580-e2fd-11eb-9e26-b1af63fa8d93.png)
[rt2.txt](https://github.com/fvwmorg/fvwm3/files/6799475/rt2.txt)

Also the "ResizeHintOverride" style is required for The Witcher 2 which is a native game.

**Comment by lgsobalvarro** [comment]
This is a kind-of common issue with games in fvwm.

For what I have noticed it has to do mostly with the way the game tells fvwm to manage the window. For instance: Crusader Kings 2 will set the window size to 100 100, but will not enter full-screen. Fvwm does not take that as a real maximize/full-screen command. (That's my theory anyhow).

What I do in this cases is I define a stile for the game. Usually: `Style foo !Title, NoHandles, BorderWidth 0` get the job done. You could also add `maximized fullscreen` if needed.

**Comment by lgsobalvarro** [comment]
You would have to use a Function for that, I think. However I would suggest you to first use FvwmIdent to make sure the window is actually maximized (check that the width and height match your screen resolution).

Looking at the Railroad Tycoon 2  screenshot... It makes me thing perhaps the resolution the game is set to does not match your screen, hence the "extra" space. If that's not the case, and the window is changing it's start position of something (take a look at FvwmIdent for that) , you could add to the style `!UsePPosition`. If the window resizes after the game loads (playing low-res intro videos or so) you can add `!UseUSPosition, FixedPPosition` to your style (it will also work with `!UsePPosition` ). 

As I said some games can be troublesome  and require a bit of "try and error" to make them behave as expected.

**Comment by sebaro** [comment]
I tried with this, it doesn't help:
>Style "steam_app_7620" !Title, !Handles, !Borders, !UsePPosition

This is the window info, I assume the geometry is wrong (y=32):
![screenshot-2021-07-15 09:48](https://user-images.githubusercontent.com/12168595/125742289-cc79b55a-86f0-4d02-8392-4ff4089449ce.png)

**Comment by lgsobalvarro** [comment]
Seems to me that is the case.

I don't own Railroad Tycoon 2 so I can't try to reproduce this issue. So all my suggestions have been guess work.
You could force the window to start at geometry 0 0.

Also check how `EwmhBaseStruts` is set. It may be set to restrict 32 pixels on the top of the screen. I don't think this is the case since `FullScreen` _should_ ignore `EwmhBaseStruts` Still is worth checking.

You could also use `move shuffle up` that should do it for you.

**Comment by sebaro** [comment]
I have EwmhBaseStruts:
```
InfoStoreAdd mEdgeLeft "10"
InfoStoreAdd mEdgeRight "10"
InfoStoreAdd mEdgeTop "10"
InfoStoreAdd mEdgeBottom "50"
EwmhBaseStruts $[infostore.mEdgeLeft] $[infostore.mEdgeRight] $[infostore.mEdgeTop] $[infostore.mEdgeBottom]
```
But changing these doesn't help, as you said are ignored in full-screen mode.

Yes, the game crashes when switching desktops or apps.
I tried with different setting in winecfg, with a virtual desktop of any resolution (1280x1024, 800x600) the game's window is always 1024x768, and in normal mode not full-screen.

Is there a way to set/force geometry on full-screen windows?

For Move:
```Key M   A   CM   Move 0 0 ewmhiwa```
This works.

Thanks lgsobalvarro

**Comment by ThomasAdam** [comment]
Hi @sebaro 

I can't install the steam client, so wouldn't be able to reproduce this.

My time is in high demand elsewhere at the moment, but some things which I've noticed from the FvwmIdent information you've provided are:

1.  The window has `Static` gravity.  This is unusual (although perfectly legal in terms of the ICCCM/EWMH) because the window is resized relative to the frame and the root window.  I think this is arguably a "bug" in the steam client.

Have a look at setting one of the following:

```
Style <steam_client_class> MoveByProgramMethod IgnoreGravity
```

or:

```
Style <steam_client_class> MoveByProgramMethod UseGravity
```

If none of these help, you're out of luck.

I know you've been suggested `Move 0 0 ewmhiwa".  This because of the Static gravity field.  Perhaps you should consider:

```
Style <steam_client_class> InitialMapCommand Move 0 0 ewmhiwa
```

... to force this, but only in the case where `MoveByProgramMethod` fails to help.
