### ISSUE TITLE
"GeometryWindow Hide" doesn't work

### ISSUE THREAD

**Issue by slalik** [fvwmorg/fvwm3#589]
When I use `GeometryWindow Hide` the geometry window is shown. 

`GeometryWindow Show Never` really hides the window.

`GeometryWindow Hide Move` and `GeometryWindow Hide Resize` hide the window during move or resize (as they should).

**Comment by somiaj** [comment]
@slalik I believe I have fixed the issue, check out js/gh-589

**Comment by slalik** [comment]
Yes, the fix works. Thank you!
