### ISSUE TITLE
Bundeled golang dependeices for FvwmPromt are discouraged in multiple distributions.

### ISSUE THREAD

**Issue by somiaj** [fvwmorg/fvwm3#594]
Although bundling the depends in `bin/FvwmPrompt/vendor` helps with building on the many systems used by fvwm, this is discouraged by some major distributions.

https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling
https://fedoraproject.org/wiki/Bundled_Libraries

https://wiki.debian.org/EmbeddedCopies
https://www.debian.org/doc/debian-policy/ch-source.html#s-embeddedfiles

https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies

For instance, Debian policy would prefer I remove `bin/FvwmPrompt/vendor` from the source tarball, and then build against system libraries (which might mean packaging them first).

Some thoughts,

1) At a minimum there should be a configuration flag to use/not use the bundled libraries, to allow FvwmPrompt to be built using system libraries instead.

2) Provide `bin/FvwmPrompt/vendor` as a separate tarball from the release tarball so that those who want can use them and a configure flag to build with those libraries over the system libraries.

**Comment by ThomasAdam** [comment]
Well, that's understandable. However, this is a packaging problem downstream of fvwm.

You can already affect golang's build via environment variables if needed.
