### ISSUE TITLE
Building FvwmPrompt should also disable FvwmCommand

### ISSUE THREAD

**Issue by somiaj** [fvwmorg/fvwm3#598]
If building FvwmPrompt, FvwmConsole is not built since this will be its replacement. The same should probably be true for FvwmCommand and FvwmCommandS. These modules should not be built (and their manual page should not be installed) if FvwmPrompt is built.

**Comment by ThomasAdam** [comment]
FvwmCommand has already been replaced as a wrapper around `FvwmMFL`.
