### ISSUE TITLE
FvwmButtons fails silently; Fvwm3

### ISSUE THREAD

**Issue by PackRat-SC2018** [fvwmorg/fvwm3#60]
On both Void and ArchLabs, kernel 5.6.x, FvwmButtons does not start.

With the default RightPanel configuration, there is a quick flash (FvwmPager, I think) and then just the wallpaper visible. Sometimes, FvwmIconMan or stalonetray will remain, but not both.

Fvwm3 is functional afterwards, I can start both FvwmPager and FvwmIconMan from FvwmConsole. If I try to start FvwmButtons from FvwmConsole (either the RightPanel or a simple test panel with just FvwmIconMan) no FvwmModule starts, and there is no message in FvwmConsole.

**Comment by ThomasAdam** [comment]
Hi @PackRat-SC2018,

Thanks for the report. Do you have a core file left behind from FvwmButtons?

**Comment by PackRat-SC2018** [comment]
I don't think so. Where would it get dumped?

I started Fvwm again with "fvwm3 -D" - that the correct way to generate the file you need?

**Comment by ThomasAdam** [comment]
Hi,

> I don't think so. Where would it get dumped?
> 
> I started Fvwm again with "fvwm3 -D" - that the correct way to generate the file you need?

Ah, alas `-D` isn't going to help here.

First we need to compile `FVWM3` so that we can get debug output from it, so something like:

```
make clean ; make CFLAGS="-O0 -ggdb" -j4 && sudo make install
```

As for corefiles, you should check that corefiles can be created:

```
ulimit
```

If that returns `unlimited`, we're all set.  if not, you should add this to your shell profile:

```
ulimit -c unlimited
```
and restart X11.

Corefiles will usually be in the CWD for the program you're using, so check `$HOME` for that.

Then it's just a case of installing `gdb` and using it like so:

```
gdb /path/to/fvwm3 ./corefile
(gdb) bt full
```

If you're using `systemd-coredump`, you can use `coredumpctl`, which will plonk you inside gdb, where the command above (`bt full`) will work once more.

Then attach the output here.

**Comment by PackRat-SC2018** [comment]
ulimit returned unlimited. Not sure the gdb command worked as intended. Here is the terminal output:

`[doug@WILLOW-01 .fvwm]$ ls /usr/local/bin
dwm    fvwm-bug          fvwm-menu-desktop    fvwm-perllib  startdwm
fvwm   FvwmCommand       fvwm-menu-directory  fvwm-root     startyaxwm
fvwm2  fvwm-config       fvwm-menu-headlines  slstatus      xpmroot
fvwm3  fvwm-convert-2.6  fvwm-menu-xlock      st
[doug@WILLOW-01 .fvwm]$ gdb /usr/local/bin/fvwm3 ./corefile
GNU gdb (GDB) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/fvwm3...
/home/doug/.fvwm/./corefile: No such file or directory.
(gdb) bt full
No stack.
(gdb) 
`

**Comment by ThomasAdam** [comment]
Hi @PackRat-SC2018,

That's because `corefile` doesn't exist. It's usually called `core`.

Kindly,
Thomas

**Comment by PackRat-SC2018** [comment]
Recompiled Fwm3 on a clean ArchLabs install, and on Void. Used the make command you provided above.

FvwmButtons working as expected on both systems.

**Comment by ThomasAdam** [comment]
Thanks, @PackRat-SC2018!  I'll close this for now then, but if you find anything else, feel free to file another issue, please.
