### ISSUE TITLE
Window placement enhancement

### ISSUE THREAD

**Issue by oredaze** [fvwmorg/fvwm3#600]
I suspect this would be a rather minor thing to implement, but very nice.
The idea is that you use a combination of PositionPlacement Center(for the first one) and MinOverlapPlacement (for the rest).
Openbox does this and it's the way that makes the most sense to me.

**Comment by ThomasAdam** [comment]
Hi @oredaze 

Is this for one type of window, or all? Either way you should be able to do this with something like:

```
Style * InitialMapCommand Foo

DestroyFunc Foo
AddToFunc Foo
+ I None ($[w.class]) Move ....
+ I TestRc (Match) Style .... MinOverlapPlacement
```

**Comment by oredaze** [comment]
It is for all types of windows.
I have tried to make this work based on your example, but I can't. The type of logic that these functions use is kinda confusing to me. It looks to me as if your example tries to `Move` a window if no window exists, which obviously can't happen, and if a window exists it just goes to the `TestRc` line...

Also I am not sure if my explanation was clear enough, so let me paraphrase myself just in case:
The placement of the very first window in an empty desktop should be centered, the second and following ones should use MinOverlapPlacement.

**Comment by ThomasAdam** [comment]
This can be done through conditionals and PipeRead -- I don't think this feature needs adding directly to fvwm3.
