### ISSUE TITLE
Provide an option to box the cursor into a given monitor/rectangle

### ISSUE THREAD

**Issue by somiaj** [fvwmorg/fvwm3#603]
I would like a feature where I could force the mouse cursor to be boxed into a single monitor or a given rectangle that could then be toggled so when using certain apps I can restrict the cursor to that window and not accidentally move out it out.

**Comment by ThomasAdam** [comment]
You can probably use `unclutter` for this.

**Comment by somiaj** [comment]
I don't think `unclutter` would do this, it just hides the mouse, I want to make it so the mouse cannot move outside of a particular area. `xinput --map-to-output` is suppose to help with this, but for my mouse it didn't have any affect because my mouse can move further than 100% of the monitor size, so the transformation matrix just slows down mouse movement, not restrict it.

I think for mice who cannot move beyond the maximum global monitor using `xinput` to set a transformation matrix can be used to restrict the cursor to any rectangle on the desktop. But in my case I need to also tell my mouse driver to never allow positions beyond 100% of the global monitor. If this was possible easy enough in fvwm it would be nice.

**Comment by somiaj** [comment]
I wonder if this could be useful, seems `XFixes` extension includes pointer barriers which can be used to place the barrier into a given rectangle.

http://who-t.blogspot.com/2012/12/whats-new-in-xi-23-pointer-barrier.html

**Comment by somiaj** [comment]
Looking deeper I did find a tool like this that would work.

https://github.com/nogard0/xpointerbarrier

I still think it would be nice to implement this in fvwm, I don't like how that tool is listening for events.
