### ISSUE TITLE
PipeRead when called from a function cannot grab pointer

### ISSUE THREAD

**Issue by BanchouBoo** [fvwmorg/fvwm3#610]
## Upfront Information

* Fvwm3 version: 1.0.4

* Linux distribution: Void Linux (glibc)

* Platform: Linux unknown

## Expected Behaviour

The following function is meant to run a program that lets you select a region on your screen (like slop for example) and move/size the window to that region, but it's unable to capture the pointer. I initially thought the `BusyCursor` wasn't working for some reason, but that's not actually the case. If I run `BusyCursor Read False` in my `StartFunction` then call the `PipeRead` directly in a keybind instead of calling the function it works fine, so presumably something about it being called from a function makes it unable to capture the pointer.
```
DestroyFunc BooxResizeMove
AddToFunc BooxResizeMove
+ I BusyCursor Read False
+ I PipeRead 'boox -w -f "Current ResizeMove %wp %hp %xp %yp"'
```

## Relevant logs

When I run the command this is all I get in the log, seemingly nothing important
```
[1630881980.595227] ewmh_ComputeAndSetWorkArea: monitor 'HDMI-A-0': {l: 0, r: 0, t: 0, b: 0} {x: 0, y: 0, w: 1920, h: 1080}
[1630881980.595260] EWMH_GetWorkAreaIntersection: mon: HDMI-A-0 {ax: 0, ay: 0, aw: 1920, ah: 1080
[1630881980.595266] EWMH_GetWorkAreaIntersection: mon: HDMI-A-0 {x: 0, y: 0, w: 1920, h: 1080
[1630881980.595277] EWMH_GetWorkAreaIntersection: mon: HDMI-A-0 finalising: {x: 0, y: 0, w: 1920, h: 1080}
```

Full logs here: [fvwm3-output.log](https://github.com/fvwmorg/fvwm3/files/7112468/fvwm3-output.log)

**Comment by ThomasAdam** [comment]
Hi @BanchouBoo,

Yes.  This is due to how `PipeRead` blocks execution.   Try:

```
DestroyFunc BooxResizeMove
AddToFunc BooxResizeMove
+ I BusyCursor Read False
+ I Exec 'boox -w -f "Current ResizeMove %wp %hp %xp %yp"'
```

**Comment by BanchouBoo** [comment]
But... I need it to be a `PipeRead`? And like I said, `PipeRead` works fine if I call it directly instead of in a function, the problem is that it can't capture the mouse pointer when I call it from the function specifically, this is also true for `Exec` and `Exec` doesn't do what I need it to do.

**Comment by ThomasAdam** [comment]
@BanchouBoo 

I've been testing this with `xprop` and `slop` which do work.  Can you point me toward this `boox` software, please?

**Comment by BanchouBoo** [comment]
Did some additional testing, it *does* work with `Exec` I just had a quoting issue when I changed it the first time, but I still need it to be a `PipeRead` regardless.
