### ISSUE TITLE
Qt applications opens progressive lower on the screen when restarted

### ISSUE THREAD

**Issue by entropic77** [fvwmorg/fvwm3#614]
* Fvwm3 version: 1.0.5 (1.0.4-16-g3663d42d)

* Linux distribution: Debian 11.0

* Platform: Linux unknown

## Expected Behaviour

Windows that store their position should open at the same spot they were when they quit.

## Actual Behaviour

Every time a Qt application which stores it's position is quit and restarted, it opens 10 pixels further down on the screen. (Or 9 pixels, on my customized configuration.)

## Steps to Reproduce

Start kate, inspect its position with xwininfo. Quit. Start it again and inspect its position again. Also check `~/.config/katerc` or `~/.local/share/kate/anonymous.katesession` (`grep YPosition ~/.config/katerc ~/.local/share/kate/anonymous.katesession`), between restarts and watch it increasing.

The problem happens with Qt 5.15 applications that saves window position when quitting, and restores position when started. For example KeepassXC 2.6.2 and Kate 20.12.2. It worked as expected in Debian 10 with Qt 5.11.

The problem happens with the default configuration, also with a blank config, and fvwm2.

The problem does not appear in some other window managers I tried: openbox, blackbox, twm, xfwm4.

Not sure if related, but a section of the Qt documentation says: "When [the window is decorated], the window shifts towards the bottom/right corner of the screen depending on the size of the decoration frame. Although X provides a way to avoid this shift, some window managers fail to implement this feature." https://doc.qt.io/qt-5/restoring-geometry.html

I haven't seen any gtk-applications yet that has the same problem, except chromium, which opened even farther down, but that might be a different issue. Qterminal is one exception I found of a Qt application that is not affected.

**Comment by ThomasAdam** [comment]
Hi @entropic77 

Can you try each of the following options one at a time to see if they help:

`Style foo MoveByProgramMethod UseGravity`
`Style foo MoveByProgramMethod IgnoreGravity`

Where `foo` is the class name of the window in question.

**Comment by entropic77** [comment]
They did not help unfortunately. Neither for Qt-apps nor Chromium.

**Comment by lgsobalvarro** [comment]
I have also noticed this with QT/KDE Apps. As @entropic77 says this does not happens on other WM (I have tried with e16, wmaker, and kde/kwin).
I have also noticed that the application sometimes takes time to redraw when switching between pages.
I'm using QT 5.15.2+kde222 (meaning QT 5.15.2 with the additional KDE patch, v. 222). I have not tried the styles suggested (yet) but I'll as soon as I'm able and update this post.

**Comment by entropic77** [comment]
A little clarification from my side now that I've experimented some more: Kate did not save it's position on Debian 10 (kate ver 18.08.0), but some apps did, for example Falkon, KeepassXC and Qt designer, which save/restore position correct in Debian 10 (Qt 5.11.3) but wrongly in Debian 11 (Qt 5.15.2).

The fvwm3 version was the same in both tests.

**Comment by ThomasAdam** [comment]
Hi @entropic77 

Well, this appears to be a problem with Qt.  Per their own documentation, they claim:

```
When this happens, the window shifts towards the bottom/right corner of the screen depending on the size of the decoration frame.
```

I can only presume they're referring to the window gravity, and the window receiving a `ConfigureNotify` event.  Both of which are handled correctly by fvwm.  The application itself (I was testing this with `KeePassXC`) requests user-specified positioning which is coming from the application itself.  There is no reason for the window to move itself at all.

I really don't want to be working around these sorts of bugs in fvwm3.

**Comment by lgsobalvarro** [comment]
Hi @ThomasAdam 
I think you are correct with KeePassXC.
Some other applications like Falkon may not play nicely when a Notification deamon, or certain KDE services are not present/running.
It may well be a QT bug that KDE has not patched yet (KDE took over the maintenance of Qt5 "community" after Trolltech changed it's support policy some time ago).
I can't talk about Kate 18.08.0 (I use 21.08.1) but it is never placed `UnderMouse` as it should. ( I use `Style * PositionPlacement UnderMouse` I'm also using `!UsePPosition`).
Please let me know if there is any testing I could do for you.

**Comment by ThomasAdam** [comment]
I'll close this issue for now.  The QT folks need to stop pushing this broken ideal onto window managers.
