### ISSUE TITLE
FvwmPrompt is installed unstripped

### ISSUE THREAD

**Issue by Zirias** [fvwmorg/fvwm3#618]
## Upfront Information

Hello, I'm the maintainer for the fvwm3 package/port in FreeBSD. I started maintaining the port with 1.0.2; back then, compiling the Go module didn't work (for reasons beyond my understanding), but meanwhile, you chose to bundle all dependend Go libs in your tree and of course, that works. I finally found the time to update the FreeBSD port, so now, I'd like to include `FvwmPrompt`.

* Fvwm3 version (run: `fvwm3 --version`)
    fvwm3 1.0.4 (released)
    with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS

* Linux distribution or BSD name/version
FreeBSD 13.0-RELEASE-p4

## Expected Behaviour

fvwm3 installs all binaries *except* `FvwmPrompt` stripped. I expect this to be installed stripped as well.

## Actual Behaviour

`FvwmPrompt` is installed unstripped.

## Extra Information

Sorry for deviating from your template here, it just isn't useful for this case. I added `GOBUILD="go build -ldflags=\"-s -w\""` to the make invocation when `FvwmPrompt` is built, which solves the problem. Maybe you want to add these `ldflags` to `GOBUILD`? Or maybe you want to introduce a new `GOFLAGS` (or similar), so the build flags are still overridable by the user? Anyways, it would be nice if building a stripped binary for `FvwmPrompt` would be supported.

**Comment by ThomasAdam** [comment]
Hi @Zirias 

Yes, this makes sense.  Can you send a pull-request which addresses this, please?  That would help me massively.

Kindly,
Thomas
