### ISSUE TITLE
FvwmIconMan crashes when trying to display some utf-8 characters.

### ISSUE THREAD

**Issue by somiaj** [fvwmorg/fvwm3#622]
FvwmIconMan, using the default config, crashes when trying to display some utf-8 characters. For example the following character crashes FvwmIconMan

https://www.compart.com/en/unicode/U+1F479

With some further testing it is related to the font. The font from the default config is `*FvwmIconMan: Font "xft:Sans:Bold:size=8:antialias=True"`. Setting the font to `*FvwmIconMan: Font ""`, it no longer crashes and just displays a empty box for the character it cannot find. So this maybe a combination of the font and FvwmIconMan.

If possible, FvwmIconMan should better deal with some utf-8 characters in some fonts.

**Comment by polarbub** [comment]
I tried to set the icon man font to "" and it did nothing for the problem.

This happens on the default config on 1.0.4 with the provided problem website.

**Comment by ThomasAdam** [comment]
Hey @polarbub 

I'll try and find time to look at this, but it won't be any time soon.

Do you see the same problem if you also try to start fvwm3 as:

```
fvwm3 -f /dev/null
```

**Comment by polarbub** [comment]
> I tried to set the icon man font to "" and it did nothing for the problem.
I just restarted x and now this fix works. The charaters that would crash it before don't show up at all in the icon manager but the rest of the titles do. Also the font is the default font for x and it doesn't look very good.

**Comment by somiaj** [comment]
This is actually an issue in XFT that was fixed three years ago, and merged 3 months ago.

<https://gitlab.freedesktop.org/xorg/lib/libxft/-/commit/6a08279ee80dbd1a226592d7f18c862c2e4a7d3a>

Upgrade to xft 2.3.6 to get color emoji's working correctly.

**Comment by polarbub** [comment]
Alright, this works. Thanks!
