### ISSUE TITLE
Resize windows without touching the corners

### ISSUE THREAD

**Issue by demostanis** [fvwmorg/fvwm3#649]
## Describe the new feature

I have a keybinding to resize windows using Alt+Right click
However, when I want to make the window smaller, I have to make it bigger first. If I drag the window towards the center, the window doesn't get resized.

## How might fvwm3 need to change?

Resize according to the nearest corner?

## Can this be achieved through scripting?

This feature exists in XFWM, Compiz, and probably more.

**Comment by ThomasAdam** [comment]
You probably want something like the following:

```
Pick Resize frame direction automatic keep
```
