### ISSUE TITLE
Unable to initialize RandR

### ISSUE THREAD

**Issue by tylertucker202** [fvwmorg/fvwm3#650]
* Fvwm3 version 1.0.4 (released)

* Linux distribution or BSD name/version Ubuntu 20.04

* Platform Linux x86_64

## Expected Behaviour

Running `fvwm3 -r` should start fvwm3

## Actual Behaviour

When I run `fvwm3 -r` in a vnc session, nothing happens and I get the message 'Unable to initialize RandR'

Logs display `FscreenInit: RandR not present`

I am able to run other WM (fvwm2 and awesome)

Thanks for your help. Please let me know if I am missing anything useful.

**Comment by ThomasAdam** [comment]
Which VNC Server are you using?  It will need to support RandR.

**Comment by tylertucker202** [comment]
That is an excellent point. I'm using tightvnc. Would something like TigerVNC be better?

**Comment by ThomasAdam** [comment]
Hey @tylertucker202 

Yes, I think so.  According to what little googling I've done, TigerVNC appears to support RandR.

**Comment by tylertucker202** [comment]
@ThomasAdam I am happy to report that fvwm3 is running successfully. Thank you for your help! This issue can now be closed.
