### ISSUE TITLE
FvwmPrompt quoting not consistent with the Read command.

### ISSUE THREAD

**Issue by domichel** [fvwmorg/fvwm3#662]
$ fvwm3 --version
fvwm3 1.0.5 (1.0.4-123-g0fe58f0d-dirty)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS

A new ~amd64 gentoo installation.

$ uname -sp
Linux Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz

## Expected Behaviour
FvwmPront should use the same quoting than into the files read by the Read command.

If I write `Exec urxvt -name "Some name" -e mc` into a file and read it with `Read thefile`, it work fine and the resource of the urxvt window is "Some name".

If I write the same at the FvwmPrompt prompt, mc start but the resource of the urxvt window is truncated to "Some".
Into the log, I get `urxvt: "name": malformed option.`

In order to get the resource string I want, I must write  `Exec urxvt -name \"Some name\" -e mc`

That is not consistent and can cause a lot of confusion for newcomers.

I get the same issue with Style options like `Style "ALSA Mixer card $[infostore.SoundCard]" !Icon`

* Does the problem also happen with Fvwm2?
No.

Include your configuration with this issue.
That's fvwm-crystal git with some work in progress in $[FVWM_USERDIR].

**Comment by siebenmann** [comment]
I will add my voice to this issue, and note that it prevents using FvwmPrompt as a direct replacement for FvwmConsole. I'm accustomed to doing things such as changing a menu definition in my .fvwm/config, opening a FvwmConsole, and pasting the new definition into FvwmConsole to refresh my live session without a full restart. The FvwmPrompt quoting issue means that this doesn't work.

**Comment by ThomasAdam** [comment]
Hi,

Please have a look at the `ta/gh-662` branch in this repo, which I believe should fix this issue.

**Comment by siebenmann** [comment]
In some quick testing for me, the change from this branch fixes this issue.

**Comment by ThomasAdam** [comment]
Thanks, @siebenmann -- that's good enough for me.  Will merge.
