### ISSUE TITLE
my fvwm config does not work with recent chromium

### ISSUE THREAD

**Issue by marcespie** [fvwmorg/fvwm3#663]
Thanks for reporting your bug here!  The following template will help with
giving as much information as possible so that it's easier to diagnose and
fix.

## Upfront Information

Please provide the following information by running the command and providing
the output.

* Fvwm3 version (run: `fvwm3 --version`)
fvwm3 1.0.4 (released)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, XRandR, XRender, XCursor, XFT, NLS

* Linux distribution or BSD name/version
OpenBSD-current (post 7.1)

* Platform (run: `uname -sp`)
OpenBSD nausicaa.home 7.1 GENERIC.MP#475 amd64

I have several lines in my config that look like:

Mouse 1 W       MS      Maximize 0 100

but since fvwm* does not use XPeekEvent (as far as I can tell), it uses XNextEvent of mouse events inside the window, check the modifiers to see if they match, and try to pushback the event in the queue. This results in a synthetic event !

Chromium (v100.0.4896.127 but this has happened for some time now) is unhappy about this and won't see some clicks (but not all!)

An instance of an url that doesn't work but doesn't require login is:
https://en.cppreference.com/w/cpp/container/vector

(try to use the pulldown menus at the top)

The exact same problem happens with older fvwm2s.

The fix would be to try to make use of XPeekEvent to avoid fooling security-conscious programs into seeing synthetic events when fvwm3 is not changing anything

**Comment by ThomasAdam** [comment]
I think this has now been fixed.

**Comment by marcespie** [comment]
can you point me to the actual change so I can check prior to 1.0.5 ?
or even put it in our OpenBSD port ?

**Comment by marcespie** [comment]
well, actually, I just recompiled and installed fvwm3 from master, and no the issue has not been fixed.

Again: use my partial config, go to the pulldown menu, select an entry, and see it NOT do anything at all.

**Comment by marcespie** [comment]
likewise (but requires login) most of the menu entries do not work... setting your status to online/idle or trying to switch account doesn't work. Somehow chromium classifies the event that fvwm3 put back as synthetic and DOES NOT operate on it.
