### ISSUE TITLE
Only alacritty's window position was moved after exiting fullscreen.

### ISSUE THREAD

**Issue by lolicon0930** [fvwmorg/fvwm3#685]
## Upfront Information
* Fvwm3 version
`fvwm3 1.0.5 (cee5f75)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS`
* Linux distribution or BSD name/version
`Linux 5.18.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.16-1 (2022-08-10) x86_64 GNU/Linux`
* Platform
`12th Gen Intel(R) Core(TM) i5-12500`
## Expected Behaviour
The window position of alacritty returns to its original position after exiting fullscreen.
## Actual Behaviour
The window position of alacritty is moved after exiting fullscreen.
## Steps to Reproduce
* Start with a blank config file (`fvwm3 -f /dev/null`) and go from there.
1. Open alacritty.
2. ToggleFullscreen.
* Does the problem also happen with Fvwm2?
 I didn't try.
## Does Fvwm3 crash?
No.
## Extra Information
* Video

https://user-images.githubusercontent.com/14966910/185830930-5820e0d7-2c40-4c1e-8c9e-4fd321429b80.mp4

* Attach `$HOME/.fvwm/fvwm3-output.log` from the step above.
[fvwm3-output.log](https://github.com/fvwmorg/fvwm3/files/9390973/fvwm3-output.log)
* Include your configuration with this issue.
[config](https://github.com/fvwmorg/fvwm3/files/9390993/config.txt)
https://github.com/alacritty/alacritty/issues/6262

**Comment by ThomasAdam** [comment]
You should be able to fix it like this:

```
Style Alacritty MoveByProgramMethod IgnoreGravity
```

**Comment by lolicon0930** [comment]
It becomes moving in the opposite direction.
There are still situations where it jumps to 0,0 and moves within a certain range.

https://user-images.githubusercontent.com/14966910/186028524-31e87574-ffd7-4ade-8314-55ea7c2c55cb.mp4

**Comment by ThomasAdam** [comment]
@lolicon0930,

There'll be something in your configuration file causing this -- I don't have time to go through yours and check.
