### ISSUE TITLE
[FvwmPager] Feature to remove windows from the pager

### ISSUE THREAD

**Issue by donmor** [fvwmorg/fvwm3#688]
## Describe the new feature

* I can't find any options to hide the windows inside the FvwmPager applets. This makes the widget weird when used in a narrow top bar (I made a separated large pager hidden in a panel).

## How might fvwm3 need to change?

* Add a pair of configuration options: `*FvwmPager: HideWindows` and `*FvwmButtons: NoHideWindows`. These options can control whether the windows inside the pager should be shown.

## Can this be achieved through scripting?

* I'm afraid the source of FvwmPager have to be modified to achieve this.
* Cairo-Dock have a switcher widget resembles Fvwm's pager and the inner windows can be hidden.

**Comment by somiaj** [comment]
I don't quite understand what this feature would do, or the point of it. Why would you want to hide all the windows? The point of the pager is to show the location of windows. If the actual goal is a way to move between pages and/or desks in a tiny panel, use the `GotoDesk` or `GotoDeskAndPage` functions and bind them to buttons in your top bar. Then you can use these to move between desks/pages and not have any windows in them.

If you want to hide specific windows use, `*FvwmPager: UseSkipList`.
