### ISSUE TITLE
fvwm-root doesn't work properly with picom

### ISSUE THREAD

**Issue by pansy27** [fvwmorg/fvwm3#715]
## Upfront Information

* Fvwm3 version: fvwm3 1.0.6 (1.0.5-3-g6ecbbadd)

* Linux distribution: Arch Linux

* Platform: Linux

## Expected Behaviour
I was trying to set the wallpaper using fvwm-root and run picom.

## Actual Behaviour
The wallpaper that got set by fvwm-root becomes grey colored if picom is started. This doesn't happen with nitrogen and hsetroot.

## Enabling logging
Here's the log: https://pastebin.com/guJJGH6Z

## Steps to Reproduce
* set wallpaper using fvwm-root
* start picom, the background set by fvwm-root becomes grey colored.
* config: https://pastebin.com/8iPmjVWX

## Extra Information

* tried using picom without my picom config, still facing the same problem
* tried adding "fvwm" and "fvwm-root" to exceptions in picom config but to no avail
* my picom config: https://pastebin.com/jMDwajHT
* some screenshots: 
before starting picom:
![02_32_54](https://user-images.githubusercontent.com/88635622/193928434-d47ed477-a25a-4bf1-9edd-9c0a04729f13.png)
after starting picom with no configuration file:
![02_33_40](https://user-images.githubusercontent.com/88635622/193928570-a529fecc-2efc-46e2-a567-b602936f1713.png)

**Comment by ThomasAdam** [comment]
Hi @pansy27 

Yes indeed -- this is due to how fvwm-root sets the wallpaper -- and even then, this isn't something I'm inclined to fix.  I'm sure there's better wallpaper setters.  fvwm-root is good for what it does, but it is limited.

**Comment by NsCDE** [comment]
@ThomasAdam and @pansy27

Am I missing something, or:

- pansy27 didn't read man page for fvwm-root and use `-r`
- Thomas forgot that fvwm-root has this capability. :-)

For me, `fvwm-root -r <img>` works perfectly with picom.
