### ISSUE TITLE
Pseudo transparent backgrounds not working with large resolutions

### ISSUE THREAD

**Issue by DeluxeEgg** [fvwmorg/fvwm3#717]
## Upfront Information
$ fvwm3 --version
fvwm3 1.0.4 (released)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS

Gentoo ~amd64

$ uname -sp
Linux AMD Ryzen 9 7950X 16-Core Processor

## Expected Behaviour
I recently purchased two displays that create a combined resolution of 5120x1440.  I have been using pseudo-transparencies for years with my older 3840x1200 setup and everything worked correctly (i.e. transparent background in the pager).

## Actual Behaviour
After starting FVWM with the two new displays, pseudo-transparent backgrounds no longer work and appear as a grey background instead.  Reducing the resolution of the displays permits the pseudo-transparent background to work properly again (even without a restart of FVWM).

## Enabling logging
Nothing appeared in the log file

## Steps to Reproduce
Set a resolution of 5210x1440 or higher and pseudo-transparencies stop working.

Reduce the resolution and they work again.

## Does Fvwm3 crash?
No, FVWM continues to run.

## Extra Information
For some background, I use pseudo-transparent backgrounds with a number of other applications outside of FVWM (terminals, system monitors, etc.) and they still work properly.

I am running FVWM-Crystal as the theme and confirmed it is not and issue with that.

**Comment by ThomasAdam** [comment]
Pseudo-transparency, via ParentialRelativity?

**Comment by DeluxeEgg** [comment]
I would assume it's using ParentialRelativity (provided my understanding of that is correct).  Specifically, the pseudo-transparency that no longer works in FVWM is when it's using the root background to create the "transparency" (for example, my menu background) - different than when using "true" transparency as with a composite manager.

**Comment by dumblob** [comment]
Any insights why this is "not planned"?
