### ISSUE TITLE
FvwmPager does not update selected desktop when changing desktop

### ISSUE THREAD

**Issue by entropic77** [fvwmorg/fvwm3#721]
## Upfront Information

* Fvwm3 version: fvwm3 1.0.6 (1.0.5-10-g6d3791f9)

* Linux distribution: Debian 11.5

* Platform: Linux unknown

## Expected Behaviour

When changing desktop with `GotoDesk`, FvwmPager should highlight the desktop that was changed to.

## Actual Behaviour

When changing desktop with `GotoDesk`, FvwmPager does not highlight the desktop that was changed to, the highlight is stuck on the initial desktop.

It also happens when clicking in FvwmPager, but only when clicking on the desktop title; when clicking on the desktop area, the highlight is updated as it should.

## Steps to Reproduce

Here's a minimal config that can be used to see the problem:
```
IgnoreModifiers L25

Style FvwmPager Sticky

DestroyModuleConfig FvwmPager: *
*FvwmPager: Rows 1
*FvwmPager: Columns 4

AddToFunc StartFunction
+ I Module FvwmPager 0 3

DesktopSize 1x1

Mouse 5         R       A       GotoDesk 1 0 0 3
Mouse 4         R       A       GotoDesk -1 0 0 3

Key   F1        A       M       GotoDesk 0 0
Key   F2        A       M       GotoDesk 0 1
Key   F3        A       M       GotoDesk 0 2
Key   F4        A       M       GotoDesk 0 3
```

Press `Alt-F1` to `Alt-F4`, or scroll the mouse-wheel, or click the desktop-name in the FvwmPager.

## Extra Information

It worked as expected before the commit 594f25e41994577f1fbb571516d15ebc93df8c6c

Changing the `Alt-Fn` commands to the following will work as expected:
```
Key	F1		A	M	GotoDeskAndPage 0 0 0
Key	F2		A	M	GotoDeskAndPage 1 0 0
Key	F3		A	M	GotoDeskAndPage 2 0 0
Key	F4		A	M	GotoDeskAndPage 3 0 0
```

**Comment by ThomasAdam** [comment]
Hi @entropic77 

Odd -- I can't reproduce this, even using your example config -- and *only* your example config.

For me, using those keybindings, with FvwmPager open, highlights the correct desk, regardless of using `GotoDesk` or `GotoDeskAndPage`.

**Comment by entropic77** [comment]
I tried it on two other computers too (deb 10 and 11), cleanly installed fvwm from latest git (2c8be7be551f925959726e0094f6f4b227a2c886). Still getting the problem.

**Comment by ThomasAdam** [comment]
@entropic77 

Then can you please take a recording of what you're seeing?

**Comment by entropic77** [comment]
Here's a recording: https://www.entropic.se/tmp/fvwm-issue-721.ogv

All desktop switches in the video (except the next to last at 0:31) I use Alt-F2, scroll the mouse buttons or click the desktop title in the pager. For the next to last, I click the *desktop area* of the pager, and that's the only one that works as I expect.

**Comment by ThomasAdam** [comment]
Hi @entropic77 

Please can you take a look at the `ta/gh-721` branch and tell me if this fixes the issue you're seeing?

Thanks.

**Comment by entropic77** [comment]
@ThomasAdam Yep, that branch fixed the problem.
