### ISSUE TITLE
Incorrect calculation of text width (XmbTextEscapement)

### ISSUE THREAD

**Issue by setdebug** [fvwmorg/fvwm3#728]
## Upfront Information

Please provide the following information by running the command and providing
the output.

```
fvwm3 1.0.5 (released)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS
```

Running on FreeBSD 13.1 amd64

The configuration file sets the font as follows:

`DefaultFont "-*-helvetica-bold-*-*-*-14-*-*-*-*-*-*-*"`

In menus, Alt-Tab, etc., the right side of text appears to be cut off when using this font:

![menu](https://user-images.githubusercontent.com/83483696/197951618-9fbb555e-4919-42f9-8335-0b48905db99c.png)
![alt-tab](https://user-images.githubusercontent.com/83483696/197951623-9dde0d2e-b214-46a9-9c07-5cd5e6659cca.png)

If I edit `libs/Flocale.c` near line 2229 like this:

```
else if (flf->fontset != None)
{
	// result = XmbTextEscapement(flf->fontset, tmp_str, new_l);
	XRectangle ink;
	XmbTextExtents(flf->fontset, tmp_str, new_l, &ink, NULL);
	result = ink.x + ink.width;
}
```

The text isn't cut off anymore; however, underlines are then positioned incorrectly because `FlocaleTextWidth` returns different values. I can't find an obvious solution to fix the issue without changing how the underlines are drawn.

**Comment by somiaj** [comment]
This is actually quite an old bug, unsure if a fix has ever been found.

<https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=243825>

Though, most just use XFT fonts these days, and I don't think this is an issue with them. Have you tried using XFT fonts?

**Comment by setdebug** [comment]
I just tried changing all instances of `"-*-helvetica-bold-*-*-*-14-*-*-*-*-*-*-*"` to `"xft:Helvetica:weight=bold:slant=oblique:pixelsize=14:scalable=False"` and the results are exactly the same.

It's interesting this bug is that old - I'm surprised I didn't find that bug report!

**Comment by ThomasAdam** [comment]
I'm unlikely to fix this any time soon.

**Comment by somiaj** [comment]
@setdebug It could be that your thought of modifying the underline code is part of what is needed to fix this. If you are going to look at this deeper, and look into modifying the code that draws the underline, here is another old bug report to be aware of (underlines not correctly working with non utf-8 characters). <https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=464363>

**Comment by ThomasAdam** [comment]
I'm going to close this bug for now.  If anyone feels like picking this up and fixing it though, please do!
