### ISSUE TITLE
WindowStyle does not affect window title font

### ISSUE THREAD

**Issue by ssterling** [fvwmorg/fvwm3#736]
## Upfront Information

* fvwm3 1.0.6 (1.0.5-18-g4a30ff5c-dirty) with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, XRandR, XRender, XCursor, XFT, NL
* Gentoo, running Linux 5.15.74
* Linux AMD Ryzen 5 3600 6-Core Processor

## Expected Behaviour

`WindowStyle * Font "..."` changes window title font.

## Actual Behaviour

`WindowStyle * Font "..."` has no effect.

Cursor is shaped like a plus, and window borders, decor, &c. are not drawn until the left mouse button is pressed, upon which the cursor becomes normal and the computer beeps.

## Enabling logging

```
[1667181280.942519] FScreenInit: Using RandR 1.6
[1667181280.957416] FlocaleGetFontSet: [fvwm][FlocaleGetFontSet]: (-*-fixed-medium-r-semicondensed-*-13-*-*-*-*-*-*-*,-*-fixed-medium-r-normal-*-14-*-*-*-*-*-*-*,-*-*-medium-r-normal-*-16-*-*-*-*-*-*-*) Missing font charsets:
[1667181280.957427] FlocaleGetFontSet: KSC5601.1987-0
[1667181280.957431] FlocaleGetFontSet: , 
[1667181280.957433] FlocaleGetFontSet: GB2312.1980-0
[1667181280.957435] FlocaleGetFontSet: 
[1667181283.262045] convert_charsets: [fvwm][convert_charsets]: WARNING -
	
[1667181283.262066] convert_charsets: Invalid byte sequence during conversion from UTF-8 to ISO-8859-1
```

## Steps to Reproduce

Launch FVWM using the following configuration:
```
DefaultFont "xft:Sans:Regular:size=10"
WindowStyle * Font "xft:Sans:Bold:size=10"
Style * Colorset 1, HilightColorset 2
```
(Regarding why the last line is there: see #735.)

## Does Fvwm3 crash?

No.

## Extra Information

I’ve tried swapping around the Bold and Regular bits, just in case it was a font problem, but the issue persists.

**Comment by somiaj** [comment]
Your expectations are incorrect. WindowStyle does not work like Style and you are using it incorrectly. As is stated in the manual page 'sets attributes (styles) on the selected window'. This means you need to run WindowStyle on a selected window.

If you want to change the style of all windows, use `Style * Font "xft:Sans:Bold:size=10"` and all windows will use that font. If you want to change the style of a specific window you need to run `WindowStyle` inside of a function or in the context when a window is selected. One such way to do this is to use FvwmConsole or FvwmPrompt, and inside of that run `Pick WindowStyle Font "xft:Sans:Bold:size=10"`, and that will change the style of the single window you select.

**Comment by ThomasAdam** [comment]
Hi @ssterling,

Per @somiaj's comments, this isn't a bug - in the sense that it's always worked like this.
