### ISSUE TITLE
FVWM3 on Kubuntu: unknown type name ‘RROutput’

### ISSUE THREAD

**Issue by voltumna** [fvwmorg/fvwm3#76]
Hello All, 
i have tried to do the **./configure && make** and it all goes well, but then it fails with the following

What am I missing? this is a 'new' installation and I have put all the dependencies I could

`
...
Making all in libs
make[2]: Entering directory '/home/me/Downloads/fvwm3-master/libs'
  CC       FScreen.o
In file included from FScreen.c:29:
FScreen.h:79:2: error: unknown type name ‘RROutput’
   79 |  RROutput   rr_output;
      |  ^~~~~~~~
FScreen.h:162:41: error: unknown type name ‘XRRScreenChangeNotifyEvent’
  162 | void   monitor_output_change(Display *, XRRScreenChangeNotifyEvent *);
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
FScreen.c: In function ‘FScreenSelect’:
FScreen.c:235:2: warning: implicit declaration of function ‘XRRSelectInput’; did you mean ‘XSelectInput’? [-Wimplicit-function-declaration]
  235 |  XRRSelectInput(disp, DefaultRootWindow(disp),
      |  ^~~~~~~~~~~~~~
      |  XSelectInput
FScreen.c:236:3: error: ‘RRScreenChangeNotifyMask’ undeclared (first use in this function)
  236 |   RRScreenChangeNotifyMask | RROutputChangeNotifyMask);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
FScreen.c:236:3: note: each undeclared identifier is reported only once for each function it appears in
FScreen.c:236:30: error: ‘RROutputChangeNotifyMask’ undeclared (first use in this function)
  236 |   RRScreenChangeNotifyMask | RROutputChangeNotifyMask);
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~
FScreen.c: At top level:
FScreen.c:240:37: error: unknown type name ‘XRRScreenChangeNotifyEvent’
  240 | monitor_output_change(Display *dpy, XRRScreenChangeNotifyEvent *e)
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
FScreen.c: In function ‘scan_screens’:
FScreen.c:293:2: error: unknown type name ‘XRRMonitorInfo’
  293 |  XRRMonitorInfo  *rrm;
      |  ^~~~~~~~~~~~~~
FScreen.c:298:8: warning: implicit declaration of function ‘XRRGetMonitors’ [-Wimplicit-function-declaration]
  298 |  rrm = XRRGetMonitors(dpy, root, false, &n);
      |        ^~~~~~~~~~~~~~
FScreen.c:298:6: warning: assignment to ‘int *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  298 |  rrm = XRRGetMonitors(dpy, root, false, &n);
      |      ^
FScreen.c:306:40: error: request for member ‘name’ in something not a structure or union
  306 |   char *name = XGetAtomName(dpy, rrm[i].name);
      |                                        ^
FScreen.c:324:20: error: request for member ‘x’ in something not a structure or union
  324 |   m->si->x = rrm[i].x;
      |                    ^
FScreen.c:325:20: error: request for member ‘y’ in something not a structure or union
  325 |   m->si->y = rrm[i].y;
      |                    ^
FScreen.c:326:20: error: request for member ‘width’ in something not a structure or union
  326 |   m->si->w = rrm[i].width;
      |                    ^
FScreen.c:327:20: error: request for member ‘height’ in something not a structure or union
  327 |   m->si->h = rrm[i].height;
      |                    ^
FScreen.c:328:29: error: request for member ‘outputs’ in something not a structure or union
  328 |   m->si->rr_output = *rrm[i].outputs;
      |                             ^
FScreen.c:329:29: error: request for member ‘primary’ in something not a structure or union
  329 |   m->si->is_primary = rrm[i].primary > 0;
      |                             ^
FScreen.c: In function ‘FScreenInit’:
FScreen.c:338:2: error: unknown type name ‘XRRScreenResources’
  338 |  XRRScreenResources *res = NULL;
...
FScreen.c:377:3: warning: implicit declaration of function ‘XRRFreeScreenResources’ [-Wimplicit-function-declaration]
  377 |   XRRFreeScreenResources(res);
      |   ^~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:575: FScreen.o] Error 1
make[2]: Leaving directory '/home/me/Downloads/fvwm3-master/libs'
make[1]: *** [Makefile:507: all-recursive] Error 1
make[1]: Leaving directory '/home/me/Downloads/fvwm3-master'
make: *** [Makefile:448: all] Error 2
$>
`
Thanks

**Comment by ThomasAdam** [comment]
Hi @voltumna,

You need to install the XRandR header files.  At least version 1.5

Then FVWM3 will compile.
