### ISSUE TITLE
Minor Issues with Fvwm3MFL Man Page

### ISSUE THREAD

**Issue by farblos** [fvwmorg/fvwm3#774]
## Upfront Information

Please provide the following information by running the command and providing
the output.

* Fvwm3 version (run: `fvwm3 --version`)

```
fvwm3 1.0.5 (released)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS

fvwm3 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of fvwm under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

* Linux distribution or BSD name/version

Debian testing

* Platform (run: `uname -sp`)

Linux unkown

## Minor Issues with Fvwm3MFL man page

- The man page at no point mentions that one can send regular fvwm commands through the socket.

- The example command

  ```
  echo set focus_change | nc -U /tmp/fvwm_mfl.sock 2>&1 | jq --unbuffered
  ```

  does not provide any useful information when executed except the `connection_profile` JSON, since (at least on my system) `ncat` closes on EOF before it actually can report focus changes.

  What about the following example command instead:

  ```
  ( echo set focus_change; echo Next Focus; sleep 1 ) |
  nc -U /tmp/fvwm_mfl.sock 2>&1 | jq --unbuffered
  ```

**Comment by ThomasAdam** [comment]
> * does not provide any useful information when executed except the `connection_profile` JSON, since (at least on my system) `ncat` closes on EOF before it actually can report focus changes.

Try using the BSD netcat.  Works fine for me.
