### ISSUE TITLE
Seemingly unrelated mouse binding breaks certain website menus in Chromium

### ISSUE THREAD

**Issue by mjk-gh** [fvwmorg/fvwm3#777]
## Upfront Information

* Fvwm3 version (run: `fvwm3 --version`):
```
fvwm3 1.0.5 (released)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS
```

* Linux distribution or BSD name/version
Devuan testing, 64 bit

* Platform (run: `uname -sp`)
Linux unknown

## Expected Behaviour
I would expect a mouse binding that requires modifiers to be pressed to *not* interfere with clicking the configured mouse button while *no* modifiers are pressed.

For example, on the website https://batronix.com/ you will find a few icons on the top right, e.g. the "account" icon.
If you hover over it, a little menu will drop down, containing 3 items:
- Account
- Manage services
- Newsletter
(As the item "Account" is the same as clicking directly on the account icon, we will ignore it here.

When hovering over "Manage services" and then clicking that item with the left mouse button, you would expect that item to be selected (a popup with services to activate/deactivate should appear). This does work in Firefox ESR (102.5.0) all the time, and it works in Chromium (108.0.5359.94) -- unless you put this line in your ~/.fvwm3/config:

```
Mouse 1       WTSFI     4          Move
```
(The actual modifiers do not seem to matter, instead of "4", you can use "C", "CS", "M" etc.)

## Actual Behaviour
With the mouse binding above, a left-mouse-button click on "Manage services" in Chromium (*without* any modifier keys pressed!) simply leads to the little menu to vanish, instead of showing the "manage services" popup. Firefox seems to be unfazed by the additional mouse binding, and properly displays the expected pop-up dialog.

The mouse binding above should only get in the way when pressing the specified modifiers.

## Enabling logging

I did a
```
pkill -USR2 fvwm3
```

and the logfile `~/.fvwm3/fvwm3-output.log` did not show anything suspicious when clicking on the little menu.

## Steps to Reproduce

The following is a minimal ~/.fvwm3/config to reproduce the problem, just comment in/out the line with the mouse binding and restart fvwm3 to see how it reacts to the hover/pop-up menu:

```
# -*- mode: sh; -*-

DeskTopSize          3x3
DesktopConfiguration per-monitor
EdgeScroll           100000 100000

# W = window
# T = window title bar
# S = Window side, top, bottom bar
# F = window corners
# I = icon window

#     Button  Context  Modifiers  Function
Mouse 1       WTSFI     4          Move
```
- 3x3 desktop most likely not necessary, I just had too many windows open
- No fvwm configuration in /etc to be seen, as far as I can tell, so above config should be all that fvwm3 loads.

## Extra Information

* FWIW, I attached `$HOME/.fvwm3/fvwm3-output.log`.
[fvwm3-output.log](https://github.com/fvwmorg/fvwm3/files/10170728/fvwm3-output.log)

**Comment by raid1** [comment]
This is related to https://github.com/fvwmorg/fvwm3/issues/761 or even a duplicate.

**Comment by mjk-gh** [comment]
> This is related to #761 or even a duplicate.
Thanks for the hint!

Even if the workaround mentioned there does not work for all programs, it seems to work for Chromium `109.0.5414.74`; starting it with `--disable-features=SendMouseLeaveEvents` makes it work like a charme again.

**Comment by ThomasAdam** [comment]
Closing this as per the reasons in #761
