### ISSUE TITLE
Pager coordinates rounding is off

### ISSUE THREAD

**Issue by Cigaes** [fvwmorg/fvwm3#778]
* Fvwm3 version 1.0.5 built from Debian Testing package for Debian Stable on x86_64
```
fvwm3 1.0.5 (released)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS
```

FvwmPager is configured:
```
DesktopSize 6x4
*FvwmPagerFont none
*FvwmPagerSmallFont none
*FvwmPagerRows 1
*FvwmPagerColumns 1
*FvwmPagerBack Grey45
*FvwmPagerBalloons all
*FvwmPager: SolidSeparators
```
… and swallowed by FvwmButtons:
```
Module FvwmButtons
*FvwmButtonsFore Black
*FvwmButtonsBack Gray67
*FvwmButtonsGeometry +0+0
*FvwmButtonsRows 1
*FvwmButtons(2x1, Swallow FvwmPager 'Module FvwmPager *', Size 112 56)
```

The result is that the coordinates of the view of the windows is off, compared to fvwm2. In particular, the two windows on the right have their right side at the same position on the screen, but they are two pixels off in the pager, while they were aligned in fvwm2. Also, the last line is a little cropped.

(The first screenshot is from fvwm2, the second screenshot is from fvwm3, on 2×1920×1080 screen.)

![fvwm2](https://user-images.githubusercontent.com/5101943/207807946-127b243c-e23f-435d-98a7-510fb4465f5c.png)
![fvwm3](https://user-images.githubusercontent.com/5101943/207807950-21d6ce1c-898c-42ea-bb12-a448cdb70ba8.png)

**Comment by somiaj** [comment]
This is not a bug, and is working as intended. Fvwm3 computes the scaled position and size of a window directly (vs fvwm2 computed the distances from the boundaries of full page). This change was needed to support allowing the pager to show one monitor at a time. The approach fvwm2 used does not reliably work when trying to compute the width and height of a window on a monitor that wasn't positioned at (0,0).

**Comment by Cigaes** [comment]
Thanks for the comment. I understand the change was necessary for a new feature, and I do not contest it. But look at the screenshots: it seems pretty obvious that you have a bug there.
In particular, whether the pager shows a single monitor or the whole virtual screen, windows that are aligned on their right should appear aligned in the pager. Otherwise it is misleading and not beautiful.
At a guess, I would say the problem comes from incorrect handling of integer rounding: you compute the coordinate of the left of the window in the pager, round to the nearest integer, then compute the width of the window, round to the nearest integer, and add, accumulating the rounding errors to the point that they become visible.
