### ISSUE TITLE
No default panel with latest Master.  Dual Monitor of different size.

### ISSUE THREAD

**Issue by BrianA-MN** [fvwmorg/fvwm3#78]
Hi Thomas, 
This is on a Slackware64 14.2 with Nouveau driving a NVIDIA GS8400GX with dual outputs to a DVI at 1600x900 and VGA at 1280x1024.  The .config works under 2.6.9 but not 3.0.0.   You asked for the config and xsession-errors log, which are attached.  I'm just a tester, but willing to help with more testing or explanation of system config or Slackware configs.   Cheers, BrianA_MN
[config.txt](https://github.com/fvwmorg/fvwm3/files/4618062/config.txt)
[1.txt](https://github.com/fvwmorg/fvwm3/files/4618099/1.txt)

**Comment by ThomasAdam** [comment]
Thanks, @BrianA-MN.  Please can you also attach the output from `xrandr`?

**Comment by BrianA-MN** [comment]
Here is xrandr. 
[xrandr-out.txt](https://github.com/fvwmorg/fvwm3/files/4619234/xrandr-out.txt)

**Comment by BrianA-MN** [comment]
Sorry I was only trying to leave comment and file.

**Comment by ThomasAdam** [comment]
Hi @BrianA-MN,

It looks as though you don't have a monitor marked as primary.  Please can you try setting one of your monitors as primary.  For example:

```
xrandr --output <NAME_OF_MONITOR> --primary
```

Perhaps add this to the top of your `~/.xsession` or `~/.xinitrc` script (however you're starting `FVWM3`), and try again...

Kindly,
Thomas

**Comment by ThomasAdam** [comment]
Hi @BrianA-MN,

Further to my previous comment, you should also checkout the `ta/primary-if-none` branch and see if that fixes your problem.  This change assigns the first output `FVWM3` finds as primary in the case no primary monitor is found.

**Comment by BrianA-MN** [comment]
Thomas, I finally compiled, packaged and installed this ta/primary-if-none patch and it didn't resolve the issue of no right screen.  Is there a special file or where is the code embedded so I could do a diff?  Thanks BrianA_MN
