### ISSUE TITLE
Window across screen boundary only raises if under window in primary screen

### ISSUE THREAD

**Issue by utopiabound** [fvwmorg/fvwm3#782]
Thanks for reporting your bug here!  The following template will help with
giving as much information as possible so that it's easier to diagnose and
fix.

## Upfront Information

Setup: Two monitors (two screens).

Fvwm Focus Style options: 
```
Style * SloppyFocus, MouseFocusClickRaises, !FPGrabFocus
```

* Fvwm3 version (run: `fvwm3 --version`)
```
$ fvwm3 --version
fvwm3 1.0.5 (released)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS

fvwm3 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of fvwm under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

```

* Linux distribution or BSD name/version
Fedora 37

* Platform (run: `uname -sp`)
```
$ uname -sp
Linux x86_64
```

## Expected Behaviour

Clicking in a window raises the window above all overlapping windows, regardless of screen boundary crossing.

## Actual Behaviour

If the window crosses a screen boundary, the window is only raised if it is under a window in the primary screen.

Window spanning screen 0 and screen 1 (0 is primary):

If Window intersects no windows in screen 0, only clicking the Title or border will raise the window, clicking into the window will not raise it.

If Window is under a screen 0 window, it will raise across all screens

If Window is already raised above all intersecting windows on screen 0, no clicking into the window will raise it above windows on screen 1. (Title or border clicks will raise it)

The Title/Border behavior is probably because of the Mouse bindings to a function that explicitly calling Raise.

**Comment by ThomasAdam** [comment]
Hi @utopiabound 

Thanks for reporting this -- however, I'm not able to reproduce this.  For me, windows are being raised correctly.  Admittedly, I'm testing this with XTerm, so if you have a specific application which shows this, do please let me know.

**Comment by somiaj** [comment]
I am able to reproduce this with the default-cofnig using xterm.

Place an xterm so it overlaps two monitors. Place a second xterm on the non primary monitor so they overlap. Clicks in either xterm won't raise the xterm. Clicks on the title bar will. If both xterms are fully on the same monitor they raise correctly when clicking inside the xterm.

**Comment by utopiabound** [comment]
I've noticed that some (mostly seen with firefox, because of the number of windows across multiple monitors, but it's not exclusive to firefox) applications have the wrong "Monitor" designation in the FvwmIdent info, this will cause the raise failures as above.

(Given two monitors HDMI-1, and DVI-I)
For instance a firefox window that is fully within the confines of what DVI-I defines, has a listing of HDMI-1, but this can be corrected, by moving the window between the two monitors.  I don't have a consistent reproduction case for this behavior.

**Comment by utopiabound** [comment]
This still happens in 1.0.6

**Comment by ThomasAdam** [comment]
Add this to your configuration:

```
BugOpts RaiseOverUnmanaged True
```
