### ISSUE TITLE
window placement doesn't use dual-monitor desktops

### ISSUE THREAD

**Issue by ExecutorElassus** [fvwmorg/fvwm3#793]
fvwm3-1.0.4
gentoo Linux
Linux AMD Ryzen 7 3800X 8-Core Processor

xorg treats two monitors as a single virtual desktop. When starting fvwm3, ConfigFvwmButtons gives the following geometry:

`*FvwmButtons: Geometry 0:1 520x100-1-1`

This _should_ position the bar in the bottom-right corner of the monitor on the right. However, ButtonsBar only ever spawns in the bottom-right corner of the _left_ monitor, roughly in the middle of the virtual desktop. 

Likewise, setting apps to use fullscreen will only fill one monitor, leaving the other showing my regular desktop. 

Previous versions of fvwm (2.7.0) would spawn ButtonsBar in the desired location, and would spread fullscreen windows across both monitors (nice for widescreen movies, not so nice for video games that didn't have double-wide resolutions and thus got stretched).

Apps that position themselves can always spawn wherever they were set to spawn on either monitor, but apps that let the WM place them will always only spawn on the monitor where the mouse is. 

## Desired Behaviour

I'd prefer ButtonsBar to position itself as with previous versions of fvwm, and would prefer fullscreen to be configurable to use one or both monitors (one game I run uses a "windowed fullscreen" mode to spread across both monitors). 

## Actual Behaviour

See above

## Enabling logging

I don't  believe this is a failure, but if you want a logfile I can attach one. 

## Steps to Reproduce

* How can the problem be reproduced?  For this, the following is helpful:

note: I'm using all the same config files I used under fvwm2, so this may be a problem with one of them. 

* Does the problem also happen with Fvwm2?

no. 

## Does Fvwm3 crash?

no crash (however, IconMan frequently fails to start, which may or may not be related).

**Comment by ThomasAdam** [comment]
Hi @ExecutorElassus 

For this, you'd need to manually specify he geometry.

**Comment by ExecutorElassus** [comment]
all right. Are these commands documented somewhere? How should I write the config file to include these commands/options?

**Comment by somiaj** [comment]
They are all listed in the fvwm manual page.

**Comment by ExecutorElassus** [comment]
listed, yes. But I have no idea how to use them in a config. Can you send me the relevant part from yours as an example?

Thank you for the help. I'm sorry, but I'm new at this :(

**Comment by somiaj** [comment]
@ExecutorElassus I forgot that fvwm accepts screen in the geometry string, the discussion around #814 reminded me of that. For your setup using `520x100-1-1@g` should use the global monitor (like fvwm2 does) which will now be default due to #814. If you want to do the geometry relative to a specific monitor, use the RANDR name, such as `520x100-1-1@HDMI-2`.

The method I mentioned would have required something along the lines of:

```
Style <windowclass> StartsOnScreen <RandRName>, PositionPlacement screen <RandRName> -0 -0, !UseUSPosition, !UsePPosition
```

This tells the window which screen to start on, the position placement uses the move options, see 'Window Movement and Placement' in the manual page, to tell the window where to be placed, and the last two options tell fvwm to ignore any position info given from the app itself.

**Comment by ExecutorElassus** [comment]
@somiaj , thanks for the advice. I tried using both:

`*FvwmButtons: Geometry 520x100-1-1@DisplayPort-0` (also DisplayPort-1)
and 
`*FvwmButtons: Geometry 520x100-1-1@g`

in my .fvwm/ConfigFvwmButtons file, but no matter which of those commands I used, it always displays on the monitor on the left.

Or is this an upcoming fix that isn't in fvwm3-1.0.4?

Thanks so much for your help!

**Comment by somiaj** [comment]
The fix only makes it so @g is the default (if no @foo is provided). Adding @g or @RandRName will work with your version of fvwm. You must not be reading the configuration correctly, because the tests all work fine for me.

**Comment by ExecutorElassus** [comment]
hrm. Just to check, here's how my ConfigFvwmButtons file starts out:

`
################## FvwmButtons button-bar ################################
*----------------*----*----*---*-----------*
*                *biff*clck*   *           *
*  FvwmIconMan   *----*----* ^ *   Pager   *
*                *  xload  *   *           *
*----------------*----*----*---*-----------*
KillModule FvwmButtons
DestroyModuleConfig FvwmButtons: *
#*FvwmButtons: Geometry 520x$[monitor.$[monitor.primary].height]-1-1
*FvwmButtons: Geometry 520x100-1-1@DisplayPort-0
#*FvwmButtons: Monitor DisplayPort-1
*FvwmButtons: Back Colorset 9
*FvwmButtons: (Frame 2, Padding 2 2, Container(Rows 2 Columns 9 Frame 1 Padding 10 0))
# Show 5 more desks in a popup panel:
# Unfortunately, a popup shows the desks 1 to 5, then 0
*FvwmButtons: (4x2, Frame 2, Swallow "FvwmIconMan" "Module FvwmIconMan")
*FvwmButtons: (2x2, Frame 0, Container(Rows 2 Columns 2 Frame 0))
*FvwmButtons: (Frame 2, Swallow(UseOld,NoHints,Respawn) "xbiff" `Exec exec xbiff -bg bisque3`)
*FvwmButtons: (Frame 3, Swallow(UseOld,NoHints,Respawn) "xclock" `Exec exec xclock -bg bisque3 -fg black -hd black -hl black -p>
*FvwmButtons: (2x1, Frame 2, Swallow(UseOld,NoHints,Respawn) "xload" `Exec exec xload -bg bisque3 -fg black -update 5 -nolabel`)
*FvwmButtons: (End)
# The 8 pixels in -108 are to account for the frames:
*FvwmButtons: (1x2, Panel(up, indicator, delay 5000, steps 5, position Root 46 -108p) FvwmPagerSubPanel "Module FvwmPager FvwmP>
*FvwmButtons: (2x2, Frame 2, Swallow(UseOld) "Inline" "Module FvwmPager Inline 0 0")
*FvwmButtons: (End)
`

When I change the @ part in the Geometry line, nothing seems to change except that sometimes the buttons have a transparent background, and sometimes it's black. 

What am I doing wrong here?

Cheers.

**Comment by ExecutorElassus** [comment]
UPDATE: jfc, all this time I've been fiddling with an iconbar that I'm not even using. The _real_ one is BarButtons, defined in .fvwm/modules as:

```
DestroyModuleConfig BarButtons: *
*BarButtons: Colorset 8
#*BarButtons: Fore #0afbff
*BarButtons: Font "xft:sans-serif:Bold:pixelsize=10;-*-helvetica-bold-r-*-*-10-*-*-*-*-*-*-*"
# Geometry - really likes to pick its own size, but giving a position is OK
# Warning: I've added a size geometry to avoid pbs if the fvwm_icons are
# not in the image path ! Remove the size in this geometry especially if
# you add buttons
*BarButtons: Geometry -5-25@g
# Layout: specify rows or columns, not both
*BarButtons: Columns 2
*BarButtons: BoxSize smart
```
Adding a `@g` to the geometry statement there fixed the position. However, now the buttons background is still black. I'll have to fiddle with that.

Cripes. I'm sorry for wasting your time :(
