### ISSUE TITLE
fvwm3 test result

### ISSUE THREAD

**Issue by domichel** [fvwmorg/fvwm3#8]
fvwm3 is installedd on my gentoo system with the following configuration:

```
fvwm3 --version
fvwm 3.0.0 compiled on Jan  4 2020 at 22:48:57
with support for: ReadLine, RPlay, Stroke, XPM, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS
```
When started with its default config and startx, I get:

```
Monitor: LVDS (PRIMARY) (x: 0, y: 0, w: 1600, h: 900)
Screen found; no crtc present
[fvwm][executeModule]: <<ERROR>> No such module 'FvwmBanner' in ModulePath '/usr/local/libexec/fvwm3/3.0.0'
Monitor: LVDS (PRIMARY) (x: 0, y: 0, w: 1600, h: 900)
Screen found; no crtc present
Monitor: LVDS (PRIMARY) (x: 0, y: 0, w: 1600, h: 900)
Screen found; no crtc present
Monitor: LVDS (PRIMARY) (x: 0, y: 0, w: 1600, h: 900)
Screen found; no crtc present
Monitor: LVDS (PRIMARY) (x: 0, y: 0, w: 1600, h: 900)
Screen found; no crtc present
Monitor: LVDS (PRIMARY) (x: 0, y: 0, w: 1600, h: 900)
Screen found; no crtc present
trayer: Fatal IO error 11 (Ressource temporairement non disponible) on X server :0.
XIO:  fatal IO error 4 (Interrupted system call) on X server ":0"
      after 128 requests (128 known processed) with 0 events remaining.
XIO:  fatal IO error 4 (Interrupted system call) on X server ":0"
      after 233 requests (233 known processed) with 1 events remaining.

```
The backgroung image and the menu are working, but I get no banner and no button.

When replacing fvwm by fvwm3 in fvwm-crystal and using startx:
```
Monitor: LVDS (PRIMARY) (x: 0, y: 0, w: 1600, h: 900)
Screen found; no crtc present
[fvwm][executeModule]: <<ERROR>> No such module 'FvwmCommandS' in ModulePath '/usr/local/libexec/fvwm3/3.0.0'
[fvwm][scanForPixmap]: <<WARNING>> Couldn't load image from /home/dom/.fvwm-crystal/icons/fvwm-desktop/32x32-xmahjongg.png
[fvwm][scanForPixmap]: <<WARNING>> Check that FVWM has support for the filetype it's being asked to load.
[fvwm][scanForPixmap]: <<WARNING>> Couldn't load image from /home/dom/.fvwm-crystal/icons/fvwm-desktop/32x32-dosbox.png
[fvwm][scanForPixmap]: <<WARNING>> Check that FVWM has support for the filetype it's being asked to load.
[fvwm][scanForPixmap]: <<WARNING>> Couldn't load image from /home/dom/.fvwm-crystal/icons/fvwm-desktop/32x32-xmahjongg.png
[fvwm][scanForPixmap]: <<WARNING>> Check that FVWM has support for the filetype it's being asked to load.
[fvwm][scanForPixmap]: <<WARNING>> Couldn't load image from /home/dom/.fvwm-crystal/icons/fvwm-desktop/32x32-dosbox.png
[fvwm][scanForPixmap]: <<WARNING>> Check that FVWM has support for the filetype it's being asked to load.
[fvwm][scanForPixmap]: <<WARNING>> Couldn't load image from /home/dom/.fvwm-crystal/icons/fvwm-desktop/32x32-xmahjongg.png
[fvwm][scanForPixmap]: <<WARNING>> Check that FVWM has support for the filetype it's being asked to load.
[fvwm][scanForPixmap]: <<WARNING>> Couldn't load image from /home/dom/.fvwm-crystal/icons/fvwm-desktop/32x32-dosbox.png
[fvwm][scanForPixmap]: <<WARNING>> Check that FVWM has support for the filetype it's being asked to load.
[fvwm][scanForPixmap]: <<WARNING>> Couldn't load image from /home/dom/.fvwm-crystal/icons/fvwm-desktop/32x32-xmahjongg.png
[fvwm][scanForPixmap]: <<WARNING>> Check that FVWM has support for the filetype it's being asked to load.
[fvwm][scanForPixmap]: <<WARNING>> Couldn't load image from /home/dom/.fvwm-crystal/icons/fvwm-desktop/32x32-dosbox.png
[fvwm][scanForPixmap]: <<WARNING>> Check that FVWM has support for the filetype it's being asked to load.
[fvwm][scanForPixmap]: <<WARNING>> Couldn't load image from /home/dom/.fvwm-crystal/icons/fvwm-desktop/32x32-xmahjongg.png
[fvwm][scanForPixmap]: <<WARNING>> Check that FVWM has support for the filetype it's being asked to load.
[fvwm][scanForPixmap]: <<WARNING>> Couldn't load image from /home/dom/.fvwm-crystal/icons/fvwm-desktop/32x32-dosbox.png
[fvwm][scanForPixmap]: <<WARNING>> Check that FVWM has support for the filetype it's being asked to load.
[fvwm][scanForPixmap]: <<WARNING>> Couldn't load image from /home/dom/.fvwm-crystal/icons/fvwm-desktop/32x32-xmahjongg.png
[fvwm][scanForPixmap]: <<WARNING>> Check that FVWM has support for the filetype it's being asked to load.
[fvwm][scanForPixmap]: <<WARNING>> Couldn't load image from /home/dom/.fvwm-crystal/icons/fvwm-desktop/32x32-dosbox.png
[fvwm][scanForPixmap]: <<WARNING>> Check that FVWM has support for the filetype it's being asked to load.
[fvwm][scanForPixmap]: <<WARNING>> Couldn't load image from /home/dom/.fvwm-crystal/icons/fvwm-desktop/32x32-xmahjongg.png
[fvwm][scanForPixmap]: <<WARNING>> Check that FVWM has support for the filetype it's being asked to load.
[fvwm][scanForPixmap]: <<WARNING>> Couldn't load image from /home/dom/.fvwm-crystal/icons/fvwm-desktop/32x32-dosbox.png
[fvwm][scanForPixmap]: <<WARNING>> Check that FVWM has support for the filetype it's being asked to load.
[fvwm][scanForPixmap]: <<WARNING>> Couldn't load image from /home/dom/.fvwm-crystal/icons/fvwm-desktop/32x32-xmahjongg.png
[fvwm][scanForPixmap]: <<WARNING>> Check that FVWM has support for the filetype it's being asked to load.
[fvwm][scanForPixmap]: <<WARNING>> Couldn't load image from /home/dom/.fvwm-crystal/icons/fvwm-desktop/32x32-dosbox.png
[fvwm][scanForPixmap]: <<WARNING>> Check that FVWM has support for the filetype it's being asked to load.
[fvwm][Echo]: Custom recipe loading from '/home/dom/.fvwm-crystal/recipes'
Monitor: LVDS (PRIMARY) (x: 0, y: 0, w: 1600, h: 900)
Screen found; no crtc present
[fvwm][Echo]: /--------- Fvwm-Crystal: Recipe loaded ---------/
Monitor: LVDS (PRIMARY) (x: 0, y: 0, w: 1600, h: 900)
Screen found; no crtc present
could not open /home/dom/.stalonetrayrc (No such file or directory)
Monitor: LVDS (PRIMARY) (x: 0, y: 0, w: 1600, h: 900)
Monitor: LVDS (PRIMARY) (x: 0, y: 0, w: 1600, h: 900)
Screen found; no crtc present
Screen found; no crtc present
Monitor: LVDS (PRIMARY) (x: 0, y: 0, w: 1600, h: 900)
Screen found; no crtc present
Monitor: LVDS (PRIMARY) (x: 0, y: 0, w: 1600, h: 900)
Screen found; no crtc present
WARNING: Could not find all icon sizes for the application icon
[fvwm][CreateConditionMask]: <<DEPRECATED>> Use comma instead of whitespace to separate conditions
[fvwm][GetWindowSizeHints]: <<WARNING>> reason: 5: The hints have been ignored because the window's current size would have become invalid.  The new hints will become active when the window generates the next ConfigureRequest.

[fvwm][GetWindowSizeHints]: <<WARNING>> The application window (id 0xc0012a)
  "mc [dom@tux]:~/.fvwm-crystal" has broken size hints (inconsistent with current size).
    fvwm is ignoring those hints.    hint override = 0, flags = 350
  min_width = 12, min_height = 18, max_width = 0, max_height = 0
  width_inc = 8, height_inc = 14
  min_aspect = 0/0, max_aspect = 0/0
  base_width = 4, base_height = 4
  win_gravity = 1

    If you are having a problem with the application, send a bug report
    with this message included to the application owner.
    There is no need to notify fvwm-workers@fvwm.org.
[fvwm][GetWindowSizeHints]: <<WARNING>> reason: 5: The hints have been ignored because the window's current size would have become invalid.  The new hints will become active when the window generates the next ConfigureRequest.

[fvwm][GetWindowSizeHints]: <<WARNING>> The application window (id 0xc0012a)
  "mc [dom@tux]:~/.fvwm-crystal" has broken size hints (inconsistent with current size).
    fvwm is ignoring those hints.    hint override = 0, flags = 350
  min_width = 12, min_height = 18, max_width = 0, max_height = 0
  width_inc = 8, height_inc = 14
  min_aspect = 0/0, max_aspect = 0/0
  base_width = 4, base_height = 4
  win_gravity = 1

    If you are having a problem with the application, send a bug report
    with this message included to the application owner.
    There is no need to notify fvwm-workers@fvwm.org.

```

**Comment by ThomasAdam** [comment]
Hi,

> fvwm3 is installedd on my gentoo system with the following configuration:
> 
> ```
> fvwm3 --version
> fvwm 3.0.0 compiled on Jan  4 2020 at 22:48:57
> with support for: ReadLine, RPlay, Stroke, XPM, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS
> ```

So, not compiled with `libpng` which explains some of the errors below.

> When started with its default config and startx, I get:
> 
> ```
> Monitor: LVDS (PRIMARY) (x: 0, y: 0, w: 1600, h: 900)
> Screen found; no crtc present
> [fvwm][executeModule]: <<ERROR>> No such module 'FvwmBanner' in ModulePath '/usr/local/libexec/fvwm3/3.0.0'

FvwmBanner was removed by me in fvwm3, so that no longer exists.  Use feh(1) or some other external tool to do the same thing.

```
> Monitor: LVDS (PRIMARY) (x: 0, y: 0, w: 1600, h: 900)
> Screen found; no crtc present
```

Normal -- you only have one screen, it seems.

> The backgroung image and the menu are working, but I get no banner and no button.

Button to what?  Which button?
 
> When replacing fvwm by fvwm3 in fvwm-crystal and using startx:
> 
> ```
> Monitor: LVDS (PRIMARY) (x: 0, y: 0, w: 1600, h: 900)
> Screen found; no crtc present
> [fvwm][executeModule]: <<ERROR>> No such module 'FvwmCommandS' in ModulePath '/usr/local/libexec/fvwm3/3.0.0'

`FvwmCommand` has gone from FVWM3 for now.  I might add it back in temporarily until it's replaced along with `FvwmConsole`.

> [fvwm][scanForPixmap]: <<WARNING>> Couldn't load image from /home/dom/.fvwm-crystal/icons/fvwm-desktop/32x32-xmahjongg.png
> [fvwm][scanForPixmap]: <<WARNING>> Check that FVWM has support for the filetype it's being asked to load.

As noted above, you haven't compiled `FVWM3` against `libpng`.

> could not open /home/dom/.stalonetrayrc (No such file or directory)

I presume you pass what you need to via command-line options to `stalonetray`?

Everything else looks normal to me.

Thanks for testing!

**Comment by domichel** [comment]
Fvwm-Crystal look nice. This is the devel version. With the Custom recipe which contain one main button, the main button is shifted vertically outside of the screen, when its place is correct with fvwm2. The config of that button is in the file.
[CustomButtonBar.txt](https://github.com/fvwmorg/fvwm3/files/4023778/CustomButtonBar.txt)
It is loaded with a Read command.

FvwmIdent give:

```
Monitor: LVDDS
Desk: 0
Layer: 2
Width: 1472
Height: 32
X (Current page): 64
Y (Current page): -34

```
The button definition contain:
`*FvwmButtons-CustomBar: Geometry 1472x32+64-0*FvwmButtons-CustomBar: Geometry 1472x32+64-0`

If I replace +64-0 by +64+0, I get the button at the top at the screen and FvwmIdent tell me than X(current page) is 0, which is fine.

+64-0 works fine with the same button and fvwm2. In order to get the same result with fvwm3, I must write 1472x32+64+868

**Comment by ThomasAdam** [comment]
Hi,

> The button definition contain:
> `*FvwmButtons-CustomBar: Geometry 1472x32+64-0*FvwmButtons-CustomBar: Geometry 1472x32+64-0`
> 
> If I replace +64-0 by +64+0, I get the button at the top at the screen and FvwmIdent tell me than X(current page) is 0, which is fine.
> 
> +64-0 works fine with the same button and fvwm2. In order to get the same result with fvwm3, I must write 1472x32+64+868

Right -- this is because we don't translate XGeometry specifications to the global screen any more.  This is going to be tricky to get right, and although you could argue it's a bug, I'm going to say that it's better (and less ambiguous) to now force the exact geometry, as you've done so.

**Comment by domichel** [comment]
> Hi,

Yes, Hi!
> 
> So, not compiled with `libpng` which explains some of the errors below.
> 
Yes, I see that.

> ```

> > The backgroung image and the menu are working, but I get no banner and no button.
> 
> Button to what? Which button?

The button I get on the right with fvwm2 and the same fvwm default config.
Can it be because I configured fvwm3 with
`--configure --prefix=/usr/local --enable-package-subdirs `
and made the installation with
`make prefix="/usr/local" exec_prefix="/usr/local" libdir="/usr/local/lib" datarootdir="/usr/local/share" install`

> > could not open /home/dom/.stalonetrayrc (No such file or directory)
> 
> I presume you pass what you need to via command-line options to `stalonetray`?

Yes.
> 
> Everything else looks normal to me.
> 
> Thanks for testing!

You are welcome!

**Comment by domichel** [comment]
Hi!
> > +64-0 works fine with the same button and fvwm2. In order to get the same result with fvwm3, I must write 1472x32+64+868
> 
> Right -- this is because we don't translate XGeometry specifications to the global screen any more. This is going to be tricky to get right, and although you could argue it's a bug, I'm going to say that it's better (and less ambiguous) to now force the exact geometry, as you've done so.

It doesn't matter. It is a shell script which generate that magic button. Magic because the user can choose what he want into it and prefs like its placement from its menu, and the button is generated and reloaded on the fly.
It is just to make one more subtraction in the script to get it right for both fvwm2 and 3.

Thanks for your time!

**Comment by domichel** [comment]
Screenshot of fvwm3 running fvwm-crystal. We can see 2 buttons, the left one with some desktop icons, they are file managers launchers. The bottom one with its preference menu give a contemporary look and feel.
![Capture_écran-20200105_201007](https://user-images.githubusercontent.com/678325/71784794-cbbfe580-2ff7-11ea-80fd-b3997619ab04.png)

**Comment by ThomasAdam** [comment]
Thanks!  I'll close this for now -- if you have any other observations, please feel free to open.
