### ISSUE TITLE
FvwmEvent's window_name event (or perhaps function calls) causes window focus issues

### ISSUE THREAD

**Issue by entropic77** [fvwmorg/fvwm3#802]
## Upfront Information

* Fvwm3 version: fvwm3 1.0.6 (1.0.5-57-ge1b81631)

* Linux distribution or BSD name/version: Debian 11 Bullseye

* Platform: Linux unknown

## Expected Behaviour

I have created a function which changes the window frame color based on the window title. This function is called by FvwmEvent on `window_name` events.

## Actual Behaviour

The function is executed as it should, but the problem is that it seems like the function call is causing some glitches in window focusing. I guess this is as hard to understand as it is to explain, so here's a video: https://www.entropic.se/tmp/fvwmevent.ogv Observe the tooltips which appears on mouse hover.

The website time.is/Unix_time, for example, updates the window title every second, which causes the tooltips to disappear every time the window title updates (this only happens in Chromium). The same thing can be seen when copying a file with Dolphin or any other application which updates the window title.

I've seen the same problem in Firefox but cannot reproduce it as easy. I would guess that Fvwm's function calls will cause onblur events in Firefox, but I haven't investigated this yet.

## Enabling logging

No logging was produced.

## Steps to Reproduce

Here's a minimal configuration file which can be used to test the issue:
```
AddToFunc StartFunction
+ I Module FvwmEvent

DestroyModuleConfig FvwmEvent: *
*FvwmEvent: Cmd Function
*FvwmEvent: window_name FuncTitleChanged

DestroyFunc FuncTitleChanged
AddToFunc   FuncTitleChanged
+ I  Nop
```

- Start Chromium (Firefox' tooltips does not experience this issue), and visit time.is/Unix_time or another site which updates the window title automatically and frequently.
- Then hover the mouse over any button to show the tooltips, and watch them disappear immediately.

(Test was done on Chromium Version 108.0.5359.124 (Official Build) built on Debian 11.5, running on Debian 11.6 (64-bit))

Note: I don't think FvwmEvent itself is the culprit, because the problem will also happen when calling a function from some other place, like FvwmCommand.

For example try this configuration:

```
AddToFunc StartFunction
+ I FvwmMFL

DestroyFunc FuncHello
AddToFunc FuncHello
+ I Echo hello
```

Then run `sleep 3; FvwmCommand Function FuncHello` in a terminal and follow the steps to reproduce above (hover tooltips). The tooltip will disappear when `sleep` has finished and the function call is made.

On the other hand: `sleep 3; FvwmCommand Echo hello` will __not__ cause the tooltips to disappear.

## Fvwm2

The problem also happens with Fvwm2.

**Comment by ThomasAdam** [comment]
Hi @entropic77 

Yup -- this isn't a bug in fvwm, but will have everything to do with how Chromium is handling tooltips.  Fvwm isn't responsible for those, but for it to be able to respond to running functions on events, or on demand, that will send an event to Chromium which is probably causing it to behave in the way you've noticed.
