### ISSUE TITLE
Using Maximize on a window split across RandR screens can wind up with bad results

### ISSUE THREAD

**Issue by siebenmann** [fvwmorg/fvwm3#811]
## Upfront Information

* Fvwm3 version (run: `fvwm3 --version`)
fvwm3 1.0.7 (1.0.6a-1-g8670b593)
with support for: ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS
xrandr: primary 3840x2160+0+0, secondary 3840x2160+3840+0

(This is the latest Git as of now.)

* Linux distribution or BSD name/version
Fedora 37

* Platform (run: `uname -sp`)
Linux x86_64

## Expected and Actual Behaviour

If I take a window, split it across both RandR screens so that more than half of it is on the secondary screen, and then Maximize the window, I wind up with a window on the secondary (right) screen that is as tall as the screen but very narrow. If I do this with xterm windows, they often wind up one character wide (plus the scrollbar), which I believe is their minimum width. This happens regardless of which screen I use to click on the window to select the Maximize target.

Fvwm3's Identify always identifies the split window as being on the left screen (the primary). If half or more of the window is on the left side, Maximize will maximize it normally on the left (primary) screen. If all of the window is on the secondary screen, Maximize works normally to maximize it on the secondary screen. I have enabled logging and there is no output during the Maximize.

This may be related to bug #394 and/or bug #264 (well, the fixes for them).

**Comment by ThomasAdam** [comment]
Hi @siebenmann 

Good catch!  Please can you try the `gh-811` branch and let me know if this fixes this issue?

**Comment by siebenmann** [comment]
That branch fixes the issue and it doesn't seem to cause any new ones around maximize in my quick testing.
