### ISSUE TITLE
EdgeScroll needs thinking about for per-monitor setup

### ISSUE THREAD

**Issue by ThomasAdam** [fvwmorg/fvwm3#82]
When `DesktopConfiguration` is set to `global`, the panframes should work the same in `FVWM2` since the monitors are all working as one.

But in `per-desktop` we could add panframes around the edges of each monitor, however, this would make things difficult to move windows between screens, since the EnterNotify event on the panframe would cause the monitor to switch pages (unless `DesktopSize 1x1`).

Thoughts?

**Comment by lgsobalvarro** [comment]
EdgeScroll is half-broken when using only one monitor (I have not tried with two yet). In my particular case EdgeScroll work for Bottom-Left-Top but is broken for Right. I do not know if it has something to do with Ewmh or/and the position of FvwmButtons on my cfg.

**Comment by NsCDE** [comment]
Hi

I don't even see how anything else different from EdgeScroll "0 0" or "100 100" can be reliable on per-desktop mode. For totally seamless experience with < 100 edge scroll and two different desks on two (or more) screens, this will add complexity in desktop backgrounds reliably presenting what user expects visually. This means EdgeScroll different from 0 or 100 (or 100000) should be disabled in per-desktop mode in the direction where other monitor+desk resides ... probably.

This sounds like panframes in per-monitor mode should be different and monitor aware: their purpose to be only to ensure possible edge resistance and to change to the right page of the desk on destination monitor on move from the source monitor. Parametes of such "monitor" panframes in configuration should probably be different from keyword EdgeScroll (MonitorEdgeScroll?)

Just my two cents ...
