### ISSUE TITLE
Cannot use fvwm3 1.0.6a with Xnest

### ISSUE THREAD

**Issue by gabor-zoka** [fvwmorg/fvwm3#822]
Thanks for reporting your bug here!  The following template will help with
giving as much information as possible so that it's easier to diagnose and
fix.

## Upfront Information

Please provide the following information by running the command and providing
the output.

* Fvwm3 version (run: `fvwm3 --version`)

1.0.6a

* Linux distribution or BSD name/version

ArchLinux. I build it from https://aur.archlinux.org/packages/fvwm3

* Platform (run: `uname -sp`)

Linux

## Expected Behaviour

What were you trying to do?  Please explain the problem.

I use

Xnest -br -dpms -nolock -geometry 1920x1080+0+1062 -auth .Xauthority :1

(inside a multidesktop fvwm)

Then I run 

export DISPLAY=:1; firefox & fvwm

This works with fvwm.

## Actual Behaviour

It fails with not being able to initialze RandR. It exist with message. Sadly, I do not know exactly the message as I use btrfs snapshots, and I wiped this snapshot and restored my old set-up. 

I can make an effort to replicate if this bug is considered to be fixed. Not so sure as Xnest must not be a priority.

What should have happened, but didn't?

* I am looking for a switch that would disable RandR for this use case (or similar legacy use case), or
* having an option to co-install fvwm and fvwm3. The Arch AUR build by ThomasAdam do not allow the two to co-exist. So I can use fvwm3 as my main wm, but fvwm inside Xnest

I have been using fvwm since Apr 2004 happily. I upgraded successfully to fvwm3, but when I work from home I keep all my Citrix stuff in Xnest frame. So it is pretty important for me.

Thank you for your consideration.

Gabor

**Comment by ThomasAdam** [comment]
Hi @gabor-zoka 

Use `Xephyr` instead -- many people made the switch from xnest years ago.

**Comment by gabor-zoka** [comment]
Sadly Xephyr does not work. I use Citrix in this frame and it locks up and starts 2 Citrix sessions via Xephyr. Long story short, it does not work. Xnest is superior. I used the same tested command line 

Xnest -br -dpms -nolock -geometry 1920x1080+0+1062 -auth .Xauthority :1

works

Xephyr -br -dpms -nolock -screen 1920x1080 -auth .Xauthority :1

does not.

So I will stick with fvwm then :-(

Thank you for your work on this WM though, but now I hope fvwm will keep working, too.

Gabor
