### ISSUE TITLE
Wrong maximizing with EwmBaseStruts

### ISSUE THREAD

**Issue by afhp-2020** [fvwmorg/fvwm3#84]
Recompiled from master today, can't say when the regression appeared.

When using EwmBaseStruts as described below, most Maximize actions will incorrectly resize windows.

Primary screen is 1900x1200, right screen is 900x1440 (rotated widescreen), screens are aligned at the bottom.
```
DVI-I-1 connected primary 1920x1200+0+240
DP-2 connected 900x1440+1920+0 right
```
Base struts are defined on the primary screen:
```
EwmhBaseStruts screen $[monitor.primary] 48 0 0 0
```
This is where the MainPanel goes:
```
AddToFunc StartFunction
[...]
+ I Module FvwmButtons MainPanel -g +0+521
[...]
```
Now, when maximizing a window on the right-hand screen, it fills the space as expected. 

On the primary however, `Maximize` with no argument will expand the window without covering the panel, but will overlap the right screen by the struts width (window geometry 1910x1169+48+240 ; here it's a text editor so dimensions are probably rounded to character cells. All windows expand in the same way). It should instead stop at the primary monitor's side.
`Maximize fullscreen` expands the window without its frame to the area of the screen, including under the panel (geometry 1920x1200+0+240).
`Maximize screen <number>` behaves as without argument.
`Maximize ewmhiwa` expands the window similarly to `fullscreen` but with its frame included (geometry 1910x1169+0+240). This should be normal as per the manpage.

It seems that when the struts are taken into account for positioning the window, they're not subtracted from the window size (at least horizontally).

**Comment by afhp-2020** [comment]
From .xsession-errors log, maximizing normally on the primary screen:
```
ewmh_ComputeAndSetWorkArea: monitor 'DVI-I-1': {l: 48, r: 0, t: 0, b: 0} {x: 48, y: 0, w: 1872, h: 1200}
EWMH_GetWorkAreaIntersection: mon: DVI-I-1 {ax: 48, ay: 0, aw: 1872, ah: 1200
EWMH_GetWorkAreaIntersection: mon: DVI-I-1 {x: 0, y: 240, w: 1920, h: 1200
EWMH_GetWorkAreaIntersection: mon: DVI-I-1 RETURNING: {x: 48, y: 240, w: 1920, h: 1200}
```

**Comment by ThomasAdam** [comment]
Thank you, @afhp-2020.

Out of interest, if you don't have your right screen rotated, do things work as you'd expect?

**Comment by afhp-2020** [comment]
Hi Thomas,

No difference with the right screen in `--rotation normal` with xrandr.

Even with rotation, from the `ewmh_ComputeAndSetWorkArea` in the log, the primary screen area seems to be calculated properly initally, but something is lost later on.

**Comment by ThomasAdam** [comment]
Hi @afhp-2020,

Thanks.  I can't reproduce this either.  I have:

* Set one of my monitors to be a lower resolution than the other, and maximized windows -- both respect the BaseStruts setting I have;
* Set one of my monitors to have a `right` rotation, again, same result, BaseStrut respected.

Can you take another video for me, so I can see what's happening?

Thanks!

**Comment by lgsobalvarro** [comment]
I can't reproduce this either.

It works fine with my EwmhBaseStruts, and when  I use your own EwmhBaseStruts, and it works well too.

**Comment by afhp-2020** [comment]
Weirderer and weirderer...

[fvwm3-maximize.zip](https://github.com/fvwmorg/fvwm3/files/4671418/fvwm3-maximize.zip)

Both screens are at their native resolution. Full (relevant) `xrandr` setup:
```
DVI-I-1 connected primary 1920x1200+0+240 (normal left inverted right x axis y axis) 547mm x 350mm
   1920x1200     59.95*+
   1920x1080     60.00  
   1680x1050     59.95  
   1600x1200     60.00  
   1600x900      60.00  
   1440x900      59.89  
   1400x1050     59.98  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    72.81    59.94  
DP-2 connected 900x1440+1920+0 right (normal left inverted right x axis y axis) 408mm x 255mm
   1440x900      59.89*+  74.98  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x800      74.93    59.81  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    72.81    59.94  
```
I can't pinpoint when it started happening but I think it's when I went back to master a few days ago. This is currently a fresh build, however.

At this point, the full Fvwm config might help:

[config.txt](https://github.com/fvwmorg/fvwm3/files/4671427/config.txt)

**Comment by ThomasAdam** [comment]
Hi @afhp-2020,

Got it -- the trick is to set the left EWMHBaseStrut to something > 0.

Patch to follow...

**Comment by ThomasAdam** [comment]
@afhp-2020 / @lgsobalvarro,

Chaps, please can you checkout the `ta/gh-84` branch, and give that a go?  I'm hoping this fixes your problem and doesn't regress on the previous work I've done to make `EwmhBaseStruts` work with different monitor sizes.

@lgsobalvarro -- one for you to check, please.

Thanks both!
Thomas

**Comment by afhp-2020** [comment]
Well, that was unexpected: ta/gh-84 solves this bug **and** #85 :)

**Comment by ThomasAdam** [comment]
@afhp-2020,

Well, that's something.  Two birds, one stone.

I'll wait for @lgsobalvarro to respond, and if he's happy, I'll merge the pull-request.

Thanks again!
Thomas

**Comment by lgsobalvarro** [comment]
Seems to work fine here after a quick test.

**Comment by ThomasAdam** [comment]
Thanks both. Merged now.
