### ISSUE TITLE
Docks should be able to really be docks: _NET_WM_WINDOW_TYPE_DOCK

### ISSUE THREAD

**Issue by schrmh** [fvwmorg/fvwm3#842]
## Describe the new feature
In respect to https://www.fvwm.org/Wiki/Panels/, what is called Docks there should be able to really be be Docks according to https://specifications.freedesktop.org/wm-spec/1.3/ar01s05.html.

## How might fvwm3 need to change?

Add an option to set _NET_WM_WINDOW_TYPE of FvwmButtons

## Can this be achieved through scripting?
Pretty likely doable with a few lines in xlib (<20 lines standalone)

**Comment by ThomasAdam** [comment]
Hi,

I think you've misunderstood.

**Comment by schrmh** [comment]
Unless you mean that I overlooked something in the man pages I don't think I have?

The reason I want (some) FvwmButtons to be docks is that they really act like docks in some cases.

And a certain use-case would be the ShowDesktop example which hides FvwmButtons but not docks (like xfce4-panel)
Sure, for that case I could likely make exceptions for all FvwmButton instances I want to ignore but it would in my opinion be better to just be able to define the window type of FvwmButton instances.
Else it could happen that I might need to use a few lines of xlib anyways and call it after FvwmButtons start...

Would this at least be accepted if there was a PR? Won't do one for a long time due to limited time but would be nice to know in advance...
