### ISSUE TITLE
Menus of xfce4 applications appear on the wrong screen in some cases

### ISSUE THREAD

**Issue by schrmh** [fvwmorg/fvwm3#843]
## Upfront Information

A bit similar to this https://github.com/fvwmorg/fvwm3/issues/311 but not with FVWM3's own menus and not with anything changed regarding desktops in the config.

* Fvwm3 version (run: `fvwm3 --version`)
fvwm3 1.0.7 (1.0.6a-12-gd61963f2)

* Linux distribution or BSD name/version
Arch Linux x86_64

* Platform (run: `uname -sp`)
Linux unknown

## Expected Behaviour

Context menu of the application should open where the mouse is

## Actual Behaviour

Opens in the middle of my two monitors when I have more than one DesktopName entry in the config (default config has four DesktopName entries).

## Enabling logging
If you really need this and you can't reproduce then I will do this...

## Steps to Reproduce
Use any(?) xfce4 app and right click to bring up the context menu of that app. Standard fvwm3 config should have the issue.

* Does the problem also happen with Fvwm2?
I don't know yet (currently not installed, might do that later...)

## Does Fvwm3 crash?
No

## Extra Information

![image](https://user-images.githubusercontent.com/32062480/232338464-1d7a4f17-1922-432d-aa1e-5346c72a2363.png)

**Comment by ThomasAdam** [comment]
This should be fixed via #779

**Comment by schrmh** [comment]
Indeed. I did not expect that it would have been fixed in the few commits since April.
