### ISSUE TITLE
FVWM logs warnings `Invalid byte sequence during conversion from UTF-8 to ISO-8859-1`

### ISSUE THREAD

**Issue by farblos** [fvwmorg/fvwm3#844]
Thanks for reporting your bug here!  The following template will help with
giving as much information as possible so that it's easier to diagnose and
fix.

## Upfront Information

Please provide the following information by running the command and providing
the output.

* Fvwm3 version (run: `fvwm3 --version`)

```
[fvwm-bugs]$ fvwm3 --version
fvwm3 1.0.6a (released)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS

fvwm3 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of fvwm under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

* Linux distribution or BSD name/version

Debian testing:

```
[fvwm-bugs]$ cat /etc/debian_version 
12.0
```

* Platform (run: `uname -sp`)

```
[fvwm-bugs]$ uname -sp
Linux unknown
```

## Expected Behaviour

No iconv warnings in journal/log when Firefox switches window title.

## Actual Behaviour

Getting frequent warnings along the lines of

```
Apr 22 11:54:58 sappc1 fvwm3[1317]: [1682157298.722590] convert_charsets: [fvwm][convert_charsets]: WARNING -
Apr 22 11:54:58 sappc1 fvwm3[1317]:         
Apr 22 11:54:58 sappc1 fvwm3[1317]: [1682157298.722599] convert_charsets: Invalid byte sequence during conversion from UTF-8 to ISO-8859-1
```
## Enabling logging

See above.

## Steps to Reproduce

Switch tabs in Firefox or open new web pages, thus triggering window title changes.

## Does Fvwm3 crash?

No.

## Extra Information

I debugged this issue in gdb.  I think in the following snippet from `ewmh_names.c`:

```
        val = ewmh_AtomGetByName(
                FW_W(fw), "_NET_WM_ICON_NAME",
                EWMH_ATOM_LIST_PROPERTY_NOTIFY, &size);

        if (val == NULL)
        {
                SET_HAS_EWMH_WM_ICON_NAME(fw,0);
                return 0;
        }
        if (IS_ICON_FONT_LOADED(fw) && fw->icon_font != NULL)
        {
                fc = fw->icon_font->str_fc;
        }

        tmp_str = (char *)FiconvUtf8ToCharset(
                dpy, fc, (const char *) val, size);
```

the string `val` is not (always) zero-terminated.  Here is a snippet from a gdb session of mine:

```
Breakpoint 2, EWMH_WMName (fw=0x55f83349ba90, ev=0x55f831a24820 <fev_event>, 
    style=0x0, any=0) at ./fvwm/ewmh_names.c:193
193     {
(gdb) n
194             int size = 0;
(gdb) n
203             val = ewmh_AtomGetByName(
(gdb) n
207             if (val == NULL)
(gdb) n
212             if (IS_WINDOW_FONT_LOADED(fw) && fw->title_font != NULL)
(gdb) p val
$1 = 0x55f83347ce10 "404 | Debian Sources — Mozilla Firefoxq"
(gdb) p size
$2 = 40
(gdb) x/48xb val
0x55f83347ce10: 0x34    0x30    0x34    0x20    0x7c    0x20    0x44    0x65
0x55f83347ce18: 0x62    0x69    0x61    0x6e    0x20    0x53    0x6f    0x75
0x55f83347ce20: 0x72    0x63    0x65    0x73    0x20    0xe2    0x80    0x94
0x55f83347ce28: 0x20    0x4d    0x6f    0x7a    0x69    0x6c    0x6c    0x61
0x55f83347ce30: 0x20    0x46    0x69    0x72    0x65    0x66    0x6f    0x78
0x55f83347ce38: 0x71    0x00    0x00    0x00    0x00    0x00    0x00    0x00
```

Please note the trailing letter `q` in the string.  If the trailing garbage is invalid UTF-8, like seen in the following example:

```
Breakpoint 1, FiconvUtf8ToCharset (dpy=0x55f8334521b0, 
    fc=0x55f831a1b860 <FlocaleCharsetTable>, 
    in=in@entry=0x55f8334e3e50 "404 | Debian Sources — Mozilla Firefo", <incomplete sequence \341>, in_size=40) at ./libs/Ficonv.c:494
494             my_fc = FiconvSetupConversion(dpy, fc);
(gdb) x/50xb in
0x55f8334e3e50: 0x34    0x30    0x34    0x20    0x7c    0x20    0x44    0x65
0x55f8334e3e58: 0x62    0x69    0x61    0x6e    0x20    0x53    0x6f    0x75
0x55f8334e3e60: 0x72    0x63    0x65    0x73    0x20    0xe2    0x80    0x94
0x55f8334e3e68: 0x20    0x4d    0x6f    0x7a    0x69    0x6c    0x6c    0x61
0x55f8334e3e70: 0x20    0x46    0x69    0x72    0x65    0x66    0x6f    0x78
0x55f8334e3e78: 0xe1    0x00    0x00    0x00    0x00    0x00    0x00    0x00
0x55f8334e3e80: 0x40    0x3c
```

iconv triggers the warning.

I'm not completely into that code, but I guess that `ewmh_AtomGetByName` can return arbitrary `(void *)` data, so the result probably should be zero-terminated when it  is known to be `(char *)`.
 
This would affect both functions `EWMH_WMName` and `EWMH_WMIconName` in `ewmh_names.c`.

**Comment by ThomasAdam** [comment]
Hi @farblos 

Thanks. This should not be happening. Can you send me through a proposed patch, and I'll take a look.

**Comment by farblos** [comment]
@ThomasAdam: Nah, my diagnosis was wrong.  I really get these warnings, but they are not related to zero-termination of strings.  I think the string semantics in that region of code is simply (ptr, length) and not (zero-terminated ptr).

Will continue to poke around with gdb ...

**Comment by farblos** [comment]
Ok, the story (more lilkely) goes like this:

- I use `Style * NoIcon` in my config file
- Accordingly (?), the icon font never gets loaded for any window, and `fw->icon_font` always equals `NULL` for all windows
- However, `EWMH_WMIconName` gets called, anyway, and tries to convert the icon name encoding
- As there is no the window icon font which could provide the character set, `FiconvSetupConversion` picks `FLCIconvDefaultCharset` as default, which is for whatever reason ISO-8859-1 in my FVWM
- But the emdash in the Firefox title does not convert from UTF-8 to ISO-8859-1 and, hence, the warning

Any hints on why `FLCIconvDefaultCharset` is on ISO-8859-1?

(At least during this journey I came across `BugOpts TransliterateUtf8 true`, which silences the warnings as a work-around.)

**Comment by ThomasAdam** [comment]
@mikeandmore -- is this something you've time to look at?  I know you did some work on font handling recently.

**Comment by mikeandmore** [comment]
Sure. I may have some time this weekend or next weekend to take a look.

I think we simply shouldn't convert to ISO-8859-1 under XFT because that was mostly used for old xfonts.

**Comment by mikeandmore** [comment]
send a PR #860 .

@ThomasAdam Does that look right to you?

**Comment by farblos** [comment]
@mikeandmore Thanks. Unfortunately your patch does not make the warnings go away. But maybe I did something wrong ...

```
git clone https://github.com/fvwmorg/fvwm3.git
cd fvwm3
sh autogen.sh 
./configure
make
git remote add mikeandmore https://github.com/mikeandmore/fvwm3.git
git fetch mikeandmore 
git cherry-pick 0a9a1c212b2b8fd04e3325c5fd7405391169d0e7
make clean
make
```

The resulting binary should have XFT support:

```
[fvwm3]$ ./fvwm/fvwm3 -version
fvwm3 1.0.7 (1.0.6a-17-g01908e29)
with support for:  XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS

fvwm3 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of fvwm under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

`git log` shows your commit:

```
commit 1cfb38c81433b2e906f0e26279f8e09e060cf5ef (HEAD -> main)
Author: Mike Qin <mikeq@untether.ai>
Date:   Sun Jun 25 10:46:32 2023 -0400

    we don't need iconv under XFT

commit 01908e2930bb24f9cc098941470a417c374f62c2 (origin/main, origin/HEAD)
Author: Thomas Adam <thomas@fvwm.org>
Date:   Mon Dec 9 00:22:08 2019 +0000

    FvwmPerl: fix regexp warning for special chars
[...]
```

Started fvwm3 directly from the development directory, double-checking:

```
[fvwm3]$ nc -U /tmp/fvwm_mfl.sock
{"connection_profile":{"version":"1.0.7","version_info":"1.0.6a-17-g01908e29"}}
set echo
echo $[version.num]
{"echo":{"message":"1.0.7"}}
echo $[version.info]
{"echo":{"message":"1.0.6a-17-g01908e29"}}
echo $[version.line]
{"echo":{"message":"fvwm3 1.0.7 (1.0.6a-17-g01908e29)"}}
```

But when I open a new tab in firefox I still get the warnings in the log:

```
[1687899731.167629] CMD_Echo: 1.0.7
[1687899738.559748] CMD_Echo: 1.0.6a-17-g01908e29
[1687899749.815249] CMD_Echo: fvwm3 1.0.7 (1.0.6a-17-g01908e29)
[1687899797.373485] convert_charsets: [fvwm][convert_charsets]: WARNING -

[1687899797.373513] convert_charsets: Invalid byte sequence during conversion from UTF-8 to ISO-8859-1
[1687899801.408411] convert_charsets: [fvwm][convert_charsets]: WARNING -

[1687899801.408443] convert_charsets: Invalid byte sequence during conversion from UTF-8 to ISO-8859-1
```

If you spot sth I may have done wrong during the build process pls let me know.

**Comment by farblos** [comment]
Will try to debug this tomorrow ...

**Comment by farblos** [comment]
Doh, I'm pretty sure that I haven't used an Xft font as default font during my first tests ... will repeat test tomorrow.

**Comment by mikeandmore** [comment]
@farblos Yes, you need to use Xft font. Anytime you use a xfont, fvwm needs to convert into ISO-8859-1 I believe.

**Comment by farblos** [comment]
@mikeandmore Tested again: **With** your patch and with an Xft default font (haven't tested finer granularity) the warnings are indeed gone.  **Without** your patch and with an Xft default font I get the warnings.

And if I understood you correctly (modulo your slight uncertainty), for legacy xfonts you will always get these warnings for characters that cannot be converted to ISO-8859-1.

So if @ThomasAdam oks this patch as well we can close this issue...
