### ISSUE TITLE
Full-screening a window while its upper left corner overlaps FVWMIconMan causes it to not take up the full screen.

### ISSUE THREAD

**Issue by polarbub** [fvwmorg/fvwm3#850]
## Upfront Information

I used `fvwm3 -f /usr/share/fvwm3/default-config/config` to start fvwm. Here is a video of what happens. https://www.youtube.com/watch?v=iFxiGBec9HM

* Fvwm3 version (run: `fvwm3 --version`)
https://pastebin.com/Vh1y9WjF

* Linux distribution or BSD name/version
Arch Linux

* Platform (run: `uname -sp`)
https://pastebin.com/q0qrVUWg

## Expected Behaviour

I would expect it to take up my whole left monitor.

## Actual Behaviour

It was the size of FVWMIconMan on my right monitor.

## Steps to Reproduce

1. Move the top left corner of a window to be over FVWMIconMan. 
2. Maximize the window. 
3. Observe how the window is not in the right place.

I used the default configuration.

## Does Fvwm3 crash?
Nope

**Comment by ThomasAdam** [comment]
Can you try the version from git?

I really don't think this a bug any longer.  If it is, please upload the same logs.

You can also attach files directly to Github issues, rather than using external pastebins -- this helps keep the information together in one place.

**Comment by polarbub** [comment]
It doesn't happen on the git version, but the icon manager goes in the wrong spot. I took videos because my screenshot utility wouldn't put in the black bars to show my two monitors. 

What happens:

https://github.com/fvwmorg/fvwm3/assets/71790726/b1d1bb8a-2367-4a0d-a505-4db218f2f962


Where it should be: (I moved it manually)

https://github.com/fvwmorg/fvwm3/assets/71790726/ebff9473-dd13-4740-a9b6-7d1be038b739
