### ISSUE TITLE
CursorStyle top_edge|bottom_edge|left_edge|right_edge not working

### ISSUE THREAD

**Issue by dumblob** [fvwmorg/fvwm3#851]
## Upfront Information

* Fvwm3 version (run: `fvwm3 --version`):
```
fvwm3 1.0.7 (1.0.6a-12-gd61963f2)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS
```

* Linux distribution or BSD name/version: Arch Linux (Linux 6.1.21-1-lts # 1 SMP PREEMPT_DYNAMIC x86_64)

* Platform (run: `uname -sp`): Linux unknown

## Expected Behaviour

What were you trying to do?

I have put into the default config:

```fvwm
CursorStyle top_left     crosshair
CursorStyle top_right    crosshair
CursorStyle bottom_left  crosshair
CursorStyle bottom_right crosshair

CursorStyle top_edge     crosshair
CursorStyle bottom_edge  crosshair
CursorStyle right_edge   crosshair
CursorStyle left_edge    crosshair
```
And expected the mouse cursor to change to `crosshair` everywhere.

## Actual Behaviour

Only the corner (i.e. the first 4 lines) cursor styles got applied. The edge cursor styles stayed at their defaults :cry:.

## Enabling logging

There is nothing additional in `$HOME/.fvwm/fvwm3-output.log` compared to when started wihout those 8 lines above.

## Steps to Reproduce

How can the problem be reproduced?  For this, the following is helpful:

* Reduce the problem to the smallest `fvwm` configuration example (where
  possible).  Start with a blank config file (`fvwm3 -f/dev/null`) and go from
  there.

See above how to adjust the default distributed config.

* Does the problem also happen with Fvwm2?

I did not try this (I do not have FVWM 2 installed any more).

## Does Fvwm3 crash?

No crashing.

## Extra Information

N/A

**Comment by lgsobalvarro** [comment]
Do you have the mentioned commands in your config file as shown there with all those spaces?
`CursorStyle top_edge     crosshair` it does not work, but `CursorStyle top_edge crosshair` does work as expected. I would suggest removing all those unnecessary spaces and trying again.

**Comment by dumblob** [comment]
Cood idea - have tried it now but no luck (it still shows the default cursors instead of `crosshair`):
```fvwm
CursorStyle top_edge crosshair
CursorStyle bottom_edge crosshair
CursorStyle right_edge crosshair
CursorStyle left_edge crosshair
```

**Comment by lgsobalvarro** [comment]
It could be that the Cursor theme you are using does not include `crosshair`. I have experienced similar things before. Some cursor themes do not include all known/regular cursor names. For instance for `crosshair` there is a `tcross`, `cross` and even `cell`. However... even if the cursor theme does not include a crosshair, fvwm should use a generic one.

I can't reproduce the problem using the provided your CursorStyle (once removed the unneeded spaces).

**Comment by dumblob** [comment]
My cursor theme certainly contains the `crosshair` cursor as I am happily using it for
```fvwm
CursorStyle top_left     crosshair
CursorStyle top_right    crosshair
CursorStyle bottom_left  crosshair
CursorStyle bottom_right crosshair
```
cursorstyles as noted in the original post :wink:.

**Comment by dumblob** [comment]
Yet I find it really fishy (read *wrong*) that in your setup there is a different behavior with multiple spaces in between the command arguments and with a single space.

**Comment by ThomasAdam** [comment]
Hi @dumblob 

Sorry for the delay.  Please have a look at the `ta/gh-851` branch which should fix this issue.
