### ISSUE TITLE
New version of Steam causing FVWM to crash when setting background with 'fvwm-root -r'

### ISSUE THREAD

**Issue by sebaro** [fvwmorg/fvwm3#854]
Thanks for reporting your bug here!  The following template will help with
giving as much information as possible so that it's easier to diagnose and
fix.

## Upfront Information

Please provide the following information by running the command and providing
the output.

* Fvwm3 version (run: `fvwm3 --version`)
fvwm3 1.0.7 (1.0.6a-17-g01908e29)
with support for:  XPM, PNG, SVG, Shape, XShm, SM, XRandR, XRender, XCursor, XFT, NLS

* Linux distribution or BSD name/version
Gentoo

* Platform (run: `uname -sp`)
Linux AMD Athlon(tm) 5350 APU with Radeon(tm) R3

## Expected Behaviour

FVWM doesn't crash

## Actual Behaviour

Setting background with 'fvwm-root -r' makes FVWM crash when starting Steam, it doesn't crash without the -r/--retain-pixmap.

Steam log:

> (steam:15448): GLib-GObject-CRITICAL **: 12:16:45.201: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

> (steam:15448): GLib-GObject-CRITICAL **: 12:16:45.201: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  70 (X_PolyFillRectangle)
  Resource id in failed request:  0x4009fc
  Serial number of failed request:  13774
  Current serial number in output stream:  13784
xinit: connection to X server lost

**Comment by ThomasAdam** [comment]
Hey @sebaro 

Can you capture the output from `xprop -spy -root` prior to FVWM crashing, please?

**Comment by sebaro** [comment]
[xprop.log](https://github.com/fvwmorg/fvwm3/files/11833150/xprop.log)

**Comment by sebaro** [comment]
Doesn't crash with the newest Steam version:
````
Steam Version:  1690583737
Steam Client Build Date:  Fri, Jul 28 9:44 PM UTC +02:00
Steam Web Build Date:  Sat, Jul 29 1:21 AM UTC +02:00
Steam API Version:  SteamClient020
