### ISSUE TITLE
Q: is it possible to use m4 functions like substr() in FvwmIconMan Format formatstring?

### ISSUE THREAD

**Issue by maoamid** [fvwmorg/fvwm3#871]
What is the syntax to follow?
In documenation is only mentioned this:

> *FvwmIconMan: [id] Format formatstring
A printf like format string which describes the string to be printed in the manager window for each managed window. Possible flags are: %t, %i, %c, and %r for the window's title, icon, class, or resource name, respectively. The default is "%c: %i". Warning: m4 reserves the word format, so if you use m4, take appropriate action.

I'm trying to limit the button label to a fixed number of chars only. Any clarification will help.

**Comment by ThomasAdam** [comment]
Hi @maoamid 

No. This isn't possible. FvwmM4 is no more in fvwm3. The real bug here is that the manpage needs updating.

**Comment by maoamid** [comment]
@ThomasAdam thank you for clarification
