### ISSUE TITLE
Incorrect highlighting color of the hotkey underline in menu items

### ISSUE THREAD

**Issue by ftonneau** [fvwmorg/fvwm3#894]
Using fvwm3 1.0.6a (released) built from AUR on Arch Linux, I see an aesthetic glitch on Fvwm menus: in the currently highlighted/selected menu item, the underline below the hotkey character stays with the default foreground color instead of assuming the foreground color for highlighted menu items. 

E.g., in the example attached, the default menu items are black on white and the highlighted menu items are white on red. The text in the highlighted menu item ("Maximize x") is white on red (as it should), but the underline below the final "x" is **black** on  red instead of white on red.

I realize that this is not a bug technically speaking (the program works correctly), but I do think this is an aesthetic glitch. I think that all Gtk applications have the hotkey underline assuming the current text color; and so does Openbox, for example.

![fvwm_menu](https://github.com/fvwmorg/fvwm3/assets/54842663/5860bcec-4d86-44c5-85a6-3000ae73ca8b)

**Comment by ThomasAdam** [comment]
Hi @ftonneau 


To "fix" this, we would have to redraw the menu item every time an item was highlighted.  This would not be a good thing to do.

I am not sure it's worth considering, so I'm going to close this report, but thanks for sending it through anyway.

**Comment by ftonneau** [comment]
Hi Thomas,

Obviously you are the one who knows about the source code, but I was a bit
puzzled by your reply. Isn't "redrawing the menu item every time an item is
highlighted" what fvwm is doing anyway when the colorsets for highlighted
and default items differ?

By the way, you may have seen that I am a new subscriber to the fvwm forum.
I am almost done with my fwmrc, and I will soon send appreciation comments
to the list. Fvwm is just ... amazing. Nothing can compare!

Best,
François

**Comment by ThomasAdam** [comment]
Hi @ftonneau 

Heh -- you're right that highlighting does redraw (XClearRegion()) the item, but what I was saying by redraw is to re-render the **text** of the menu, which would look very weird, and ultimately would cause visual glitches as it was redrawing.

**Comment by ftonneau** [comment]
I understand that the region (= the background) is redrawn, but so does the text (= foreground) in my example, as the highlighted text is white whereas the default text is black. Anyway, to get rid of the underline color discrepancy I now use the same text color for highlighted and default menu items, with good results :-)

![shot](https://github.com/fvwmorg/fvwm3/assets/54842663/8dfb08e5-dc69-4f57-9837-17247d60ec84)
