### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [fvwmorg/fvwm3#896]
Would you like to add more error handling for return values from functions like the following?
* [fclose](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream") ⇒ [WriteToFile‎](https://github.com/fvwmorg/fvwm3/blob/c9d00184ac3ab534e0f0ba5683106879a35857f6/modules/FvwmScript/Instructions.c#L1734)
* [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [main](https://github.com/fvwmorg/fvwm3/blob/c9d00184ac3ab534e0f0ba5683106879a35857f6/fvwm/fvwm3.c#L1852)

**Comment by ThomasAdam** [comment]
Hi @elfring 

Very few codebases which I have seen seem to care about checking for fclose()'s return value -- so I think we can skip that.

As for malloc, we should be using `fxmalloc()` instead, so if you wanted to send a patch through for that, I'd appreciate it.

**Comment by elfring** [comment]
* :thinking: How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
* :crystal_ball: How will chances evolve to benefit any more also from [the means of aspect-oriented software development](https://en.wikipedia.org/wiki/Aspect-oriented_programming "Documentation")?

**Comment by ThomasAdam** [comment]
I'm not sure I understand what you're asking with your second point -- this project doesn't use aspect-oriented software design.

**Comment by elfring** [comment]
:thought_balloon: I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

-----

:crystal_ball: Will interests grow for the application of higher level development tools?

**Comment by ThomasAdam** [comment]
Submit a pull request please with your suggestions for fclose and any other functions you feel are missing return value checks.
