### ISSUE TITLE
Simplify data processing for tint colour in parse_colorset()

### ISSUE THREAD

**Issue by elfring** [fvwmorg/fvwm3#897]
The analysis tool “Cppcheck 2.10.3-3.2” pointed the following information out for [a source code place](https://github.com/fvwmorg/fvwm3/blob/c9d00184ac3ab534e0f0ba5683106879a35857f6/fvwm/colorset.c#L965 "Update candidate: parse_colorset()").

…/Projekte/fvwm3/lokal/fvwm/colorset.c:965
(style) Condition 'tint==NULL' is always true [knownConditionTrueFalse]
CWE: 571

:thought_balloon: I imagine that duplicate code can be avoided a bit more by using the statement “`cs->tint = GetColor(tint ? tint : black);`” instead.

**Comment by ThomasAdam** [comment]
Hi @elfring 

It would really help me if you could submit pull request for these code changes. 

Thanks.
