### ISSUE TITLE
Avoid redundant variable assignments

### ISSUE THREAD

**Issue by elfring** [fvwmorg/fvwm3#898]
The analysis tool “Cppcheck 2.10.3-3.2” pointed the following information out for source code places like the following.

Id: redundantAssignment
CWE: 563

* [Variable '*changed' is reassigned a value before the old one has been used](https://github.com/fvwmorg/fvwm3/blob/c9d00184ac3ab534e0f0ba5683106879a35857f6/fvwm/colorset.c#L542 "Update candidate: parse_simple_tint()").
* [Variable 'has_pixmap_changed' is reassigned a value before the old one has been used](https://github.com/fvwmorg/fvwm3/blob/c9d00184ac3ab534e0f0ba5683106879a35857f6/fvwm/colorset.c#L1017 "Update candidate: parse_colorset()").
* [Variable 't->ol_hints' is reassigned a value before the old one has been used](https://github.com/fvwmorg/fvwm3/blob/c9d00184ac3ab534e0f0ba5683106879a35857f6/fvwm/decorations.c#L167 "Update candidate: GetOlHints()").

:crystal_ball: Will development interests grow accordingly?

**Comment by ThomasAdam** [comment]
Hi @elfring 

Again, thanks for looking at this. I have used cppcheck myself in the past. I could even run it myself if I wanted to. 

But the more valuable thing here is code changes. 

Please, would you send through a PR? Opening multiple issues like this isn't helping me.

**Comment by elfring** [comment]
:crystal_ball: Will related analysis tools trigger corresponding software improvements anyhow?

**Comment by ThomasAdam** [comment]
Only if you send me a patch.
