### ISSUE TITLE
Reconsider the check “>= 0” for pointers

### ISSUE THREAD

**Issue by elfring** [fvwmorg/fvwm3#899]
The analysis tool “Cppcheck 2.10.3-3.2” pointed the following information out for further development considerations.

Id: nullPointerRedundantCheck
CWE: 476

* [Either the condition 'cd->cs>=0' is redundant or there is possible null pointer dereference: cd->cs](https://github.com/fvwmorg/fvwm3/blob/c9d00184ac3ab534e0f0ba5683106879a35857f6/fvwm/borders.c#L3019 "Update candidate: border_draw_decor_to_pixmap()").
* [Either the condition 'td->cd->cs>=0' is redundant or there is possible null pointer dereference: td->cd->cs](https://github.com/fvwmorg/fvwm3/blob/c9d00184ac3ab534e0f0ba5683106879a35857f6/fvwm/borders.c#L3897 "Update candidate: border_get_titlebar_draw_descr()").

**Comment by ThomasAdam** [comment]
@elfring 

Please stop. Rather than opening issues, send me PRs.

**Comment by elfring** [comment]
How do you think about to replace the operator “`>=`” by “`!=`” in affected pointer checks? :thinking:

**Comment by ThomasAdam** [comment]
Depends on the check. 

That's the issue with static code analysis. You need to check every identified case for false positives.

**Comment by elfring** [comment]
Would you like to exclude null pointers at mentioned source code places? :thinking:

**Comment by ThomasAdam** [comment]
Do you have an example of what you mean?

**Comment by elfring** [comment]
:thought_balloon: Please take another look at the linked two source code places.

**Comment by ThomasAdam** [comment]
Maybe we should ignore them. Again, until you send me a patch, it's hard to know the impact of the changes.

**Comment by elfring** [comment]
:crystal_ball: Do you find a possible source code transformation easier to understand by the means of the semantic patch language?

Another script example:
```cocci
@replacement@
expression input1, input2, index, target;
@@
 if (input1
-    >=
+    !=
     0)
 {
 ...
 target = &input2[input1[index]];
 ...
 }
```

**Comment by ThomasAdam** [comment]
What I would like to see, is for each of your identified issues, the corresponding .cocci file you are using (which can live in `contrib/coccinelle` in the fvwm3 source tree), and the resultant code changes based on that .cocci file.

Do you think you're able to do that?

**Comment by elfring** [comment]
:crystal_ball: Would you like to apply any variations of the shown SmPL script example on more source files?

**Comment by ThomasAdam** [comment]
Until you generate a PR for this, I'm not commenting further. 

Same goes for all the other issues you've opened. 

Please, stop. Please heed my suggestions.

**Comment by elfring** [comment]
Why do you seem to refuse discussion on concrete issues before pull/merge requests?

**Comment by ThomasAdam** [comment]
I don't. I want to see proposed code changes which by themselves will generate discussion. Please. Try it.

**Comment by elfring** [comment]
Change suggestions can be automatically generated from [the presented SmPL script example](https://github.com/fvwmorg/fvwm3/issues/899#issuecomment-1703925760 "Change suggestion") (also for this issue).
:crystal_ball: Will the chances grow to achieve consensus on its implementation details?

**Comment by ThomasAdam** [comment]
I honestly feel like I'm being trolled. 

I don't want to generate the patch for you. I want to see the patch as part of a PR. 

Please. Last chance. If you'd like my help with this, please ask.
