### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [fvwmorg/fvwm3#900]
The function “[exit](https://pubs.opengroup.org/onlinepubs/9699919799/functions/exit.html "Terminate a process.")” does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function “[DeadPipe‎](https://github.com/fvwmorg/fvwm3/blob/c9d00184ac3ab534e0f0ba5683106879a35857f6/modules/FvwmForm/FvwmForm.c#L2748 "Update candidate")”.

**Comment by ThomasAdam** [comment]
@elfring 

I'm going to ask you one last time.  *Please* can you stop opening issues with descriptions of code changes, and instead send through a PR for the code changes you're describing?

**Comment by elfring** [comment]
:thought_balloon: I imagine that corresponding software design options need to be clarified before.
- [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html)
- [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html)
- [Signal-safe locks](https://locklessinc.com/articles/signalsafe_locks/)

**Comment by ThomasAdam** [comment]
No, not really.  Just send through a patch you feel looks right, and we can discuss it.

**Comment by elfring** [comment]
How do you think about to [concentrate signal handling in a corresponding thread](https://stackoverflow.com/questions/11679568/signal-handling-with-multiple-threads-in-linux "Signal handling with multiple threads in Linux")? :thinking:

**Comment by ThomasAdam** [comment]
For the love of god, @elfring send a patch through. Stop asking all these crappy ephemeral questions. 

This is your last warning. After this, I've a mind to block you.
