### ISSUE TITLE
FindScreenOfXY: couldn't find screen at 555 x 134 returning first monitor.  This is a bug.

### ISSUE THREAD

**Issue by voltumna** [fvwmorg/fvwm3#93]
is this a real bug?

**Comment by ThomasAdam** [comment]
No, I'll need to remove the debug... thanks for the reminder.

**Comment by ThomasAdam** [comment]
@voltumna -- feel free to write a patch to remove it.

**Comment by voltumna** [comment]
Oh alright, thank you :)

I wish I knew how to create a patch, sorry, I am a user, I am checking the logs because my fvwm3 seems to be missing a lot of supports: xpm, png, ttf etc... and I am looking at how to do it,

but luckily, I can simply ignore this error :smile:

**Comment by ThomasAdam** [comment]
Hi @voltumna 

> Oh alright, thank you :)
> 
> I wish I knew how to create a patch, sorry, I am a user, I am checking the logs because my fvwm3 seems to be missing a lot of supports: xpm, png, ttf etc... and I am looking at how to do it,

For this, you'll need to install the header files for these packages.  Some Linux distributions have these as `-deve` packages, hence:

```
libxpm-dev
libpng-dev
```

etc, etc.

> but luckily, I can simply ignore this error smile

No problem, I'll remove this.

-- Thomas
