### ISSUE TITLE
It's hard to click some menus of Steam

### ISSUE THREAD

**Issue by xuzhen** [fvwmorg/fvwm3#933]
## Upfront Information

Please provide the following information by running the command and providing
the output.

* Fvwm3 version (run: `fvwm3 --version`)
fvwm3 1.0.9 (released)
with support for:  ReadLine, XPM, PNG, SVG, Shape, XShm, SM, Bidi text, XRandR, XRender, XCursor, XFT, NLS

* Linux distribution or BSD name/version
Ubuntu 23.10

* Platform (run: `uname -sp`)
Linux x86_64

## Expected Behaviour

The menus do not disappear when the mouse is moved to it

## Actual Behaviour

Some menus disappear when I move the mouse to them, unless I move very quickly.

## Steps to Reproduce

Fvwm3 with blank configuration. `fvwm3 -f /dev/null`

Install and run Steam (https://store.steampowered.com/about)

Click the Steam/View/Friends/Games/Help on top, the menu appears. Move mouse to the menu, menu disappears.

https://github.com/fvwmorg/fvwm3/assets/360612/c4e625b1-7d79-43c9-8957-026fcd01c166

On other DE/WM, Steam behaves correctly. 

https://github.com/fvwmorg/fvwm3/assets/360612/1b1d0da1-aa5c-4bff-9f87-813856fb49d9

**Comment by ThomasAdam** [comment]
Duplicate of #924

**Comment by xuzhen** [comment]
OK. I'll post what I found in that issue.
