### ISSUE TITLE
Unable to initialise RandR (dup of #650, no workaround possible here)

### ISSUE THREAD

**Issue by spacelama** [fvwmorg/fvwm3#937]
## Upfront Information

* Fvwm3 version (run: `fvwm3 --version`)

fvwm3 1.0.6a (released)

* Linux distribution or BSD name/version

Would you believe Microsoft windows?
Linux DBJXCY3 4.4.0-19041-Microsoft #3636-Microsoft Thu Oct 19 17:41:00 PST 2023 x86_64 GNU/Linux

* Platform (run: `uname -sp`)

Linux unknown

## Expected Behaviour

Start fvwm3 under Xnest (fvwm2 works no problems) (possible prerequisite: running under windows, under mobaxterm for the X display, in a Debian bookworm image under WSL (phew!))

## Actual Behaviour

```
> fvwm2
FvwmIconMan: Internal error with select: errno=Interrupted system call
#(meh, not a problem for now, seems to fire up successfully)
^C

> fvwm3
Unable to initialise RandR
> echo $?
101
```

Should have started - not intending to use any randr functionality.  Should be able to fallback to just being a window manager.

## Steps to Reproduce

Find an environment without randr functionality, eg: under windows, under mobaxterm for the X display, in a Debian bookworm image under WSL, run Xnest (phew!))

```
> Xnest &
> export DISPLAY=:0
> fvwm3
> echo $?
```

Start fvwm3.  Should immediately exit 101 with "Unable to initialise RandR"

fvwm2 starts up successfully

Vanilla fvwm config from debian bookworm.  Just like #650, but I don't have a workaround available to me.

**Comment by somiaj** [comment]
Fvwm3 depends on RandR, while fvwm2 does not. Due to this if your xserver doesn't have RandR support you won't be able to use fvwm3. Instead of using `xnest`, use `xserver-xephyr`, as that has RandR support, and I run fvwm3 inside of it just fine.
