### ISSUE TITLE
Disabling decorations on some fullscreen windows

### ISSUE THREAD

**Issue by dpapavas** [fvwmorg/fvwm3#945]
Not sure if this is a bug with FVWM or not, but I'm having trouble getting some full-screen windows (most, if not all, created by game applications) to be mapped without decorations.

 Here’s an `xprop` output from one such window:

```
_NET_WM_USER_TIME(CARDINAL) = 28195825
_VARIABLE_REFRESH(CARDINAL) = 1
_NET_WM_ICON(CARDINAL) = Icon (128 x 128):
…
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 18, 0
_KDE_NET_WM_FRAME_STRUT(CARDINAL) = 0, 0, 18, 0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_STICK
_NET_WM_ICON_VISIBLE_NAME(UTF8_STRING) = “Space Tail”
_NET_WM_DESKTOP(CARDINAL) = 2
WM_STATE(WM_STATE):
window state: Normal
icon window: 0x0
_NET_WM_VISIBLE_NAME(UTF8_STRING) = “Space Tail”
XdndAware(ATOM) = BITMAP
_NET_WM_NAME(UTF8_STRING) = “Space Tail”
WM_NAME(STRING) = “Space Tail”
WM_PROTOCOLS(ATOM): protocols WM_DELETE_WINDOW, WM_TAKE_FOCUS
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 1
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 321007
WM_LOCALE_NAME(STRING) = “en_US.UTF-8”
WM_CLASS(STRING) = “Space Tail.x86_64”, “Space Tail.x86_64”
WM_HINTS(WM_HINTS):
Client accepts input or input focus: True
window id # of group leader: 0xdeb0df
WM_NORMAL_HINTS(WM_SIZE_HINTS):
user specified location: 0, 0
WM_CLIENT_MACHINE(STRING) = “debian”
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
```

As far as I can see (although I’m not sure I’m interpreting it correctly), the last line should instruct FVWM not to decorate the window if the `MwmDecor` style is used. I have this style (along with `MwmFunctions`, `MwmBorder`) applied globally, yet this window is still decorated.

I'm runing fvwm3 1.0.6a (released) on x86_64 Debian Stable.  Note that, although I've recently changed to FVWM3, I've been having such problems for years on FVWM2.

Please let me know if you need any more information.

**Comment by ThomasAdam** [comment]
Probably related to #574 -- see comments therein.

**Comment by dpapavas** [comment]
I saw this before opening this issue, but contrary to that case and [this one](https://fvwmforums.org/t/fvwm-full-screen-sdl/3121) for example, setting `MWMDecor` doesn't result in no decorations on such windows for me.  Might something else in my configuration be interfering with it?
