### ISSUE TITLE
new window to popup close to my mouse pointer?

### ISSUE THREAD

**Issue by harridu** [fvwmorg/fvwm3#948]
## Describe the new feature

Using a pretty large monitor (49") it is unpredictable where the next window will pop up. Would it be possible that new windows are placed as close to the current mouse pointer as possible, without overlapping other windows (if possible)?

## How might fvwm3 need to change?

This would be some new placement style. Please excuse if I was too blind to see.

## Can this be achieved through scripting?

I have no idea.

**Comment by ThomasAdam** [comment]
Style * PositionPlacement under mouse

**Comment by harridu** [comment]
@ThomasAdam , this is not what I meant. UnderMouse just opens the window under the mouse, ignoring empty space. The suggestion was to open it as close as possible to the mouse pointer, see above. Overlapping other windows should be avoided.
