### ISSUE TITLE
Desk 0 not accessible.

### ISSUE THREAD

**Issue by rasatpc** [fvwmorg/fvwm3#957]
## Upfront Information

* Fvwm3 version (run: `fvwm3 --version`)
Version 1.1.0

## Expected Behaviour
What were you trying to do?  Please explain the problem.

Ivar on Fvwm forum, upgraded to 1.1.0 and he cannot access Desk 0 in the pager with 4 desks. Left-click mouse cursor does not work on desk 0 but does on 1, 2 and 3.
https://fvwmforums.org/t/desktopname-0/4594

* Reduce the problem to the smallest `fvwm` configuration example (where
  possible).  Start with a blank config file (`fvwm3 -f/dev/null`) and go from
  there.

I did a test on 1.1.0. Desk 0 is not accessible with the mouse cursor on a pager.

#########
DesktopName 0 Web
DesktopName 1 Email
DesktopName 2 Office

DesktopSize "2 1"  ## (columns - rows)

Module FvwmPager VdeskPager 0 2  ## (desk number - number of desks)

DestroyModuleConfig VdeskPager: *
*VdeskPager: Geometry 150x240-0+0
*VdeskPager: Rows 3  ## (page rows)
*VdeskPager: Colorset * 15 ##  RootTransparent requires Picom.
*VdeskPager: HilightColorset * 17  ## (active page background)
*VdeskPager: BalloonColorset * 10  ## (font color)
*VdeskPager: WindowColorsets 13 18  ## (inactive - active apps)
*VdeskPager: Font "xft:Sans:size=12:antialias=True"
*VdeskPager: WindowBorderWidth 1
*VdeskPager: BalloonStringFormat %c
*VdeskPager: BallonYOffset +2
*VdeskPager: Window3dBorders
*VdeskPager: UseSkipList # hides modules
*VdeskPager: MiniIcons

Style VdeskPager NoTitle, !Handles, Borders, BorderWidth 1, BorderColorset 6, Sticky, WindowListSkip, FixedSize, !Iconifiable

**Comment by rasatpc** [comment]
The problem is still there. Also, I updated my fvwm3 fork.
"This branch is up to date with fvwmorg/fvwm3:main".

**Comment by ThomasAdam** [comment]
Hi @rasatpc 

Please try the `ta/gh-957` branch, where I believe this should now be fixed.

**Comment by rasatpc** [comment]
Doesn't work. The pager (VdeskPager) does not appear.

**Comment by rasatpc** [comment]
Pager disappearing was a config problem. After fixing it, still Desk 0 is not assessable with mouse course.

**Comment by ThomasAdam** [comment]
It works fine for me. Can you suggest ways of how I can reproduce this if it's still not working for you, @rasatpc ?

**Comment by rasatpc** [comment]
1. Start Fvwm with empty .fvwm/ folder.
2. Add this test pager script to an empty file name config.

Colorset 2  fg #ffffff, bg #2b4e5e, hi, sh, Plain, NoShape
Colorset 6  fg #ffffff, bg #88b2b1, hi, sh, Plain, NoShape
Colorset 7  fg #999999, bg #cbdcca, hi, sh, Plain, NoShape
Colorset 10 fg #ffffff, bg #2b4e5e, hi #aaaaaa, sh #999999, Plain, NoShape

DesktopName 0 Web
DesktopName 1 Email
DesktopName 2 Office

DesktopSize "2 1"

Module FvwmPager TestPager 0 2

DestroyModuleConfig TestPager: *
*TestPager: Geometry 150x240-0+0
*TestPager: Rows 3
*TestPager: HilightColorset * 7
*TestPager: BalloonColorset * 10
*TestPager: WindowColorsets 6 2
*TestPager: UseSkipList
*TestPager: MiniIcons

Style TestPager NoTitle, !Handles, Sticky, WindowListSkip

3. Restart

Click Email desk and go back to Web desk. With mouse cursor can't access Web desk. Only works with command GoToDesk 0 0 0.

**Comment by rasatpc** [comment]
Didn't see yesterday's gh-957 update.  Desk 0 works but with right-click. Change to left-click.

**Comment by rasatpc** [comment]
I did one test with a fresh install with main and ta-gh-957 branch. And, new login to a clean desk with RightPanel.

*main branch with mouse cursor
1.  Desk 0 works fine until going to other Desk (1,2,3) 
2.  I added one xterm in each desk to see any desk changes. There are problems.

*ta-gh-957 branch
1. Min-window doesn't appear
2.  With FvwmConsole run Module FvwmPager and min-window appears.

I will wait for the merge.

**Comment by ThomasAdam** [comment]
Hi @rasatpc 

OK, there were actually two things going on here -- but your original bug report didn't clarify much.  

As it happens though, on the `ta/gh-957` branch, you should now find that switching between desks using the `RightPanel` config works as expected.

Let me know how  you get on, and if there's anything else related to this bug report which needs fixing.

**Comment by rasatpc** [comment]
Lastly, default config,  I did a test on ta/gh-957 with the VdeskPager that I used as a sample. in this report. To change desk between Web, Email,  and Office only right-click. The page change is ok with left-click.

First, check if the VdeskPager config is correct.
