### ISSUE TITLE
FvwmPager (mini window)

### ISSUE THREAD

**Issue by rasatpc** [fvwmorg/fvwm3#959]
## Upfront Information

* Fvwm3 version (run: `fvwm3 --version`)
fvwm3 1.1.0 (released)

EDIT: ta/gh-957

## Actual Behaviour
Configs with FvwmPager, the mini window is not appearing at the right time. Mjaakko found the issue and gave a few examples.
https://fvwmforums.org/t/desktopname-0/4594/4

Note: In main branch, FvwmPager works ok.

**Comment by ThomasAdam** [comment]
Hi @rasatpc 

This is working fine for me -- so I can only assume it's configuration-related.
